### ISSUE TITLE
How to bypass spacy for another language parsing?

### ISSUE THREAD

**Issue by nandan29rathod** [HazyResearch/snorkel#1001]
I have to use the snorkel for the Indian languages like Hindi and spacy parsing does not work for the Hindi language.
Can anybody help me how to use another parsing which helps to extract candidates in non-English languages?

**Comment by jason-fries** [comment]
Hi @nandan29rathod,
Snorkel supports [CorenNLP](https://github.com/HazyResearch/snorkel/blob/master/). If you edit the `_start_server` and `_conn_opts` functions in `snorkel/parser/corenlp.py`, you should be able to load other language models. Once that's changed, it's easy to just swap out a call for spaCy with a call to CoreNLP.
