### ISSUE TITLE
Non-English tutorial

### ISSUE THREAD

**Issue by nandan29rathod** [HazyResearch/snorkel#1004]
Hello guys,
I have a lot of issues which concerns about snorkel to use for other languages than English. Can you guys create a simple tutorial for a non-English dataset which spacy does not support? Using coreNLP, providing POS, NER tags etc. not from using spacy. Because spacy only for standard languages (here English,French, German,Spanish).
It would be very helpful.

**Comment by jason-fries** [comment]
See Issue #1001
