### ISSUE TITLE
ModuleNotFoundError: No module named 'snorkel'

### ISSUE THREAD

**Issue by HarrietLyBui** [HazyResearch/snorkel#1007]
I tried the latest snorkel installation by following the instruction. However, when I tried to run the tutorials, I got following errors 

ModuleNotFoundError: No module named 'snorkel'

**Comment by jmugan** [comment]
I was getting that too. It looks like you have to remove `~/Library/Jupyter/kernels`. See the accepted answer here https://stackoverflow.com/questions/47277958/error-module-not-found-in-jupyter-notebook-sklearn. That just brings me to another error about `etree.cpython-36m-darwin.so`, but at least it is progress.

**Comment by loveJasmine** [comment]
it time to consider give up conda env

**Comment by akshitj1** [comment]
removing `~/Library/Jupyter/kernels` as @jmugan suggested will remove your existing kernels. Try adding the new kernel with snorkel env:
`python -m ipykernel install --user --name snorkelenv --display-name "Python (snorkel-env)"` . 
Select this kernel in your jupyter notebook.

**Comment by bhancock8** [comment]
As @akshitj1 pointed out, the most probable culprit is that your jupyter kernel is not your environment where snorkel is installed. You can either install the `nb_conda_kernels` package to make all your conda environments available in jupyter, or run the command in the README (and mentioned above) to add a single snorkelenv explicitly. Reopen if this doesn't solve your issue.
