### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by loveJasmine** [HazyResearch/snorkel#1017]
mldl@ub1604:~/ub16_prj/snorkel/tutorials/intro$ PYTHONPATH=../../treedlib/ python Intro_Tutorial_3.py 
marginal_tuples is []
Traceback (most recent call last):
  File "Intro_Tutorial_3.py", line 45, in <module>
    train_marginals = load_marginals(session, split=0)
  File "/home/mldl/ub16_prj/snorkel/snorkel/annotations.py", line 567, in load_marginals
    cardinality = session.query(Candidate).get(marginal_tuples[0][0]).cardinality
IndexError: list index out of range

**Comment by ZefengHan** [comment]
excuse  me， how do you solve this problem? I have delete snorkel.db, but it doesn't change anything. Also  return the same wrong.
![image](https://user-images.githubusercontent.com/37654359/56454060-06a4bf00-637e-11e9-8601-35c039d0667a.png)
