### ISSUE TITLE
How to use pytorch with GPU?

### ISSUE THREAD

**Issue by jbkoh** [HazyResearch/snorkel#1023]
Hi,

I am trying to use GPU with Pytorch in the tutorial. In my limited knowledge, we should explicitly indicate that I want ot use GPU in Pytorch something like
```python
model = LSTM().cuda()
```
However, I don't know how to change the training datasets generated from ``Snokel.Session`` to GPU enabled format that PyTorch can accept because the dataset variables are in a list of snorkel's custom classes, which I can't force the format with ``cuda()`` function. Could you provide an instruction about how to use GPU with PyTorch in Snorkel?

Thanks!

**Comment by bhancock8** [comment]
Closing this in favor of #1028.
