### ISSUE TITLE
installation error for pytorch-cpu >=0.4

### ISSUE THREAD

**Issue by luofanghao** [HazyResearch/snorkel#1025]
Hi, encountered this error when installation:

![screen shot 2018-09-06 at 7 55 56 pm](https://user-images.githubusercontent.com/7426314/45196002-0d2b5f80-b20f-11e8-8488-ac0bc8bcb09d.jpg)

I am using macOS.

**Comment by mrosett** [comment]
`pytorch-cpu` doesn't have a version for macOS - see [here](https://anaconda.org/pytorch/pytorch-cpu). If you don't need pytorch functionality, simply removing it from `environment.yml` let me get everything up and running. So far the tutorials seem to be working.

**Comment by luofanghao** [comment]
Thank you! I solved by install pytorch separately and removed it from `environment.yml`.
