### ISSUE TITLE
Candidate Extraction Analysis

### ISSUE THREAD

**Issue by sampanriver** [HazyResearch/snorkel#1026]
I want to analysis the precision/recall of my customized candidate extractor with a golden set. Is there any way that could easily achieve that?

**Comment by paroma** [comment]
You can use the `error_analysis` function [here](https://github.com/HazyResearch/snorkel/blob/b047dfb032560584752cb5952a82b90943529209/snorkel/learning/classifier.py#L93) and pass in the predicted and gold labels to calculate statistics about your candidate extractor
