### ISSUE TITLE
Pandas version of crowdsourcing tutorial

### ISSUE THREAD

**Issue by tmerrittsmith** [HazyResearch/snorkel#1030]
I've edited the crowdsourcing tutorial to use pandas instead of spark. It was useful for me, so may be useful to others. Do you want it?

**Comment by ajratner** [comment]
@tmerrittsmith yes!!  This would be awesome!  We definitely want to keep the spark one, but could have the pandas version as a separate notebook?  Thanks!!

**Comment by tmerrittsmith** [comment]
Cool. Yeah the spark one is definitely worth keeping - it's like the Ferrari version, where mine is the second hand hatchback... 

I'll tidy up what I've got, but can provide two possibilities:
1) A straight conversion of the crowdsourcing tutorial (exactly the same data and results), just using pandas where spark was used (to be honest, I didn't use pandas that much apart from joining the csvs at the beginning)

2) Something more similar to the intro tutorial, but for tabular data. We wrote some labelling functions for a UCI repository dataset, and then used snorkel's generative model to resolve the labels.

What's the best way to get them to you, once they're ready?

**Comment by ajratner** [comment]
Hah :) . Both of these sound awesome- whatever you can send, we'll look over!  And best way would be a PR (separate ones for each).  Thanks!!

**Comment by tmerrittsmith** [comment]
Sorry, haven't got round to making the PR - I'll do that today.

**Comment by ajratner** [comment]
@tmerrittsmith awesome thanks!!

**Comment by hanzlfs** [comment]
@tmerrittsmith thanks! I think your PR is good enough to have insights.

**Comment by ajratner** [comment]
@paroma assigned to you since you're looking at the PRs!

**Comment by paroma** [comment]
thank you for submitting this PR! (merged with #1048)

**Comment by gauthamkrishna-g** [comment]
@tmerrittsmith Could you kindly update on the tabular data PR in case you have any leads? Thanks!
