### ISSUE TITLE
Error: Tutorial 1 - articles.tsv not found.

### ISSUE THREAD

**Issue by skk123123** [HazyResearch/snorkel#1032]
Hi,
I have completed the snorkel setup and while running Tutorial 1, I get t
he following error after executing this line of code :
%time corpus_parser.apply(doc_preprocessor, count=n_docs)

Error details.
~/snorkel/HazyResearch-snorkel-97591ff/snorkel/parser/doc_preprocessors.py in _get_files(self, path)
     69             return fpaths
     70         else:
---> 71             raise IOError("File or directory not found: %s" % (path,))
     72
     73

**OSError: File or directory not found: data/articles.tsv**

As I can see the data directory doesn't exist. Is there any step that I am missing here ?
 Thanks.

**Comment by paroma** [comment]
Is this for Intro_Tutorial_1? The [repo](https://github.com/HazyResearch/snorkel/tree/master/tutorials/intro/data) has a `data/` folder with the `articles.tsv` file now!
