### ISSUE TITLE
create training data sets for multi-classification task 

### ISSUE THREAD

**Issue by darshdonnii** [HazyResearch/snorkel#1036]
Hi,
Thanks for this interesting system. 
I have a multi-classification task on text documents(10 different classes),  in each class I have a list of terms that describe the related class,  only 200 documnets are manually labeled by experts into their classes. 

the 200 labeled documents are not enough to train a classifcation model. 
Hier i'm asking, if it is possible to write labeling functions in Snorkel to imporove my training data. the list of terms of each class can help in this scenario.
currentl, I just have theoritical overview of Snorkel. 

Does Snorker helps in this case? how can I write labeling functions for this case?

Any help will be greatly appreciated.
Thanks

**Comment by paroma** [comment]
If you have more *unlabeled* documents, you can use Snorkel to write labeling functions to label these documents using the list of terms for each class you have. You can take a look at the [intro tutorial](https://github.com/HazyResearch/snorkel/tree/master/tutorials/intro) or the [CDR tutorial](https://github.com/HazyResearch/snorkel/tree/master/tutorials/cdr) for an example of how Snorkel is applied in this case!
