### ISSUE TITLE
Error during Snorkel installation

### ISSUE THREAD

**Issue by kalpmail** [HazyResearch/snorkel#1037]
I am getting an error even in the first step to install Snorkel. I use Python 3.6. Please see the attached screenshot. 
![screenshot 2018-11-14 17 28 46](https://user-images.githubusercontent.com/7083177/48563645-66bca400-e8ba-11e8-9658-a6184d76d42e.png)

**Comment by stephenbach** [comment]
Hi, thanks for checking out Snorkel!

Looks like you’re on a Mac and need to install XCode (https://developer.apple.com/xcode/)

**Comment by kalpmail** [comment]
Hi Stephen

Thanks a lot! Yes, I am using Snorkel on Mac. 
Based on your suggestion, first, I installed XCode and then, Snorkel. Installation is successful.
