### ISSUE TITLE
ResolvePackageNotFound:    - pytorch-cpu[version='>=0.4']

### ISSUE THREAD

**Issue by kemathur** [HazyResearch/snorkel#1043]
Was trying to play with snorkel based on the mentioned instructions.
Ran this:
conda env create --file=environment.yml

Had to update file to be just pytorch.

**Comment by minhtriet** [comment]
In case you are using MacOS, change the line `pytorch-cpu[version='>=0.4']` to `pytorch`

**Comment by Drakensberge** [comment]
can confirm this works

**Comment by bhancock8** [comment]
This is now fixed in #1063 with pytorch 1.0.
