### ISSUE TITLE
CDR tutorial zip data is empty

### ISSUE THREAD

**Issue by ombinar** [HazyResearch/snorkel#1045]
Hi all,

Is there an alternative data source? This is empty - http://www.biocreative.org/media/store/files/2016/CDR_Data.zip

cdr > download_data.sh

Thanks,

Ricky

**Comment by shizifan** [comment]
Try this link:
https://excellmedia.dl.sourceforge.net/project/bioc/CDR_Data.zip

**Comment by ajratner** [comment]
@shizifan thanks for the link!  I just tried however and the original link is working for me.  Feel free to re-open if any problems again!
