### ISSUE TITLE
how to generate PASCAL VOC or MSCOCO labels for image training data 

### ISSUE THREAD

**Issue by AllenDun** [HazyResearch/snorkel#1046]
Hi,
it's a great repo. I am working in the computer vision area, such as image classification and detection. PASCAL VOC or MSCOCO labels are widely used in CV area. How to generate these labels using Snorkel?
It is not very clear in the image tutorial.

**Comment by paroma** [comment]
In the image tutorial, we use the bounding box and category labels from the [Visual Genome dataset](https://visualgenome.org) to write labeling functions to detect a person or bike. More examples on how labeling functions can be used over image data in this [paper](https://papers.nips.cc/paper/6628-inferring-generative-model-structure-with-static-analysis)
