### ISSUE TITLE
CandidateExtractor very low core usage with `parallelism=80`

### ISSUE THREAD

**Issue by npow** [HazyResearch/snorkel#1047]
I'm running the CandidateExtractor with `parallelism=80`, but I'm getting very low core usage. I'm using postgresql as per the "parallel processing" tutorial. Is there something else I need to configure to get more parallelism?

![image](https://user-images.githubusercontent.com/206201/51125628-0cbf5880-17ef-11e9-80c1-a0128591285f.png)

**Comment by ajratner** [comment]
Hi @npow unfortunately I'm not sure without more info.  That being said, we're not actively working to optimize the parallel processing capabilities in this repo at the moment, so there might be some easy ways to speed this up if you're interested in digging into and submitting a PR!  Closing in the mean time
