### ISSUE TITLE
BRAT : Unable to launch in browser

### ISSUE THREAD

**Issue by skk123123** [HazyResearch/snorkel#1050]
I run this code in the Snorkel workshop
brat.view("spouse/train", doc)
When I click on LaunchBRAT  - 
I get 404 error at the following URL
http://localhost:8889/index.xhtml#/spouse/train/5ede8912-59c9-4ba9-93df-c58cebb542b7

I have independently tested BRAT and it works fine in the browser.

**Comment by paroma** [comment]
try opening the window in the browser: `brat.view("spouse/train", doc, new_window=False)`?
