### ISSUE TITLE
Incorporating invariances

### ISSUE THREAD

**Issue by mhigginslp** [HazyResearch/snorkel#1057]
Is there a way to incorporate text invariances (ways you can change a text without affecting it's classification) into snorkel?

**Comment by ajratner** [comment]
Hi @mhigginslp great question!  For some of our work on accomplishing this via the approach called _data augmentation_, check out [this blog post](https://hazyresearch.github.io/snorkel/blog/tanda.html) (corresponding to [this NeurIPS 2017 paper](https://arxiv.org/abs/1709.01643), and [this repo](https://github.com/HazyResearch/tanda))
