### ISSUE TITLE
Lots of simple rules or fewer complex rules?

### ISSUE THREAD

**Issue by mhigginslp** [HazyResearch/snorkel#1060]
We are currently applying snorkel to text classification with ~20 classes (in the future it will be more like 100).  Right now there is 1 rule per class and they are rather complicated.  It looks something like:  S_1, S_2, S_3 are long sets of words.  If a text contains **any** word from S_1 **and** **any** word from S_2 but **no** word from S_3 then it belongs to class Y.  

You could imagine separating this into many more rules ...  |S_1|*|S_2|*|S_3| if we use one word from each list, or 2^|S_1|*2^|S_2|*2^|S_3| if we take every subset of every list!

Do you have any intuition, empirical/theoretical results about how many rules are appropriate?  How would you think about breaking these rules up (if that is advised)?

**Comment by paroma** [comment]
This is a great question! We have details on the theoretical results about number of labeling functions required in this [paper](https://arxiv.org/abs/1605.07723)

The Snorkel generative model learns one accuracy per labeling function. If you want to model the accuracy of the words in S1, S2, and S3 separately, then splitting them into multiple rules would be the way to go. We would be glad to hear about how splitting rules vs. keeping complex rules worked for your task!

**Comment by mhigginslp** [comment]
I also found these great guides as well:
https://www.youtube.com/watch?v=mrIkus844B4&feature=youtu.be

And this real world application.
https://towardsdatascience.com/a-technique-for-building-nlp-classifiers-efficiently-with-transfer-learning-and-weak-supervision-a8e2f21ca9c8
