### ISSUE TITLE
Recursively feed LF outputs as noisy crowd labels

### ISSUE THREAD

**Issue by sampathkethineedi** [HazyResearch/snorkel#1061]
I want to add additional domain specific labeling functions to existing generic annotations. So I was thinking of recursively feeding outputs as noisy crowd labels. Is there an existing implementation or pipeline architecture for this?

**Comment by sampathkethineedi** [comment]
I wanted to know how many individual annotations are ideal for the generative model. Also would using the output after every loop as a new crowd worker annotation set improve the accuracy?

**Comment by ajratner** [comment]
Hi @sampathkethineedi I may not understand the proposed setup entirely?  I think there are two aspects you refer to:

(1) _Incorporating crowd labels + LFs together:_ You can certainly do this!  One option is just to directly feed the crowd labels in as their own labeling function or set of labeling functions (e.g. one per crowd worker), in which case Snorkel will automatically learn an accuracy for each crowd worker!

(2) _Feeding outputs of the generative / discriminative model back in as LFs:_ This might lead to degenerate settings... but could work?  Seems like a cool research question to check out!  And no, no existing architecture for this- but always happy to accept PRs and/or here about empirical results!

Closing for now, but feel free to re-open
