### ISSUE TITLE
Error in RegexTokenizer

### ISSUE THREAD

**Issue by iamsimha** [HazyResearch/snorkel#1069]
When I tried to use RegexTokenizer 
```python
CorpusParser(parser=RuleBasedParser(sent_boundary=RegexTokenizer(" ")))
```
I get an error 

```
TypeError: '<' not supported between instances of 'str' and 'int'
```
 at https://github.com/HazyResearch/snorkel/blob/3a8126045d9ca332de3e3a94e6d3d620f6260598/snorkel/parser/rule_parser.py#L46

This seems like a bug to me, where we are expecting string to be an integer.

**Comment by bhancock8** [comment]
I think you're right. PRs welcome!
