### ISSUE TITLE
Dependency Selection

### ISSUE THREAD

**Issue by wfjin** [HazyResearch/snorkel#1070]
What does each type of dependency mean for the output of dependency selector?

```
DEP_SIMILAR = 0
DEP_FIXING = 1
DEP_REINFORCING = 2
DEP_EXCLUSIVE = 3
```

How shall we select dependencies, and  how many dependencies do you recommend for N samples?

**Comment by ajratner** [comment]
Hi @wfjin these dependency types correspond to those listed in the NeurIPS'16 and ICML'17 papers (see snorkel.stanford.edu).  However we are in the process of refactoring all of this code for the upcoming v0.9 release, where we have a new simplified approach for learning the dependency structure (see ICML'19 paper, also posted online), which focuses just on the first type of basic 'is similar' dependencies.

I'll close this for now, but feel free to re-open if any questions, esp. once the v0.9 release is out!
