### ISSUE TITLE
Can't seem to do better than Majority Vote

### ISSUE THREAD

**Issue by edu-gp** [HazyResearch/snorkel#1073]
I'm working on a binary classification task, and I have 4 LF's so far. I have a labelled dev dataset (around 10k datapoints) and measured the coverage and accuracy:

```
	name	coverage	accuracy
0	LF_0	1.000000	0.848231
1	LF_1	1.000000	0.915177
2	LF_2	1.000000	0.856611
3	LF_3	0.644972	0.959723
```

After creating the labels matrix (of size `n_datapoints x n_labelling_functions`) I pass that into Snorkel's GenerativeModel. (I also tried playing around with specifying dependencies, but they didn't help much; makes sense since I believe these LF's are independent).

Visualizing the marginals, they look great (the class unbalance is expected):
![LF_marginals](https://user-images.githubusercontent.com/46904813/54338258-c8421480-4607-11e9-95da-9e4e9f0353c9.png)

I try to use the marginals from the GenerativeModel to make predictions on my dev set (so if the marginal is > 0.5, then it predicts 1, else it predicts -1). Using this, I get the same F1 score as majority vote:

```
F1
Snorkel Generative: 0.6863292148266241
Majority Vote:      0.6863292148266241
```

However, if I remove LF_3 (so now all LF's have perfect coverage and varying accuracy), I actually end up doing worse than majority vote:

```
F1
Snorkel Generative: 0.6587171052631579
Majority Vote:      0.6853526220614827
```

Snorkel doing worse or just on-par with Majority Vote is worrisome. Consider a "weighted majority vote"; if I learn these weights against my dev set, that should perform better than an unweighted majority vote, and even better than Snorkel!

What's the intuition behind why Snorkel would be on-par or do worse than MV? Am I not writing the right labelling functions? Am I assessing my metrics wrong?

Any pointers would be greatly appreciated. Thanks!

**Comment by ajratner** [comment]
Hi @edu-gp ,

Thanks for the detailed post!  To start, I'll note it's often a little hard for us to debug or comment without more knowledge of the dataset / task, and getting hands on... but I can ask about a few summary statistics.

First, what's the rate of "conflict" i.e. disagreement between the labeling functions?  Assuming this is a binary problem, do they all output both labels, or do some only ever either abstain or vote one way?  And finally, how are you training the generative model?  Are you doing a hyperparameter search with the dev set, or just running and tuning by hand?

I'll also quickly note a few higher-level things:
- Regardless of the above stats, four labeling functions is definitely on the low end of where the Generative Model will add significant value over MV (see the VLDB 2018 paper for more theoretical intuition here).  In fact, three LFs is the minimum needed to learn something beyond MV according to our theory!
- However, Snorkel is not just the Generative Model.  In fact, in some cases it may make sense (for various practical reasons) to just run MV at this stage, and use the rest of the Snorkel pipeline this way!
- We also have a new version of the Generative Model in our new [Snorkel metal](https://github.com/HazyResearch/metal) repo, in progress, but might be helpful depending on what's going on here
- Training on the dev set as you mention could be an option, especially for such a simple configuration (four LFs, no strong dependencies), however if you developed your LFs with the dev set (as is the default workflow we build around), then this small dev set will be quite significantly biased.  Either way, in the end it's an empirical question that can vary from case to case!

Hope this helps!
Alex
