### ISSUE TITLE
Class Imbalance for the OTHER class

### ISSUE THREAD

**Issue by wfjin** [HazyResearch/snorkel#1076]
It is very common to have an "other" class in the intent classification system to handle the intents/classes that are "outside" of our current intended ones.

Sometimes the "other" class can be quite significant, more than 30% of the total, and it is extremely difficult to write proper LFs for the "other" class (that's the point of the class indeed!)

I am wondering what kind of suggestions you guys would think to handle the "other" class. We tried to create a LF to handle that in way that if all other LF abstains, then return "other". But it does not work well as it restricts the generalization power of the generator.

**Comment by paroma** [comment]
Thanks for the question! My best guess here is try writing a few LFs for this class, even if it's fairly low coverage. If you're doing a binary task, you can let this "other" class be the 3rd class. When training the generative model, you can pass in the class balance with "other" being 30% and see how the model does

**Comment by paroma** [comment]
Closing for now, feel free to re-open with any questions!
