### ISSUE TITLE
Labeled Dataset as output

### ISSUE THREAD

**Issue by sampathkethineedi** [HazyResearch/snorkel#1079]
The generative model returns probability for each labeling function and then trains a discriminative end model over the marginals. If my aim is to generate a relatively less noisy labeled data from noisy labeling functions without training an end extraction model, how do I go about it? Is there a built in snorkel pipeline which does this?

**Comment by vumaasha** [comment]
The generative model produces the marginals over Y i.e P(Y). You just have to do an argmax if you want to get noisy class labels instead of marginals

**Comment by sampathkethineedi** [comment]
But that will only give me the labeling function with highest probability. I would rather train an end extraction model and store the predicted class for each candidate as the label. Would this be a good approach?

**Comment by vumaasha** [comment]
@sampathkethineedi you could of course learn a discriminative model, it depends on the label density whether it will be beneficial or not. Please refer to the paper https://arxiv.org/abs/1711.10160

**Comment by paroma** [comment]
Closing this for now, feel free to reopen!
