### ISSUE TITLE
Benefit of using snorkel comparing without using snorkel for data progrmaming

### ISSUE THREAD

**Issue by Mike9035** [HazyResearch/snorkel#1080]
Alex Ratner:
             
     We try to apply your data programming method for our project.
     I found an example/code given in https://hazyresearch.github.io/snorkel/blog/dp_with_tf_blog_post.html, which is easy to follow and understand.

     My problem is that I can not find any example in snorkel tutorials which is similar with
     example you used in DataProgrammingTensorFlow-v2 (easy matrix setting for data 
     points and corresponding features' value) So I don't know how to
     use snorkel for our problem which is very similar with example you used in
     DataProgrammingTensorFlow-v2.

     My question:
      1). Do you have any similar example as used in DataProgrammingTensorFlow-v2 but it use snorkel package/framework? If yes, where I can find these examples.
      2). What is benefits to use snorkel for our application comparing with directly following your example in DataProgrammingTensorFlow-v2 without using snorkel? Or is there any problem if we directly modeling noisy training set generation process by learning a generative model, i.e. learning labeling functions' accuracies by observing their overlaps (using a matrix completion objective) as in your example to our application without using snorkel ?

      Mike

**Comment by ajratner** [comment]
Hi @Mike9035 ,

Sorry for the delayed response here!  The example in the notebook you reference handles a simplified setting where we assume balanced binary classes (`P(Y=1) = P(Y=-1) = 0.5`), LFs with symmetric accuracies (same on both classes), and no dependencies.  In the main snorkel package we handle the more general cases for all these assumptions!

However, worth noting that we have a new matrix completion-style approach (published in AAAI'19 paper posted at snorkel.stanford.edu) which is similar to the algorithm in that notebook, and also handles the extended settings above.  We'll be merging this version into the upcoming v0.9 release of Snorkel!

Hope this helps- closing for now but feel free to re-open
