### ISSUE TITLE
SentenceNgramViewer 'gold' argument error 

### ISSUE THREAD

**Issue by eric-czech** [HazyResearch/snorkel#1082]
Should these lines in the viewer :

https://github.com/HazyResearch/snorkel/blob/cfbbb1dbd3a835b1ddfa129e851797a2833676b0/snorkel/viewer/__init__.py#L166-L167

instead be like this?

```python
candidates = [c for c in self.candidates if c[0].get_parent() == context]
gold = [g for g in self.gold if g[0].get_parent() == context]
```

I'm struggling to see what Context subclass or other model even has a ```context_id``` attribute so I'm assuming that may be incorrect since making that change and passing in a list of candidates for the ```gold``` argument to ```SentenceNgramViewer``` at least avoids an ```Attribute 'context_id' does not exist``` error.

**Comment by bhancock8** [comment]
I think you're right. I don't think the SentenceNgramViewer is part of the unit tests at the moment, so it likely didn't get updated in a previous refactor. If you submit a PR with this fix, we'll merge it in!
