### ISSUE TITLE
LSTM error while training the end extraction model

### ISSUE THREAD

**Issue by msank00** [HazyResearch/snorkel#1095]
Hi Team,

I am trying to run the end extraction model, almost similar to the Intro 3 tutorial.

Below is the screenshot of the code and error. Can anyone point to me what might be the possible reason for this error?

![image](https://user-images.githubusercontent.com/11691571/55948426-23e6d880-5c6e-11e9-97e4-3cc407621390.png)

**Comment by v2-dev** [comment]
What candidates are you trying to extract?

**Comment by msank00** [comment]
Single person's name

**Comment by v2-dev** [comment]
Ok, I've got the same kind of errors. What's inside L_gold_dev? Apparently, to extract a single entity we should use TagRNN class, see this issue https://github.com/HazyResearch/snorkel/issues/896

**Comment by paroma** [comment]
Closing this for now, feel free to reopen for discussion!
