### ISSUE TITLE
How do you deploy the models learned by Snorkel?

### ISSUE THREAD

**Issue by cyruszhang** [HazyResearch/snorkel#1097]
I assume the pre-processing / candidate generation / labeling functions / generative model / discriminative model all have to be deployed in the inference pipeline. 

That brings me to the question:
If we use crowdsourcing as one of the LF, then that means this LF when deployed needs to really get the signal from the crowd again, which means delay and blocking. 

Am I understanding this right?

**Comment by bhancock8** [comment]
Hi Cyrus, good question! And the answer is very fortunately: No. The labeling functions + generative model are run offline to create a training set for training your discriminative model. Then at inference time, it's the same pipeline as a model trained via gold labels: you'll still need to pre-process your data and create candidates to make predictions about, but the (now trained) discriminative model makes predictions directly.

We often refer to this concept has "servable" vs "non-servable" features---the Snorkel setup allows you to supervise your model with all sorts of signals (including ones that are slow, such as crowd-sourcing), but then you can transfer this knowledge to a servable model that fits the form factor you require (e.g., low latency).

For more discussion on this point, you can check out the section titled "Transferring Non-Servable Knowledge to Servable Models" in the blog post we wrote with Google AI (https://ai.googleblog.com/2019/03/harnessing-organizational-knowledge-for.html) or the corresponding paper.

**Comment by cyruszhang** [comment]
thanks for the explanation @bhancock8 !
