### ISSUE TITLE
Entity Recognition (Unary candidate class) throws IndexError in LSTM

### ISSUE THREAD

**Issue by DeneshPohar** [HazyResearch/snorkel#1100]
I'm trying to use snorkel to train an entity classifier for n-grams, very similar to #599.  I'm hitting the same `IndexError` _originally posted by @arturomp in https://github.com/HazyResearch/snorkel/issues/599#issuecomment-360920559_.  However, I didn't see a clear workaround in that issue.

**My setup code**
```python
from snorkel.models import candidate_subclass
return candidate_subclass("Entity", args=["term"], values=LABELS)
```

And I've largely followed the flow outlined in the [Categorical Classes tutorial](https://github.com/HazyResearch/snorkel/blob/master/tutorials/advanced/Categorical_Classes.ipynb).

```python
lstm = LSTM(cardinality=classifier.cardinality, n_threads=None)
lstm.train(train_cands, train_marginals, **train_kwargs)
```

**Actual Behavior**
This ends up throwing in https://github.com/HazyResearch/snorkel/blob/1d16ae6a6dba0f51c60d5a4179576d2d89134160/snorkel/learning/pytorch/rnn/rnn_base.py#L93:
```python
args = [
    (candidate[0].get_word_start(), candidate[0].get_word_end(), 1),
    (candidate[1].get_word_start(), candidate[1].get_word_end(), 2)
]
```

Which clearly seems hard-coded to expect two candidates.

**Workaround**
I've attempted to work around this by deriving my own class from `LSTM` and overriding the ``

```python
args = [
    (part.get_word_start(), part.get_word_end(), i + 1)
    for i, part in enumerate(candidate)
]
```

Is this the right workaround?  Should this be the implementation in `RNNBase`?

**Comment by SElghazolyMM** [comment]
Any solutions for this problem? I am having a similar issue and the solution proposed here led to a new error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-ba10fe9375ba> in <module>
     12 
     13 lstm = LSTM(cardinality=Annot.cardinality, n_threads=None)
---> 14 lstm.train(train_cands, train_marginals, None, **train_kwargs)

~/anaconda3/envs/snorkel/lib/python3.6/site-packages/snorkel/learning/pytorch/rnn/rnn_base.py in train(self, X_train, Y_train, X_dev, **kwargs)
    113 
    114         # Note we pass word_dict through here so it gets saved...
--> 115         super(RNNBase, self).train(X_train, Y_train, X_dev=X_dev,
    116             word_dict=self.word_dict, **kwargs)
    117 

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by bhancock8** [comment]
@DeneshPohar the workaround you suggest seems reasonable. There are lots of great 3rd party implementations of LSTMs, and in the new v0.9 of Snorkel coming out soon, we'll give lots of examples of how to integrate with these types of libraries.

**Comment by bhancock8** [comment]
@SElghazolyMM The error you posted is one we often see in notebooks when you've modified the code behind a class that you're importing but you haven't restarted the notebook. Give that a try, and if you still have an issue, post again as a new issue.
