### ISSUE TITLE
about the massive multi-task learning (MMTL) module

### ISSUE THREAD

**Issue by michael-wzhu** [HazyResearch/snorkel#1103]
Hello, I am really interested in your work on the GLUE benchmark. And i found in your blog that, and i quote, "The Massive Multi-Task Learning (MMTL) module of Snorkel MeTaL that we used will be released as a part of v0.5 in April".  So i wonder whether this module is ready, and whether there is some documentation for it?

**Comment by bhancock8** [comment]
Thanks for your interest! v0.5 has been released, along with a tutorial showing basic usage of the MMTL package. We plan to release another tutorial down the road demonstrating how to use BERT applied to the GLUE datasets. The MMTL package itself is complete and in the master branch.
