### ISSUE TITLE
sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) 

### ISSUE THREAD

**Issue by Rock-L** [HazyResearch/snorkel#1105]
hi : i got this error and very confused me. what should i do to fix it
`sqlalchemy.exc.IntegrityError: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry '13952' for key 'kw_id'") [SQL: u'INSERT INTO kw_ner (id, kw_id, kw_cid) VALUES (%s, %s, %s)'] [parameters: ((9070L, 13952, None), (9071L, 13950, None), (9072L, 13951, None), (9073L, 13953, None), (9074L, 13917, None), (9075L, 13933, None), (9076L, 13934, None), (9077L, 13935, None)  ... displaying 10 of 11 total bound parameter sets ...  (9079L, 13932, None), (9080L, 13931, None))] (Background on this error at: http://sqlalche.me/e/gkpj)`

**Comment by vincentschen** [comment]
Looks like the database is corrupted—could you try deleting the `.db` and running this again? Feel free to re-open if the issue persists.

**Comment by hashamMunir** [comment]
I am facing the same issue, this entry does not even exist in database but error is continuesly appearing can anyone help. Exactly the same issue
ERROR - (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'd3465cda-1a3e-43df-8eab-3b0dccf19427-fos' for key 'PRIMARY'")

**Comment by vincentschen** [comment]
Hi @hashamMunir — thanks for reaching out here. Can you share more steps about how you reproduced this error? 

I also suspect that you're using an earlier version of `snorkel < 0.9` highlighting a relation extraction example (which has been transferred to the [`snorkel-extraction`](https://github.com/snorkel-team/snorkel-extraction) repository). It might be fruitful to give that repo a try!
