### ISSUE TITLE
Sudden issue with 'spaCy'

### ISSUE THREAD

**Issue by SElghazolyMM** [HazyResearch/snorkel#1112]
After using this environment without issue, I got the prompt to pip install spacy. I uninstalled and reinstalled spacy version 1.9.0, and now I am getting the error ``ImportError: cannot import name 'tags_to_entities'`` and
``ValueError: cymem.cymem.Pool has the wrong size, try recompiling``

I am using OS 10.14.4 and python version 3.6.7

**Comment by rockonrob** [comment]
This is an issue with `spaCy` versioning and not snorkel. Check your version of `murmurhash`, `cymem`, and `thinc` and that they are aligned with the `spaCy` requirements for `1.9.0`. Also see: https://github.com/explosion/spaCy/issues/2852#issuecomment-464485703. A full reinstall of your environment may fix the issue.

**Comment by vincentschen** [comment]
> This is an issue with `spaCy` versioning and not snorkel. Check your version of `murmurhash`, `cymem`, and `thinc` and that they are aligned with the `spaCy` requirements for `1.9.0`. Also see: [explosion/spaCy#2852 (comment)](https://github.com/explosion/spaCy/issues/2852#issuecomment-464485703). A full reinstall of your environment may fix the issue.

Did this resolve the issue? Feel free re-open if not.
