### ISSUE TITLE
Adding continuous variables into matrix

### ISSUE THREAD

**Issue by dmracek** [HazyResearch/snorkel#1115]
Is it possible to integrate values in my labeling matrix that are more continuous in nature? In addition to the abstain, positive, or negative approach, I'm wondering if Snorkel can integrate for example a standardized value of -3 to 3. I saw somewhere else a generative model that is more along the lines of a regression approach is in the works, but I wasn't sure if more continuous values in the LF matrix would or would not work.

**Comment by bhancock8** [comment]
Hi @dmracek, that's a great question. The current label model does only support categorical values. The more we hear requests for "regression-like" LFs (which support continuous outputs), the higher up it goes on our queue of things to work on next. There's a major version update coming up at the end of this month that I think you'll really like; we're improving a LOT of things in the current code base. I don't think regression LFs will be a part of that, but it's good to know there's a demand for that feature. Thanks for posting!

**Comment by dmracek** [comment]
Thank you @bhancock8! I suppose I could do a median split (i.e., 0-50 percentile = negative; 51-100 percentile = positive) or even split the -3 to 3 z scores into increments of 1 such that -3 to -2 would receive a positive for a LF next a -2 to -1 would receive a positive and so forth. How do you think Snorkel would handle this approach? Seems like issues related to sparsity could become a challenge?

**Comment by bhancock8** [comment]
Yeah, binning a continuous label space into a discrete one can work. You're right though, depending on how much unlabeled data you have, you'll need to consider how many examples you'll have in each of those bins by the time you label. And you do lose a little information in that ideally you could bake in somehow that -2 is closer to -3 than it is to +3 (which you would get with a regression-like'  
 setup. So you can give the binning a try and see if it works. And then when we're able to add support for regression-like LFs (probably still at least a couple months out, unfortunately), would be interesting to see how that compares.

**Comment by vmando** [comment]
+1 I have a similar use case where the LFs are mix of continuous and discrete functions. Has this functionality been implemented?
