### ISSUE TITLE
Generative_Model.train() - Labeling People in Images

### ISSUE THREAD

**Issue by Mainara** [HazyResearch/snorkel#1117]
I'm trying to use Snorkel to label people in images, for that I'm using HOG and Haar Cascade as heuristics, but I'm facing some difficulty to understand how the Generative Model will do the predictions in images, because the model is being trained only with the output of the heuristics. Is there any way to add the images in the step of training? If so, how can I do it?

**Comment by paroma** [comment]
The generative model takes as input the output of the heuristics as you said, and assigns _training labels_ to the images. The raw images and associated training labels can then be used to train an end machine learning model, like a CNN. 

More details on the Snorkel pipeline here: http://hazyresearch.github.io/snorkel/blog/weak_supervision.html

Closing this for now, feel free to reopen with other questions!
