### ISSUE TITLE
Best result on Spouse dataset

### ISSUE THREAD

**Issue by ghaccount** [HazyResearch/snorkel#1127]
I am following the tutorial in workshop folder .../tutorials/workshop/Workshop_4_Discriminative_Model_Training.ipynb

The score I get from the trained LSTM model don't look good.
Prec: 0.088, Recall: 0.661, F1 Score: 0.156

I understand it was quick exercise with small dataset. What is the best score people have achieved on this data problem?

I am trying to learn about the effectiveness of this approach. And best score achieved would be the indicator for that.

Thanks.

More detailed result
tp, fp, tn, fn = lstm.error_analysis(session, test_cands, L_gold_test)

Scores (Un-adjusted)
Pos. class accuracy: 0.661
Neg. class accuracy: 0.401
Precision            0.0882
Recall               0.661
F1                   0.156

TP: 144 | FP: 1488 | TN: 995 | FN: 74

**Comment by jason-fries** [comment]
Hi @ghaccount,
In the [Snorkel paper](https://arxiv.org/abs/1711.10160), we reported scores of:

_Precision_: **47.8**  
_Recall_: **62.5** 
 _F1_: **54.2**

For the workshop we ran as part of the user study in the paper (the source of this tutorial), the best participant scored:

_Precision_: **38.4**  
_Recall_: **66.5** 
 _F1_: **48.7**

Hope this helps!
