### ISSUE TITLE
[Question] Designing LFs

### ISSUE THREAD

**Issue by lazysjb** [HazyResearch/snorkel#1129]
I had a question on designing LFs (currently using Snorkel to do sentiment analysis on text).
For the same kind of labeling function, I think I have multiple ways of writing it.
For example, if I have a heuristic based on positive words ('good', 'awesome') and negative words ('bad', 'terrible', etc.) then I can write 2 LFs - 1 that labels positive labels (and abstain if word not found) and 1 that labels negative labels based on negative vocabs. Alternatively, I can have 1 LF that has 'if conditions' that labels positive if word in positive vocab, negative if word found in negative vocab, and abstain otherwise. Currently, I am going with the former one, since I feel that having too many logic (if's for instance) is not favorable and I should let the generative model figure out the accuracies of the 'granular' level of LFs (but this is totally a guess).
What would be the best way to label, and how can I think about which labeling functions are better in a general sense? 

Thank you!

**Comment by lazysjb** [comment]
@ajratner it would great if you could help on this

**Comment by bhancock8** [comment]
HI @lazysjb, great question! There are a few tradeoffs here. On the one hand, LFs need to have high enough coverage and conflict with other LFs for us to learn accuracies for them beyond whatever our prior is for all LFs. On the other hand, if you have two signals with different inherent accuracies combined into one LF, the model can only learn one accuracy for that LF so you limit how much that LF can be effectively downweighted or upweighted. The caveat to this is that in our latest formulation of data programming (currently implemented in the Snorkel MeTaL repo and coming by the end of the month in a big Snorkel v0.9 release), we learn a class-conditional accuracy for each LF, so it does in fact learn a different accuracy for the positive and negative classes in your binary problem. So in that case, it shouldn't make much difference whether it's one or two LFs. Unfortunately there isn't a single golden number to shoot for in terms of accuracy or coverage for any given LF, but hopefully this is helpful as you work on your own problem!
