### ISSUE TITLE
Phrase-leve fuzzy dictionary matcher

### ISSUE THREAD

**Issue by edoughty** [HazyResearch/snorkel#113]
Add new dictionary matcher that includes edit distance and minimum threshold in order to generate candidates. This could only apply to phrases of length 3 or greater.  For example, "cervical spinal cord" does not match anatomy dictionary but "spinal cord" does. We'd want to include both as candidates. 

Similarly for bacteria, we want to extend species names in order to find specific strains. We also may not know how many words after the dictionary match to include (multiple words for strain or multiple strains).
 "E. coli" is in dictionary but "E. coli K-12" may not be. Also, we may miss "E. coli strain K-12".

**Comment by ajratner** [comment]
Initial idea:
- Word-level edit distance
- Only apply to phrases w/ e.g. >= 3 words
