### ISSUE TITLE
Unable to Run Intro_Tutorial_1 after installation as spacy is not installed

### ISSUE THREAD

**Issue by agarwmae** [HazyResearch/snorkel#1187]
I am trying to compile the Intro_Tutorial_1 after installing Snorkel. After running the code "from snorkel.parser import TSVDocPreprocessor", I am getting an error of spacy not present.

Following is the error message

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/snorkel/parser/spacy_parser.py in <module>
     13 try:
---> 14     import spacy
     15     from spacy.cli import download

ModuleNotFoundError: No module named 'spacy'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-2-dd528794d4e5> in <module>
----> 1 from snorkel.parser import TSVDocPreprocessor
      2 
      3 doc_preprocessor = TSVDocPreprocessor('data/articles.tsv', max_docs=n_docs)

/anaconda3/lib/python3.7/site-packages/snorkel/parser/__init__.py in <module>
      2 
      3 from snorkel.parser.corenlp import *
----> 4 from snorkel.parser.corpus_parser import *
      5 from snorkel.parser.doc_preprocessors import *
      6 from snorkel.parser.parser import *

/anaconda3/lib/python3.7/site-packages/snorkel/parser/corpus_parser.py in <module>
      5 from builtins import *
      6 
----> 7 from snorkel.parser.spacy_parser import Spacy
      8 from snorkel.models import Candidate, Context, Sentence
      9 from snorkel.udf import UDF, UDFRunner

/anaconda3/lib/python3.7/site-packages/snorkel/parser/spacy_parser.py in <module>
     20         spacy_version = 1
     21 except:
---> 22     raise Exception("spaCy not installed. Use `pip install spacy`.")
     23 
     24 

Exception: spaCy not installed. Use `pip install spacy`.

**Comment by bhancock8** [comment]
Can you confirm that your Jupyter notebook is using the conda kernel corresponding to your snorkel environment as opposed to a generic Python3 kernel, for example?

**Comment by agarwmae** [comment]
Yes my Jupyter notebook is using conda kernel corresponding to the snorkel environment not the Python3 kernel

**Comment by chaturv3di** [comment]
`pip install spacy==1.9.0`

**Comment by agarwmae** [comment]
Thank you all. My problem got solved when i used the correct version of spacy. Thank you @chaturv3di  for helping the issue.
