### ISSUE TITLE
`save_marginals` on images tutorial

### ISSUE THREAD

**Issue by oribarel** [HazyResearch/snorkel#1211]
Hi,

I'm was going over the images tutorial (https://github.com/HazyResearch/snorkel/blob/master/tutorials/images/Images_Tutorial.ipynb), and trying to save the marginals using:
```
from snorkel.annotations import save_marginals
%time save_marginals(session, L_train, train_marginals)
```

but I'm getting an error saying that `id` does not exist.
```
AttributeError                            Traceback (most recent call last)
<timed eval> in <module>

~/anaconda3/envs/snorkel/lib/python3.6/site-packages/snorkel/annotations.py in save_marginals(session, X, marginals, training)
    514     insert_vals = []
    515     for i, k, p in marginal_tuples:
--> 516         cid = X.get_candidate(session, i).id if anno_matrix else X[i].id
    517         insert_vals.append({
    518             'candidate_id': cid,

~/anaconda3/envs/snorkel/lib/python3.6/site-packages/scipy/sparse/base.py in __getattr__(self, attr)
    687             return self.getnnz()
    688         else:
--> 689             raise AttributeError(attr + " not found")
    690 
    691     def transpose(self, axes=None, copy=False):

AttributeError: id not found
```
What is the standard way to save and load the marginals in this case?

**Comment by paroma** [comment]
We are planning an upgrade to the codebase soon which should resolve this issue. 

In the meantime, you can use `np.save('marginals.npy', train_marginals)` in the image tutorial to save the NumPy array directly. The image tutorial is not set up to use a database like the Spouse tutorial, which is causing the error with the save command.
