### ISSUE TITLE
stable version of snorkel

### ISSUE THREAD

**Issue by adbeda** [HazyResearch/snorkel#1229]
I would like to bring **snorkel** to the conda users community and it would be great to learn if there will be a release file anytime soon for the latest/stable master repo. The gunzipped tarball of the most recent version (i.e., 0.7-beta) is 150 commits behind and a year older.  

any thoughts?

**Comment by ajratner** [comment]
Hey @adbeda thanks so much for the offer of help here!!  We are actually in the middle of a big refactor effort, aiming to release in early August- so that will definitely be the best version, and coming soon!

**Comment by adbeda** [comment]
@ajratner sounds good. I will have the workflow ready and test stuffs, in the meantime.

**Comment by ajratner** [comment]
Great, thank you!!

**Comment by adbeda** [comment]
@ajratner I just want to give you a quick update on whats going on.

So, I've been testing [a recipe](https://github.com/conda-forge/staged-recipes/pull/8768) for snorkel and its dependency on pytorch which is not in conda-forge is making snorkel difficult to build. The [environment.yml](https://github.com/HazyResearch/snorkel/blob/c17c38ac8ddf569484cf9c0bde4702b2f2622033/environment.yml#L2-L4) file pulls pytorch from its own channel, which makes snorkel incompatible with the conda-forge channel. 

There is a [pytorch package](https://github.com/conda-forge/pytorch-cpu-feedstock) in conda-forge but its only built for cpu.  I think they're working on building a pytorch for both cpu. On the bright side, there are some other contributers are working on bringing a pytorch for both gpu and cpu although it may take a while. Hopefully, we'll get some update by the time your team release the latest version in August.

**Comment by adbeda** [comment]
I think my concern got fixed with the help from @hmaarrfk.

**Comment by hmaarrfk** [comment]
I would still remove all equality symbols from your recipe

**Comment by adbeda** [comment]
don't you think the package may don't work if the version of the pinned dependencies is different?

**Comment by hmaarrfk** [comment]
You should listen to that talk by msarahan. He discusses why the environment you have is different than a package you ship. 

If you want exact reproducibility for your users, you will always need to provide an environment file. Packages are meant to evolve, and by pinning, you will have to create a new package every time a small version is bumped. Numpy is actually very stable. And you can likely set the minimum version quite far back. No need for an exact version all the time.

**Comment by adbeda** [comment]
cool

**Comment by ajratner** [comment]
Looping in @bhancock8 and @henryre to coordinate current efforts on our end!

**Comment by adbeda** [comment]
@ajratner we should be able to install snorkel from conda-forge soon with 
[`conda install -c conda-forge snorkel`](https://anaconda.org/conda-forge/snorkel)
looking forward to updating it to the upcoming version.

**Comment by henryre** [comment]
Hi @adbeda, just caught up with this thread. We're redoing our release process when v0.9 comes out, which means regular package updates to pypi and conda. Since the redesign is significant, we'll be moving the current form of Snorkel to a new repo, so it would be great to have a build like the one you made there! I'll let you know when we're getting ready for that move.
