### ISSUE TITLE
if snorkel support soft-labelling function

### ISSUE THREAD

**Issue by futianfan** [HazyResearch/snorkel#1231]
Hi,

I notice that all these labelling function in snorkel can only produce discrete label, but if i have a binary classification problem where labels are soft, i.e., 0.8 mean it is positive w.p. 0.8 and negative w.p. 0.2. can snorkel support this kind of soft-labels?

Thanks very much in advance!

**Comment by vincentschen** [comment]
Good question—this is on our roadmap related to regression LFs.

Closing and tracking on https://github.com/HazyResearch/snorkel/issues/1072

**Comment by prpankajsingh** [comment]
@futianfan You can refer the work done by IIT Bombay ([Link](https://www.cse.iitb.ac.in/~ganesh/papers/aaai2020.pdf)
This work extends the snorkel framework and output a continuous score (in-stead of a hard label) that noisily correlates with labels
