### ISSUE TITLE
Multiple matcher concatenation to make new matcher

### ISSUE THREAD

**Issue by edoughty** [HazyResearch/snorkel#126]
Create a composite matcher that includes two or more matchers concatenated for a single phrase. For example in bacteria, we may want to extract "Yersinia pestis K-12". We would match the first part of the phrase ("Yersinia pestis") with a dictionary matcher and we would match the second part of the phrase ("K-12") with a regex. The concat matcher composed of dictionary match and regex match would return Yersinia pestis K-12 if the phrase contains a dictionary match followed by the regex match. 

This would be great for domain-specific candidates that can construct more sophisticated matchers using the base matcher functions (dictionary matcher, regex matcher, etc). My example is only for bacteria but I'm such experts in other domains would have similar example patterns that can be constructed using a composite/concatenated matcher.

**Comment by ajratner** [comment]
Fixed in upcoming PR; syntax is:
```python
Concat(DictionaryMatch(d=bacteria_names), RegexMatch(rgx=r'K-\d+'))
```
