### ISSUE TITLE
Candidate Extraction: Estimate size of extracted candidate set

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#130]
A user has a tradeoff between increasing the recall of their candidate extraction routine (and thus the UB recall of their system), and minimizing latency of running their application.  Informally we've often just phrased this as "don't hardcode stuff- maximize recall- but also don't blow up the system with e.g. all pairs of words"; we should be slightly more helpful / precise than this...

To start, at least, we should build a **simple method for getting an _estimate_ of the extracted set size**, which ideally even outputs a rough estimate of how long this implies various stages of their application pipeline might take as well.

Commonly, it seems like the user in fact has a discrete series of relaxations available to them (e.g. what edit distance to consider for fuzzy phrase matching, various levels of dictionary expansion, etc.) so we could even imagine providing a plot of estimated extracted set size in these cases

**Comment by syadlowsky** [comment]
Can we estimate this size based on a subset?

**Comment by ajratner** [comment]
@syadlowsky Yup I think this would be the clear thing to try first
