### ISSUE TITLE
Snorkel’s documentation

### ISSUE THREAD

**Issue by Mainara** [HazyResearch/snorkel#1322]
Hi, I'm trying to investigate some functions of DependencySelector in the [Snorkel's documentation](https://snorkel.readthedocs.io/en/master/), but the site is not working properly. I already opened this documentation in the past and was working fine. Can someone confirm if this is a general problem? If so, can you fix this?

**Comment by henryre** [comment]
Hi @Mainara , thanks for reporting! There appears to be some issue with SQLAlchemy in the doc build for master (https://readthedocs.org/projects/snorkel/builds/9364921/). Latest is still working for me, so let me know if you can access that: https://snorkel.readthedocs.io/en/latest/index.html. We're in the middle of a large redesign with more maintainable doc builds, so this issue should be resolved when that's on the master branch.

**Comment by Mainara** [comment]
Thank @henryre for answer me. I tested the second link and it's working for me too.
