### ISSUE TITLE
Probabilistic labeling functions?

### ISSUE THREAD

**Issue by kenlkehl** [HazyResearch/snorkel#1334]
Just started experimenting with Snorkel for some clinical/medical NLP tasks. Naive question here. Apologies if I'm missing this somewhere.
In drafting labeling functions, it 'feels' like I'm sacrificing a little domain knowledge when I make each function yield a categorical label (eg positive/negative, or abstain) rather than a probability distribution over the labels (eg probability of positive vs negative, within each function).
Wondering whether the ability to have probabilistic labeling functions would be useful or is possible?
(Perhaps this overlaps somewhat with the questions around regression problems,  which I see may be coming).

**Comment by paroma** [comment]
Thanks or your question! As you mentioned, this is on our roadmap related to regression LFs.

Closing and tracking on #1072
