### ISSUE TITLE
Longest candidate match not respected within Union matcher

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#141]
Discussed during the hackathon -- several people noticed issues matching longest phrase candidates. For example, in "Curative treatment of **stomach cancer** requires gastric resection" "cancer" should never be a candidate, because "stomach cancer" is in the dictionary. However it frequently is a candidate.  This happens with a lot of cancer mentions. It might just be an already-fixed issue with the Union matcher?

**Comment by ajratner** [comment]
Just reiterating from our discussion- let's get this put in to the tests (at test/Matcher.py)?  Then I can see if the new candidate extractor refactor (finished soon) fixes this!!

**Comment by henryre** [comment]
You or me?

**Comment by ajratner** [comment]
This should get resolved when I get around to finishing the CandidateExtractor refactor.  I also talked to @jason-fries about putting this into the tests, so I can confirm it's fixed at that point

**Comment by ajratner** [comment]
This still needs to be fixed in the new PR

**Comment by ajratner** [comment]
Nvm, this is fixed in the new PR- just set `longest_match_only=True` in the `Union` operator
