### ISSUE TITLE
Lack of Sentence.__dict__ in python 2.7.5 causes error in Entities object creation.

### ISSUE THREAD

**Issue by jeffwdoak** [HazyResearch/snorkel#142]
The Sentence class created in ddlite_parser.py is created using collections.namedtuple (lines 17-19). In python2.7.5 namedtuple does not have a `__dict__` attribute, but instead uses the `_asdict()` method to return an OrderedDict of field names : values. This lack of a `__dict__` method in namedtuple--created classes creates an error when an Entity object is created from a list of sentences. The simple solution for me is to switch to any other version of python besides 2.7.5.

I encountered this error in input 8 of the GeneTaggerExample_Extraction.ipynb notebook:

    E = Entities(sents, CE)
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-8-22e3ed523cb3> in <module>()
    ----> 1 E = Entities(sents, CE)
    
    /home/QUESTEK/jdoak/src/ddlite/ddlite.pyc in __init__(self, content, matcher)
        289         warnings.warn("matcher is not a CandidateExtractor subclass")
        290       self.e = matcher
    --> 291     super(Entities, self).__init__(content)
        292 
        293   def __getitem__(self, i):
    
    /home/QUESTEK/jdoak/src/ddlite/ddlite.pyc in __init__(self, C)
        126         raise ValueError("No pickled candidates at {}".format(C))
        127     else:
    --> 128       self._candidates = list(self._extract_candidates(C))
        129     self.feats = None
        130     self.feat_index = {}
    
    /home/QUESTEK/jdoak/src/ddlite/ddlite.pyc in _extract_candidates(self, sents)
        147   def _extract_candidates(self, sents):
        148     for sent in sents:
    --> 149       for cand in self._apply(sent):
        150         yield cand
        151 
    
    /home/QUESTEK/jdoak/src/ddlite/ddlite.pyc in _apply(self, sent)
        295 
        296   def _apply(self, sent):
    --> 297     xt = corenlp_to_xmltree(sent)
        298     for e_idxs, e_label in self.e.apply(sent):
        299       yield entity_internal(e_idxs, e_label, sent, xt)
    
    /home/QUESTEK/jdoak/src/ddlite/tree_structs.pyc in corenlp_to_xmltree(s, prune_root)
         70       s = s.__dict__ if hasattr(s, '__dict__') else dict(s)
         71     except:
    ---> 72       raise ValueError("Cannot convert input object to dict")
         73 
         74   # Use the dep_parents array as a guide: ensure it is present and a list of ints
    
    ValueError: Cannot convert input object to dict

I have pinned down the problem to a change in namedtuples that is only present in python2.7.5. Below are simple tests to see if a namedtuple--created class instance has a `__dict__` attribute.

Testing this out, here is the successful `__dict__` call in python 2.7.4:

    Python 2.7.4 (default, Apr 27 2016, 11:06:48)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from collections import namedtuple
    >>> Test = namedtuple('Test', 'one two')
    >>> test = Test(3, 4)
    >>> test.__dict__
    OrderedDict([('one', 3), ('two', 4)])
    >>> test._asdict()
    OrderedDict([('one', 3), ('two', 4)])

Here is the failed `__dict__` call in python 2.7.5:

    Python 2.7.5 (default, Apr 27 2016, 12:07:31)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from collections import namedtuple
    >>> Test = namedtuple('Test', 'one two')
    >>> test = Test(3, 4)
    >>> test.__dict__
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'Test' object has no attribute '__dict__'
    >>> test._asdict()
    OrderedDict([('one', 3), ('two', 4)])

Finally, here is a successful `__dict__` call in python 2.7.6:

    Python 2.7.6 (default, Apr 27 2016, 13:22:49)
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from collections import namedtuple
    >>> Test = namedtuple('Test', 'one two')
    >>> test = Test(3, 4)
    >>> test.__dict__
    OrderedDict([('one', 3), ('two', 4)])
    >>> test._asdict()
    OrderedDict([('one', 3), ('two', 4)])

It seems that namedtuple was changed in 2.7.5, but then reverted in 2.7.6 and later versions of python2.

**Comment by ajratner** [comment]
Hey Jeff,

Thanks for pointing this out & providing the detail, we really appreciate this!  We'll try to clean this up sometime soon, although in general we will support python 2.7.n where n > 5 (I'm using 2.7.10 for reference)

Thanks,
Alex
