### ISSUE TITLE
Warn user & handle LF class imbalance

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#145]
We can also try automatic up/down-sampling (will put as issue), but should have a nice way of signaling this type of imbalance to the user!

**Comment by ajratner** [comment]
We have more helpers for this now, but technically still open... we should add this in

**Comment by chaturv3di** [comment]
Just wondering if a default labelling function would counter the class imbalance. For instance, I have written about a dozen LFs: 6 each for my +ve and -ve classes. The way I've written them results in a heavy imbalance toward the negative class. 

@ajratner, would you think that adding an LF that, by default, labels every candidate as a positive instance would work? My assumption is that enabling learning of dependencies would rescue the situation by learning that, e.g. the default positive-LF is "corrected" by the negative LFs whenever they fire.
