### ISSUE TITLE
Duplicate candidates in Union matcher

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#151]
Tested on the latest version of ddlite. The Union matcher will create duplicate, identical entity instances (i.e., matching doc_id,sent_id, spans) in the resulting candidate set. This doesn't happen if you use a single matcher class. 

See example candidate pickle files in the shared dropbox folder
`ddlite-datasets/candidates/jason/diseases/v4`

**Comment by ajratner** [comment]
Did you try the new stuff in
https://github.com/HazyResearch/ddlite/tree/candidate-extractor-2

**Comment by jason-fries** [comment]
I didn't -- will check after dinner.

**Comment by ajratner** [comment]
Cool lmk if it resolves it!

**Comment by henryre** [comment]
@ajratner What still needs to get done before a PR (besides KBP...)?

**Comment by ajratner** [comment]
You mean for the candidate-extractor-2 branch?  Plan was to finish:

1. Fuzzy phrase matcher
2. Tests (e.g. to see if this issue is resolved, incorporate it into tests...)

**Comment by jason-fries** [comment]
Just tested -- using the candidate-extractor-2 branch still results in duplicate entities with the Union matcher.

**Comment by ajratner** [comment]
Hmm, I'll check this out, thanks!

**Comment by ajratner** [comment]
This is fixed by the new PR
