### ISSUE TITLE
Labeling Function Correlation/Similarity Measure

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#153]
Would it be possible to have some pairwise measure of how similar a labeling function output is? For example, a heatmap matrix of labeling function correlation coefficients, cosine similarity, etc. It would be nice to have some assessment if two labeling functions are basically equivalent 

![visualize-correlation-matrix-using-correlogram-correlogram-methods1](https://cloud.githubusercontent.com/assets/348682/15196986/e914a11a-1783-11e6-9c57-bbbdc937d55d.png)

**Comment by ajratner** [comment]
I think this is great!!!!  Esp. as we experiment with beginning to put in
user-defined dependencies

**Comment by henryre** [comment]
Yeah very good idea. Going look so much worse in matplotlib!!

**Comment by ajratner** [comment]
Tacking onto this: we may want to have a separate **warning** that comes up during e.g. learning if too high a correlation noticed between any feature and LF, esp. in joint approach

**Comment by henryre** [comment]
This is a tougher one, because the ideal action here would be to remove the feature. But this kind of breaks the "hide-the-features" thing we have going. Could implement a simple feature removal method and prompt the user to issue the exact command?

**Comment by ajratner** [comment]
Taken care of by structure learning!
