### ISSUE TITLE
CoreNLP adding non-breaking characters?

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#180]
This is a weird issue. When parsing a large collection of PubMed abstracts, for some reason the string (or similar) `http://dx.doi.org/10.7554/eLife.00802.001.` is parsed and appended with a sequence of non-breaking characters, i.e., `http://dx.doi.org/10.7554/eLife.00802.001.\x00\x00\x00\x00`

This causes `corenlp_to_xmltree_sub` to bail out due to some lxml issues
`ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters`

See the attached text for an example error case. This happens in a couple places (usually with URLs). The characters aren't in the original string. Any ideas?

[malformed.txt](https://github.com/HazyResearch/ddlite/files/268968/malformed.txt)

Here's the parsed sentence object:

`Sentence(words=[u'DOI', u':', u'http://dx.doi.org/10.7554/eLife.00802.001.\x00\x00\x00\x00'], lemmas=[u'DOI', u':', u'http://dx.doi.org/10.7554/elife.00802.001.\x00\x00\x00\x00'], poses=[u'NNP', u':', u'NN'], dep_parents=[0, 1, 1], dep_labels=[u'ROOT', u'punct', u'dep'], sent_id=8, doc_id='23878724', text=u'DOI:http://dx.doi.org/10.7554/eLife.00802.001.', token_idxs=[1081, 1084, 1085])`

(The hackfix is to change SentenceParser to strip these characters out, but I don't know why they are there to begin with.)

**Comment by alekdimi** [comment]
I'm having the same problem when analyzing the pubmed abstracts dataset. I couldn't pinpoint the exact character that caused it, but I "fixed" it by converting everything to ASCII (Unicode did not help). 

Has there been a real fix to this?

**Comment by jason-fries** [comment]
There isn't an official fix pushed, but basically the options are similar to what you did:
1) Figure a way to turn off non-breaking character output in CoreNLP 
2) Add a function to SentenceParser that removes non-breaking characters (either converting to ASCII like you did, re.sub ASCII control chars etc. 

2 is probably the easiest -- we can push a fix for the upcoming PR.

**Comment by ajratner** [comment]
Any updates here?  Should we just add change (2) above into `SentenceParser`?

**Comment by ajratner** [comment]
@jason-fries Is this issue closed with your latest PR?

**Comment by jason-fries** [comment]
Yes -- this is fixed now.
