### ISSUE TITLE
Integrate GIFs somehow

### ISSUE THREAD

**Issue by henryre** [HazyResearch/snorkel#199]
Maybe hip and trendy sound clips too with popular artists like Hannah Montana or Andrianas Grand

**Comment by jason-fries** [comment]
![giphy](https://cloud.githubusercontent.com/assets/348682/15559950/67b4ed0a-229b-11e6-89ce-8e159f2af833.gif)

**Comment by ajratner** [comment]
I think we all have enough GIFs in our diet now, thanks to the indispensable mission critical business 2.0 paradigm shift that is Slack... closing
