### ISSUE TITLE
Issue with Mindtagger on Firefox

### ISSUE THREAD

**Issue by ThomasPalomares** [HazyResearch/snorkel#202]
Hey, 

Mindtagger seems not to be displayed on Firefox. When running DDL.open_mindtagger() in the notebook, there is just a big white space in the out box.
Not a big issue (since it seems to work well in chrome), but may be useful to recommend somewhere in the notebook to use chrome (or at least not to use firefox).

(I can't add it but this deserves the fyi label)

**Comment by henryre** [comment]
I've actually had success with Firefox, but we'll definitely note this. Thanks!
