### ISSUE TITLE
Sentence and Document-level Candidate Helper Functions

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#212]
Perhaps redundant with Issue#196, but some labeling functions need access to global candidate information, e.g., sentences with several candidates separated by commas are probably similar (correct) entities in a list. Currently there aren't any helper functions to extract views.

**Comment by ajratner** [comment]
We need to address this carefully so as not to create massive slow-ups, but I agree we should address this in a nicer way for the user

**Comment by ajratner** [comment]
Closed in v0.5.0
