### ISSUE TITLE
Documentation with pydoc

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#219]
[pydoc](https://docs.python.org/2/library/pydoc.html)

**Comment by ajratner** [comment]
Using [pdoc](https://github.com/BurntSushi/pdoc); for now, just outputting html files to a `docs/` folder

**Comment by henryre** [comment]
@ajratner Have you pushed anything with this yet? Assuming its deprecating the markdown tables in README?

**Comment by ajratner** [comment]
Yup- and will be in my upcoming PR.  Although nothing much to add, just a script to run pdoc :)

**Comment by henryre** [comment]
Well nothing except good doc strings...

Parameter passing to learning with `**kwargs` will be trickier to handle. Is there an MO?
