### ISSUE TITLE
Make ddlite launch script!

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#222]
Bundle everything like checking submodules, pulling, refreshing docs, etc.

**However:** We want to have a "two-tier approach" (thanks @netj !), so that even if one of these setup tasks fails, the jupyter notebook still opens!

**Comment by netj** [comment]
A build script in DeepDive may help the submodule checking part: https://github.com/HazyResearch/deepdive/blob/master/Makefile#L122-L149

The setup instructions in README can become the lower level script for launching jupyter in the virtualenv, and with more scripts taking care of submodules, doc generation, a single higher-level launch script can just call them.

**Comment by ajratner** [comment]
Will add a check right now to make sure that submodules (e.g. treedlib) are not _empty_, otherwise will have a separate pull script (see #325)
