### ISSUE TITLE
Noun phrases

### ISSUE THREAD

**Issue by thodrek** [HazyResearch/snorkel#224]
Instead of using tools other than CoreNLP we can simply extend the parser to store the "parse" field from the json object  returned by CoreNLP. This correspond to the parse tree which already contains internal nodes annotated as Noun Phrases (NP).

**Comment by phosseini** [comment]
It does contain the NP annotations, but how can we actually get a list-- like a list of actual strings-- of all of these NPs in a document which do not have overlap with each other?
