### ISSUE TITLE
Make suite of tests based on CDR / tutorial

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#226]
@jason-fries can you help me add spacey parser tests once I have the basics set up here?  I'll push some stuff with the new candidate extractor release which will cover from XML -> candidates...

Either way: my thinking here is that if the tests are closely aligned with---and include---the new CDR tutorial, then they are more likely to (a) be relevant and (b) actually be maintained

**Comment by jason-fries** [comment]
Definitely. I think we should run both parsers on the ChemDNER corpus and see what bombs out, then use those documents as part of our tests. The frequent unicode character use in chemical names does a nice job of finding parser issues :)

**Comment by ajratner** [comment]
Yup agreed.  We can both work on this and then merge efforts, or otherwise I'll just continue with the first pass up through candidate extraction- should be done soon- and then let you know
