### ISSUE TITLE
Create uniform SentenceParser interface

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#227]
I.e. with the new parser classes there should ideally be some base class that defines the interface?

**Comment by jason-fries** [comment]
Yeah -- other than the parse method, do we need any other functionality exposed that isn't parser specific? Multiprocessing? Maybe turn on whitespace tokenization?
```
class Parser(object):
  def parse(self, doc, doc_id=None, doc_name=None):
     raise NotImplementedError
```

**Comment by ajratner** [comment]
Unfortunately my current branch has diverged a bit... but I am using a `parse_docs` method too, which takes in a list of `Document` objects.  This is instead of having the `DocParser` call a `SentenceParser` internally, for a bit cleaner separation

Other than that, yeah I guess some way to pass in configs?  @thodrek @netj any other thoughts on generic interfaces to the parser?

**Comment by jason-fries** [comment]
That seems reasonable. I've been doing something similar, using a `Corpus` object with a `DocParser` object to generate `Document`s and applying a `Parser` and `TextTransform` in the corpus object.  The `TextTransform` is useful for hacking in various things (e.g., removing special anonymizing tokens in MIMIC-III text data), so maybe that should be a separate addition.
