### ISSUE TITLE
Merge overlapping candidate spans in DictionaryMatcher

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#253]
Similar to `longest_match`flag, can we have a `merge_contiguous_match` flag to deal with (1) overlapping matches and (2) contiguous matches. This happens pretty frequently.

**Overlapping Example**
left shoulder
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shoulder blade
`left shoulder blade`

**Contiguous Example**
hypothalamic 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;abnormalities
`hypothalamic abnormalities`

**Comment by ajratner** [comment]
@jason-fries The first example seems good to cover, although slightly non-trivial to add... the latter technically is covered with Concat, but agreed as well
