### ISSUE TITLE
Only return different index entities in candidate relations when calling Relations() with the same matcher

### ISSUE THREAD

**Issue by edoughty** [HazyResearch/snorkel#257]
When you call Relations for same entity relationships (e.g., chemical-chemical relation), relations are returned for entities with themselves given the same matcher for each entity. The Relations class should not create a candidate relation of same index entities. 

For example, I created a single matcher for chemicals and called Relations with the matcher for both entity 1 and entity 2. Relations(sents, matcher, matcher) returns candidates of entities with themselves as they're both found by the same matcher.

**Comment by alekdimi** [comment]
I believe an easy and quick fix is to just add the following _if check_ in _snorkel.py_ to _'_apply'_ of class _Relation_:
```
        if e1_idxs != e2_idxs :
          yield relation_internal(e1_idxs, e2_idxs, e1_label, e2_label, sent, xt)
```
so that it will not yield duplicates.

**Comment by ajratner** [comment]
Perfect!

Sorry for the delay on getting to this... as you probably know from talking
with Steve, we're on the verge of refactoring all of this code, so this
slipped... in the meantime, feel free to submit this fix as a PR?

**Comment by alekdimi** [comment]
After further thought, I'm not sure it's the best solution. If it's only `!=` we still get symmetric pairs, e.g. for the following sentence:

> Deletion analysis revealed that stimulation of endocytosis of TRPV5 involves amino acids outside the kinase domain of WNK4. 

 we get two candidates: (_WNK4_, _TRPV5_) and (_TRPV5_, _WNK4_), which I think is undesirable. So the code should probably read:
`if e1_idxs < e2_idxs :`
This also has the added benefit of e1 always occurring before e2 in a sentence.

However, if the two relations are different, this will remove around half the pairs, which we don't want removed. Is there any way we can check if the two relations are looking for the same thing?

**Comment by ajratner** [comment]
This has to be an application-specific decision, about whether the relation
is a symmetric one; so it should be a flag.  But good point that in the
case of symmetric relations we might want this flexibility
