### ISSUE TITLE
Use sphinx autodoc to set up basic documentation

### ISSUE THREAD

**Issue by pmlandwehr** [HazyResearch/snorkel#259]
Not super important, but might be tidier than having all class notes in the README, and the code seems to have a good number of docstrings. [(Ref.)](http://www.sphinx-doc.org/en/stable/ext/autodoc.html)

**Comment by ajratner** [comment]
+1

Have pdoc in the new PR that I will push soon can try that or switch to sphinx autodoc

**Comment by ajratner** [comment]
Subsumed by #329
