### ISSUE TITLE
In Concat operator make one optional, link words?

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#262]
In general: more flexibility

@ThomasPalomares @tberardini any examples?

**Comment by tberardini** [comment]
The mutant plants described in the Arabidopsis literature may have one or more genes mutated in them. In the text, the names of all the mutated genes are given and the phenotype is only relevant if linked to all three (or n) genes at the same time, meaning that we want all the relevant genes called as a unit for the candidate extraction.

Example sentences:

(1) gene names separated by '/'

" At the fully developed ovule stage the _ **spl/nzz** _ mutant phenotype resembles that of _ ashh2 _ , but in contrast to _ ashh2 , **spl/nzz** _ is characterized by the absence of a MMC at an early stage of ovule development , thus preventing embryo sac formation . "

**spl/nzz** = two genes, spl and nzz

phenotype = absence of MMC at early stage of ovule development
and
phenotype = embryo sac formation prevented

(2) Gene names concatenated, no space in between them.

 To investigate the level of membrane lipid peroxidation , the same leaves were analyzed for MDA content ( malondialdehyde , a byproduct of lipid peroxidation ) : _ **chy1chy2lut2lut5** _ and _ **chy1chy2lut5** _ leaves showed higher accumulation of MDA upon stress treatment ( +120 % and +45 % , respectively ) , thus a far higher level of lipid peroxidation with respect to wild-type and _ lut2 _ plants ( +25 % ) ; _ **chy1chy2lut2lut5** _ plants showed a far higher photosensitivity in high-light than _ **chy1chy2lut5** _ ( Figure ) ; the latter was the xanthophyll mutant with the highest light sensitivity described so far [ ] . 

**chy1chy2lut2lut5** = four genes, chy1, chy2, lut2, lut5
**chy1chy2lut5** = three genes, chy1, chy2, lut5

(3) Gene names concatenated, space in between gene names.

 The presence of these residues may explain the small amount of GBSS detected on the _ ptst _ starch granules ( ) , which increased when starch was always present ( as seen in the _ **ptst sex4** _ double mutant ; . 

 **ptst sex4**  = two genes, ptst and sex4

**Comment by ajratner** [comment]
Thanks for this!! Updates soon

**Comment by ThomasPalomares** [comment]
Thanks Tanya !

Just two precisions regarding the phenotypes in the first example: the dictionaries contain the parts 'absence of MMC', 'early stage' and 'ovule development' but we want to catch the whole 'the absence of a MMC at an early stage of ovule development' as one candidate.

Same for the second phenotype, the dictionary contains 'embryo sac formation' and we have a quality dictionary with the word 'prevent' or 'prevented' in it and we want to capture 'preventing embryo sac formation'
