### ISSUE TITLE
Add lemmatization pre-processing to DictionaryMatcher

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#263]
@ThomasPalomares @tberardini

**Comment by tberardini** [comment]
Encountered:

dictionary word: reduced ([PATO:0001997](http://amigo.geneontology.org/amigo/term/PATO:0001997)), see synonyms

word/s in the papers: reduction, reduces

dictionary word: increased [PATO:0000470](http://amigo.geneontology.org/amigo/term/PATO:0000470), see synonyms

word/s in the papers: increase, increases

**Comment by ajratner** [comment]
Added Porter stemming in merged PR!
