### ISSUE TITLE
Tutorial issue: references DocParser, uses HTMLParser

### ISSUE THREAD

**Issue by pmlandwehr** [HazyResearch/snorkel#268]
In [GeneTaggerExample_Extraction.ipynb,](https://github.com/HazyResearch/ddlite/blob/master/examples/GeneTaggerExample_Extraction.ipynb) the notes refer to using ddlite's `DocParser` to read HTML. However, the instantiated class is built on `ddlite.ddlite_parser.HTMLReader`, which doesn't share any provenance with `DocParser`.

**Comment by ajratner** [comment]
This tutorial is being phased out; thanks for pointing out though!
