### ISSUE TITLE
Tutorial issue: DDL.launch_mindtagger doesn't start mindtagger

### ISSUE THREAD

**Issue by pmlandwehr** [HazyResearch/snorkel#270]
- or perhaps it does, but not in the notebook?

1. I'm in [GeneTaggerExample_Learning.ipynb](https://github.com/HazyResearch/ddlite/blob/master/examples/GeneTaggerExample_Learning.ipynb)
2. I run box 5, `DDL.open_mindtagger(num_sample=100, width='100%', height=1200)`
3. I get the "Making Sure MindTagger is installed. Hang on!" message, and a warning from my mac that a service is starting on a port. I also get a huge white box. Then.... nothing. Seems like I should be seeing an instance of MindTagger.

Checked the code, and did a manual install of mindtagger to `local/`. Ran again, and still nothing.

**Comment by mcmclean** [comment]
When I first ran this I had the same issue, but apparently it opens up at http://localhost:8222.  But my problem is that once I tag stuff, I don't see a clear way to end the Mindtagger session.  Despite closing the tab, returning to the notebook shows that the process is still running and I can't continue the tutorial (firefox, OS X el capitan).

**Comment by ajratner** [comment]
We'll be handling this issue very soon with a simpler labeling interface

In the meantime any luck here? Any further details so we can reproduce?

**Comment by mcmclean** [comment]
Okay, gotcha.  Will give it another try tomorrow from a fresh start with Chrome.  Had the same issue on Safari.  I also attempted to use a separate ddlite app and encountered the same issue with Mindtagger there.

**Comment by ajratner** [comment]
We're transitioning to a more native `Viewer` object, which is now in the new tutorial at `tutorial/CDR_tutorial.ipynb`- hopefully this gets us around a lot of these issues!
