### ISSUE TITLE
Support joint learn multiple relations/mentions

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/snorkel#276]

**Comment by ajratner** [comment]
@SenWu could you elaborate a bit? Thanks!

**Comment by SenWu** [comment]
For gene-pheno relation extraction task, we have three objects to learn: gene mention, phenotype mention, and gene-pheno relation. In DD, we can learn them simultaneously. Can we support it in DDLite?

**Comment by ajratner** [comment]
I agree this would be good, but I don't think we plan to support this for a little bit,; let's re-open post-DD integration!
