### ISSUE TITLE
Character-level Candidate Definitions

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#277]
A mention should be defined across a character span within the candidate. By default, this would include all characters and be equivalent to the current implementation. But this would also let us define a sub-token matcher object. For instance, many compound modifiers ("cancer-free", "aspirin-induced", etc.) are treated as single tokens by parsers. Other matchers are incorrectly tokenized ("ATM/AT"). Rather than changing tokenization, we should be able to define a regex matcher that operates on tokens but only the matched span is treated as as the candidate That way we can pull out "cancer", "aspirin", etc. with minimal hassle.

**Comment by ajratner** [comment]
Already being implemented this way :). Will be done this week

**Comment by jason-fries** [comment]
Awesome! This change alone will boost candidate recall in the chemical mention task rather nicely.

**Comment by ajratner** [comment]
Awesome. I'm sure we'll need to discuss and tune but should be simple
change, great!
