### ISSUE TITLE
CandidateExtractor Regular Expression error

### ISSUE THREAD

**Issue by cmorbaab** [HazyResearch/snorkel#279]
When I extract candidates using regular expressions the RegexNgramMatch returns added elements that do not match the regular expression I inputed. I tested my regular expression on Rubular and it worked and returned what i wanted, however when I test that regular expression in ddlite it returns different things. I tested this regular expression '?<=[\s\W])[0-9]+[-,\.]?[0-9]+\s' and ddlite starts returning entities with numbers and words and parentheses. For example it returns [u'100', u'ng/ml']. Is there an error or is there a reason for this?

**Comment by ajratner** [comment]
Hey @cmorbaab thanks for pointing this out!  Could you perhaps point me to / send some examples where there is confusing output (and the expected / "correct" output for each one as well)?  We're actually in the middle of a small refactor of this part of the code so perhaps this will fix it- either way I'll look into it.  If you send me some examples I can also integrate them in the tests

**Comment by cmorbaab** [comment]
I'm testing a regular expression('(?<=[\s\W])[0-9]+[-,\.]?[0-9]+\s(?=[a-zA-Z,\.])') to return possible candidates about the levels of a biomarker found in a article. I tested it on this paper:

[AGR2_blood_biomarker.txt](https://github.com/HazyResearch/ddlite/files/344191/AGR2_blood_biomarker.txt)

and the correct results are:

[regex_test_results.docx](https://github.com/HazyResearch/ddlite/files/344204/regex_test_results.docx)

**Comment by ajratner** [comment]
The file `regex_test_results.docx` are the actual text spans that should be matched?  I think what's going on here is that the matcher is matching even if part of the n-gram matches the regex; unclear semantics for this operator...  This will be fixed in the new matcher code in a day or two, sorry!

**Comment by cmorbaab** [comment]
Has this issue been fixed?

**Comment by ajratner** [comment]
We're hopefully minutes away from merging new PR... Which should fix this I hope!

**Comment by ajratner** [comment]
This should be fixed now- reopen if not
