### ISSUE TITLE
Examples could be redesigned to build better library intuition

### ISSUE THREAD

**Issue by DrPinkACN** [HazyResearch/snorkel#298]
Importing a library like this: `from ddlite import *`, makes it a little difficult to quickly build a working knowledge for the available functions/classes in a library. I would recommend that future examples import ddlite and/or the needed objects by name, e.g., `import ddlite` or `from ddlite import function1`.

**Comment by ajratner** [comment]
Thanks for this feedback! We agree- the new tutorial that we're working on
(Part I of which is in a current PR being merged now) does this
consistently, and we'll make sure to stick to it!

**Comment by ajratner** [comment]
Done in new tutorial!
