### ISSUE TITLE
Change "sent_id" to "sent_index" to avoid conflict with "id" attribute

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#303]
In ddlite_parser.py, the concept of sentence 'id' seems to be overloaded with two attributes. Rename "sent_id" to "sent_index" for clarity's sake?

**Comment by ajratner** [comment]
I actually disagree with this- the sentence/context id could be something other than an index (e.g. some path through a hierarchical structure).  Can discuss later but closing for now
