### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by sangha123** [HazyResearch/snorkel#305]
In ddlite.py

# ddlite matchers                                                                                                
from ddlite_matchers import *

instead of 
# ddlite matchers                                                                                                
from ddlite_matcher import *

**Comment by ajratner** [comment]
Thanks for noting this!  Will be fixed w PR we are merging now

**Comment by sangha123** [comment]
Hi Alex,

I checked and the example ipython notebooks were also not running.  I think
something to do with HTMLReader.

Sanghamitra.

**Comment by ajratner** [comment]
Which ones? As far as I'm aware the notebooks on master are running, as
multiple people have been running them

**Comment by sangha123** [comment]
They are running on the master (atleast for ddlite).  I cloned the
candidate extractor 2 branch today.  I got error in reading the pubmed
document.  Specifically I got "HTMLREADER not defined".  I am guessing
HTMLReader code did not get included in this version.

Sanghamitra.

**Comment by ajratner** [comment]
Ah I see, my bad- the only notebook that I know works for the *candidate extraction* stage with this new branch is `tutorial/CDR_Tutorial.ipynb`- perhaps check that one out?  We'll have everything merged soon too, sorry for the delays!

**Comment by sangha123** [comment]
The matcher code has also changed.  Thus RegexNgramMatch.  RegexFilterAll
are not working.

One of the reasons for looking into branch is to write phrase extractors. I
am not sure how to do this for a general data set of sentences with no
training data

I looked into the tutorials folder.  The example there uses a dictionary
matcher.

Sanghamitra.

**Comment by ajratner** [comment]
It also uses a RegexMatcher, a Union matcher and a Concat matcher!  As I
said though we're also still in-progress on this branch / PR!

**Comment by sangha123** [comment]
Is there any part of the code that deals with phrases. I could copy them &
use them along with old ddlite.

Thanks for your help
Sanghamitra.

**Comment by ajratner** [comment]
I'm a little unclear about what you're trying to do, could you perhaps give
me an illustrative example?

**Comment by sangha123** [comment]
Yes.

Example: The boy ate the apple.

Nouns: boy, apple

I want to extract

the boy ate
the boy
Boy ate
Boy

Ate the apple
the apple
apple

As my possible candidates.

I.e I want n-grams around nouns.  Writing Python code for this is simple.
I am not sure how to include it in ddlite framework.

I am also open to using linguistic definition of phrase.

Sangha

**Comment by jason-fries** [comment]
This is a very simple matcher that finds noun phrases and strips off certain POS tags.  It works with the non-PR version Snorkel nee DDLite
```
class NounPhraseMatcher(CandidateExtractor):
    """ Match Noun Phrases, L/R stripped of DTs and CCs"""
    def init(self):
        self.pattern = re.compile("(NN[SP]*|JJ[S]*|DT|CC)") 
        self.label         = self.opts['label']
        self.match_attrib  = self.opts.get('match_attrib', 'words')
        self.ignore_case   = self.opts.get('ignore_case', True)
        self.longest_match = self.opts.get('longest_match', True) 
       
    def _apply(self, s, idxs=None):
        noun_phrases = []
        np = []
        for i,tag in enumerate(s.poses):
            if self.pattern.search(tag):
                np += [(i,tag)]
            elif np:
                noun_phrases += [np]
                np = []
         
        for np in noun_phrases:   
            while np and re.search("(CC|[PW]*DT)",np[0][1]):
                np.pop(0)      
            while np and re.search("(CC|[PW]*DT)",np[-1][1]):
                np.pop()   
            if not np or re.search("JJ[RS]*",np[0][1]):
                continue
            idxs,poses = zip(*np)
            yield list(idxs), 'x'
```

**Comment by ajratner** [comment]
Also if you are *just* looking for 'any ngram with a noun in it', there are
ways to do it in the new PR (with union, Concat, and regexmatch), as well
as a very quick new child class of RegexMatch that can be made to handle
this case (call this RegexMatchAny)

This should be very quick to implement. Otherwise we'll get to it at some
point soon

**Comment by sangha123** [comment]
Hi Jason,

Should I just add this to the ddlite_matcher code, so it has access to the
rest of the code.

Thanks,
--Sangha.

On Tue, Jul 12, 2016 at 11:38 PM, Jason Alan Fries <notifications@github.com

**Comment by jason-fries** [comment]
I'd just import the relevant ddlite dependences (e.g., CandidateExtractor) and define the class in the same notebook or python script you are doing candidate extraction.

This is largely a hack that will be replaced soon by the PR so I would do the minimum amount of work to integrate the code.

**Comment by sangha123** [comment]
Thanks.

--SD.

**Comment by sangha123** [comment]
For this phrase extractor,

I used this format,
noun_regex = NounPhraseMatcher(label='Nouns')
and
noun_regex = NounPhraseMatcher(label='Nouns',
regex_pattern=r'[a-zA-Z]+',ignore_case=True,  match_attrib='words')

and

E = Entities(docs,noun_regex)


gives,

.....

Cannot convert input object to dict


I think I need to give more/different information to the
NounPhraseExtractor, I am not sure what it would be.


--Sanghamitra.

**Comment by sangha123** [comment]
Hi Jason,

I got it work with regular text (from a novel), there maybe some aspect of
my data that is giving this output.

Thanks for your help,

--Sanghamitra.

**Comment by ajratner** [comment]
Perhaps let's chat about this at hackathon on Monday?  otherwise rename issue & re-open; for now closing
