### ISSUE TITLE
SlotFill template-based Matcher

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#311]
Can we implement a Matcher class that acccepts slot-filled strings akin to Python's  string format function?

For example:
`TemplateMatcher("{0} and/or {0} cancer", anatomy_dictionary)`
which could match strings like `breast and/or ovarian cancer`

Ideally this could operate on character level spans as well to match 
`TemplateMatcher("{0}/{0}", disease_abbrv, char_level=True)`
which could match strings like `ALD/AMN`

**Comment by ajratner** [comment]
I'm going to build this ASAP (post grand merge!)

@jason-fries when you get a chance could you point me to a few examples so I can test as I build?
