### ISSUE TITLE
Change method/attribute references of "sentences" to "contexts"

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#312]
In ddlite_parser.py, I propose that references to "sentences" in the Corpus object be changed to "contexts" so that they apply to both tables and sentences.

iter_sentences -> iter_contexts
get_sentences -> get_contexts
_sentences_by_id -> _contexts_by_id

Similarly, changing "sent_id" to "context_id" so that fields can have the same names for both Sentences and Tables.

**Comment by ajratner** [comment]
I agree- can make the change, then subclass a SentencesCorpus object that
implements the current accessor methods for convenience

Fine by me to go ahead and make the change if you want!

**Comment by bhancock8** [comment]
Sweet. Perhaps I'll wait until after the weekend when "the big one" PR has come through, then I'll make the change on Monday.

**Comment by ajratner** [comment]
Makes sense, than can submit as its own PR
