### ISSUE TITLE
Showing the entire document in Viewer

### ISSUE THREAD

**Issue by sangha123** [HazyResearch/snorkel#313]
For tagging candidates, in order to understand the entire context it is better if the human tagger is able to see the entire document. example, to tag one entry in a sentence in pubmed it would be good to be able to see the entire abstract. Also if all of the tagging for one abstract is done together it makes more sense, hence showing the entire document together in mindtagger for tagging all of the candidates is also useful.

**Comment by ajratner** [comment]
Can do this with BRAT now!
