### ISSUE TITLE
Put documentation up on ReadTheDocs!

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#329]
Yes, this gives us another badge 👍 

See [the getting started tutorial](http://read-the-docs.readthedocs.io/en/latest/getting_started.html)

With the new PR, we have documentation with `pdoc`; to upload to read the docs, we'll need to switch to sphinx as in #259

**Comment by ajratner** [comment]
Also pre-generate documentation

**Comment by henryre** [comment]
Swag
