### ISSUE TITLE
Incorrect behavior for matching two of the same dictionary in Relations

### ISSUE THREAD

**Issue by henryre** [HazyResearch/snorkel#33]
See example in ddlite.py

Also, don't pair the same token to itself for a relation

**Comment by alisoncallahan** [comment]
+1 for cases where two dictionaries may have a valid overlap in their entries.

**Comment by ajratner** [comment]
Just to recap / clarify here, the goal is to just make sure that we don't create relation candidates that refer to the same e.g. token span, correct?

**Comment by henryre** [comment]
That's the bigger issue. Sentence tagging also fails in some cases where it isn't the same token.

**Comment by ajratner** [comment]
#257
