### ISSUE TITLE
Replace namedtuple contexts (e.g., Sentences) with proper classes

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#331]
I'm aware of four different "context" objects that we use now in different places (Documents, Sentences, Tables, Cells), and there are some attributes they all share (e.g., id), and some that multiple share (Sentences and Cells both have all the NLP tags). I think converting these to proper objects that all inherit from a Context object (and maybe a LingualContext object for Sentences and Cells) could give us a less hacky-feeling structure with more guarantees on what attributes passed objects will have, and encourage more generic development (i.e., less favoring of "sentences" everywhere compared to other contexts). Also, it's a step toward the SQLAlchemy classes that we'll want them to be eventually. Thoughts?

@ajratner -- I'd be happy to do the refactor, I just assigned you because I expect you'll have an opinion on this.

**Comment by stephenbach** [comment]
Subsumed by #322 .

**Comment by ajratner** [comment]
@bhancock8 I agree with this, as we discussed, this sounds great!

And @stephenbach agree as well

This was an awesome display of the wonder that is issues 👍
