### ISSUE TITLE
coreNLP server can't be started in new master

### ISSUE THREAD

**Issue by alekdimi** [HazyResearch/snorkel#334]
When I initialize SentenseParser() it is unable to start the server, specifically the following two lines:
```
  loc = os.path.join(os.environ['SNORKELHOME'], 'parser')
  cmd = ['java -Xmx4g -cp "%s/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer --port %d > /dev/null' % (loc, self.port)]
```
output the error "_Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer_".

I am, however, able to manually start the server if I go _SNORKELHOME/parser_ and type 
`java -Xmx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer `
in the terminal.

After checking out the new merged master I re-ran _install-parser.sh_ just in case, but it didn't help.

Best,
Alek

**Comment by stephenbach** [comment]
Confirming on my environment, OSX 10.10.5.

**Comment by ajratner** [comment]
Is your SNORKELHOME env variable properly set as an absolute path (i.e.
from running run.sh or set_env.sh)?

Could you print the loc variable?

Just suggesting these sanity checks to start... Steve, does "confirming"
mean you get the same error?

**Comment by stephenbach** [comment]
os.environ['SNORKELHOME'] is set to the correct absolute path.

Sorry if that was vague, confirming that I get the same error.

**Comment by ajratner** [comment]
We're passing the ParserTest so this is weird...

**Comment by stephenbach** [comment]
This is specifically happening on GeneTaggerExample_Extraction and a derived notebook that is similar, in case that narrows it down.

**Comment by alekdimi** [comment]
It was the path after all, good sanity check, my snorkelhome was set to
_/afs/cs.stanford.edu/u/alek/miner-extract/snorkel_ whereas it should be 
_/afs/cs.stanford.edu/u/alek/miner-extract/snorkel_

**Comment by stephenbach** [comment]
And for posterity, reinstalling the parser fixed it, so false alarm.
