### ISSUE TITLE
DictionaryMatch KeyError: 'd'

### ISSUE THREAD

**Issue by varun-tandon** [HazyResearch/snorkel#335]
I am attempting to create a DictionaryMatch object like so 
`marker_dm = DictionaryMatch(label='MarkerName', dictionary=markerDatabase, ignore_case=False)`
but get the following error:

/home/varun/Documents/Marker-Reader/BiomarkerMatcher.py in getBiomarkerMatcher()
      8         markerDatabase = pickle.load(f)
      9 
---> 10     marker_dm = DictionaryMatch(label='MarkerName', dictionary=markerDatabase, ignore_case=False)
     11     marker_regex = RegexMatch(label='marker', regex_pattern=r'(^|(?<=\s))[A-Za-z][A-Z1-6-]{2,}', ignore_case=False,match_attrib='words')
     12 

/home/varun/Documents/Marker-Reader/snorkel/snorkel/matchers.py in __init__(self, *children, **opts)
     18         self.opts               = opts
     19         self.longest_match_only = self.opts.get('longest_match_only', False)
---> 20         self.init()
     21 
     22     def init(self):

/home/varun/Documents/Marker-Reader/snorkel/snorkel/matchers.py in init(self)
     77     def init(self):
     78         self.ignore_case = self.opts.get('ignore_case', True)
---> 79         self.d           = frozenset(w.lower() if self.ignore_case else w for w in self.opts['d'])
     80         self.attrib      = self.opts.get('attrib', WORDS)
     81 

KeyError: 'd'

This error was not present prior to some of the more recent changes to snorkel

**Comment by ajratner** [comment]
In the new version `d` is the argument for the dictionary; we'll make sure to throw a more descriptive error here

**Comment by varun-tandon** [comment]
Thanks, as a heads up, rgx has a similar error message

**Comment by ajratner** [comment]
#337
