### ISSUE TITLE
Integrate NUMBA sampler?

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#340]
* http://numba.pydata.org/numba-doc/0.8/interface_c.html
* https://gist.github.com/gdementen/5661550

**Comment by chrismre** [comment]
I don't think this is necessarily a snorkel issue... I want bryan and CDS to prototype this for their Gibbs stuff... if it works, then we port over here.

**Comment by ajratner** [comment]
Ok closing for now
