### ISSUE TITLE
getting multiple tokens in candidate extractor.

### ISSUE THREAD

**Issue by sangha123** [HazyResearch/snorkel#350]
Is it possible to get multiple tokens for candidate extractor. i.e I have a regex expression (say 3 capital letters), I get a match : ABC then my candidates should be : (ABC,one token, ABC,one token,two token), i.e I want a bigram and trigram (It could be in both direction) . Is there a way to do this in snorkel?

**Comment by ajratner** [comment]
You should be able to just extend your regex eg- r'ABC.*'. Let me know if
this gives you any problems!

**Comment by sangha123** [comment]
It would be great if I could find a way to extract tokens outside regex
(once a pattern is matched) . The reason being I always tend to miss
something with regex. Its kind of hard to write something that covers all
possible combinations, especially when we do not know the data that well.

--Sangha.

**Comment by ajratner** [comment]
You can use the `Concat` operator to look for the concatenation of two matcher patterns; for example, if I wanted to match the pattern r'ABC' followed by some sequence of nouns, I could write:
```python
matcher = Concat(
    RegexMatchSpan(rgx=r'ABC', attrib='words'),  # Selects all *entire spans* that match r'ABC'
    RegexMatchEach(rgx=r'NN.*', attrib='poses'),  # Selects spans where *each* POS tag is a noun
)
```

**Comment by sangha123** [comment]
So concat is for getting consecutive matches,

What if I have multiple independent regex-es in need to be combined.
ii.e I am unable to write one regex that gets everything, so I write two
(or more) expressions.

Should I write two different candidates and combine them, if so how should
they be combined?

--Sangha.

**Comment by ajratner** [comment]
Could you provide an example perhaps to help me understand the question?

**Comment by sangha123** [comment]
I have one string which is

ABC 1234.  and this gets captured by one Regex

Another.

ssl2.0VPN that gets covered by another Regex.

And I am unable to combine them.  I can write two candidate extractors.  I
think like I should be able to append the candidate extractors.  I am not
sure if append is defined for the candidate extractor class.

Sanghamitra.

**Comment by ajratner** [comment]
You can just write one regex that ORs the two patterns together?

You could also write two different matchers and combine them with `Union`, but that seems unnecessary

If this is mostly a question about regular expressions then I will close this issue in a bit, let me know

**Comment by sangha123** [comment]
The main question was about can I get extra tokens outside the Regex.

I think the answer is to do some combination of  Regexex es

Yes you can close the issue.

Sanghamitra.

**Comment by ajratner** [comment]
Okay reopen if something else comes up!  We can also talk at hackathon :)  We'll try to gradually add more to the tutorials so that these things can become clearer, thanks for your patience!
