### ISSUE TITLE
Replace Ngram and Document meta columns with mutable dict types 

### ISSUE THREAD

**Issue by stephenbach** [HazyResearch/snorkel#351]
Necessary to ensure that changes to metadata mark an object as dirty.

See http://docs.sqlalchemy.org/en/latest/orm/extensions/mutable.html

Should also support smart serializing/deserializing of any lxml objects that must be converted to strings before serializing, to address workaround introduced in 2ee0395.

**Comment by ajratner** [comment]
Closed in v0.5.0
