### ISSUE TITLE
Clean up querying with primary keys for polymorphic types

### ISSUE THREAD

**Issue by stephenbach** [HazyResearch/snorkel#353]
corpus = session.query(Corpus).filter(Corpus.name == 'CDR Corpus').one()

==>

corpus = session.query(Corpus).get('CDR Corpus')

**Comment by stephenbach** [comment]
Closing this without fixing. Explicitly not supported by SQLAlchemy. From http://docs.sqlalchemy.org/en/latest/orm/inheritance.html:

> Joined inheritance primary keys
> 
> One natural effect of the joined table inheritance configuration is that the identity of any mapped object can be determined entirely from the base table. This has obvious advantages, so SQLAlchemy always considers the primary key columns of a joined inheritance class to be those of the base table only. In other words, the id columns of both the engineer and manager tables are not used to locate Engineer or Manager objects - only the value in employee.id is considered. engineer.id and manager.id are still of course critical to the proper operation of the pattern overall as they are used to locate the joined row, once the parent row has been determined within a statement.

We can work around this by adding convenience queries to `snorkel/queries.py`.

**Comment by ajratner** [comment]
Adding convenience queries sounds like the way to go!
