### ISSUE TITLE
LF utility functions from Candidate class -> separate util file

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#359]
@jason-fries I don't know what else needs to be done here, but basically, we just want to save everything that's currently needed for LF writing in existing code?

Then we can also add more here

**Comment by ajratner** [comment]
Putting them back into the Candidate class

**Comment by bhancock8** [comment]
What prompted the decision to keep LF utilities attached to candidates instead of a separate util file?

**Comment by ajratner** [comment]
Very open to discussion here :), but:
- When @SenWu pulled out the helper functions we were actually using, they were actually quite minimal
- Additionally, as these functions are often Context-specific, organizing them under different classes seems like a nice benefit
