### ISSUE TITLE
Unify Matching / Learning Function "Context" Access

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#364]
Both matchers and labeling functions should have the same access to Entity/Relation contexts (e.g, sentences) provided by a wrapper class.  In LFs we routinely look at context to disambiguate mentions, for example in doc:

PMID: 1733838 
`the localisation of the gene for Norrie disease (NDP).`
we need two extract mentions 
`264:278    Norrie disease`
`280:283    NDP`

`Norrie disease` is in our dictionary but `NDP` is not. We can label `NDP` easily in a LF if we use `Sentence` object access and the parentheses and co-occurrence with a known disease as evidence, but Matchers currently don't use global/local information to reason about a specific subsequence candidate.

We should just unify around a set of helper utilities that are tooled to whatever level of "context" a user requires for their extraction task.

**Comment by ajratner** [comment]
Agreed; two notes just to expand on this:

- Currently (pre-ORM) the candidates have access to their contexts (e.g. `Ngram.sentence`, `Ngram.sentence.xmltree`); and post-ORM, these will also be accessible, in a cleaner way
- If we want an LF to know that it occurs after something we *have decided* is a disease mention, then obviously this would have to occur at the model level, but we can certainly have a nice way for it to be aware that it's after a *candidate* disease mention... and this might be easier to do post ORM?

Anyway, am I still correct in thinking that if we just take existing helper functions from the old candidates class / notebooks, and put them in a module, then we'll be making good progress on this issue?  Are we close to a v1 on this front?

If anyone else has similar "helper functions" that they've written to help with writing LFs, it would be great to incorporate them here too!

**Comment by ajratner** [comment]
Closed in v0.5.0
