### ISSUE TITLE
CoreNLP char_offsets/token mappings do not match raw document text

### ISSUE THREAD

**Issue by varun-tandon** [HazyResearch/snorkel#368]
I am having an issue with the DictionaryMatch where it matches incorrect words. 

I construct the DictionaryMatch object like so: 
`DiseaseMatch = DictionaryMatch( d = ["CRPC"], ignore_case= True)`
And I create Entities like so:
` ngrams = Ngrams(n_max=1) `
 ` E = Entities(sentences, CandidateExtractor(ngrams, DiseaseMatch))`

When I print out these Entities I notice the DictionaryMatch object **extracts words that are not part of the Dictionary,** in this case, it extracts the word "with", despite "CRPC" being the only word in the dictionary:
```
<Entity: [u'with'][9]>
<Entity: [u'CRPC'][30]>
<Entity: [u'CRPC'][39]>
<Entity: [u'CRPC'][13]>
<Entity: [u'CRPC'][7]>
<Entity: [u'CRPC'][10]>
<Entity: [u'CRPC'][15]>
<Entity: [u'CRPC'][25]>
```
The sentence it is extracting "with" from is:

```
 We conclude that plasma AGR2 may be used along with CGA , and other serum markers , to help define NECRPC .
```

Here are some other examples:

```
Dictionary= ["CSPC"]

Incorrect Entities: 
<Entity: [u'2500'][18]>

Sentence: Blood was collected from 44 patients with metastatic prostate cancer separated
as: castration sensitive prostate cancer (CSPC, n ¼ 5); castration resistant prostate cancer
(CRPC, n ¼ 36); and neuroendocrine-predominate CRPC defined by PSA  1 ng/ml in the
presence of wide-spread metastatic disease (NE-CRPC, n ¼ 3).
```
```
Dictionary=["PSA"]

Incorrect Entities: 
1. <Entity: [u'was'][19]>
2. <Entity: [u'and'][13]>

Sentences: 
1.A third pattern with stable AGR2 levels despite decreasing PSA (Fig. 3D , F , and G) was also observed . 
2. In the five subjects with CSPC, the median (range) age and serum PSA were 58.1 (51.1–66.6) years and 428.6 (2.4–7,606) ng/ml, respectively.
```
```
Dictionary=["CGA"]

Incorrect Entities:
<Entity: [u'the'][24]>

Sentence:
The median (range) of CGA levels in normal subjects was 70 (22–714) ng/ml, which is consistent with the assay’s normal value of <100 ng/ml.
```
I noticed in all of these examples the word in the dictionary is present in the sentence, and the incorrect word is the same length as the dictionary word.

Please let me know if you need any other information.

Thanks

**Comment by ajratner** [comment]
Hi @varun-tandon,

Thanks for this detailed issue!  I tried to reproduce in a simple way and couldn't.  Two quick questions before I proceed further:

1. You are working off master branch, correct?
2. Do your documents have unique ids?

Thanks,
Alex

**Comment by varun-tandon** [comment]
Hi Alex,

I am working off the most recent version of the master branch, and I am testing with only one document, so I assume that there is only one id. 

For reference, [here](https://www.researchgate.net/profile/Parag_Mallick/publication/230714614_Anterior_gradient_2_(AGR2)_Blood-based_biomarker_elevated_in_metastatic_prostate_cancer_associated_with_the_neuroendocrine_phenotype/links/0fcfd50d8f8c7a1ab6000000.pdf) is the paper we are using.

Thanks,
Varun

**Comment by ajratner** [comment]
Hey Varun,

I'm not able to reproduce the error from the single sentences you've copied above.  Perhaps you could show me the code you're using / send me the full parsed doc?

**Comment by varun-tandon** [comment]
Hi Alex,

Here is the code I am using:

```
from snorkel.candidates import Ngrams
from snorkel.matchers import *
from snorkel.parser import *

from snorkel.snorkel import Entities

test_match = DictionaryMatch(d=["CRPC"], ignore_case = True)
ngrams = Ngrams(n_max=1)
sent_parser = SentenceParser()
doc_parser = TextDocParser("AGR2_blood_biomarker.txt")
corpus = Corpus(doc_parser, sent_parser)
sentences = corpus.get_contexts()

print Entities(sentences, CandidateExtractor(ngrams, test_match))
```

This is the text file we pass in: 
[AGR2_blood_biomarker.txt](https://github.com/HazyResearch/snorkel/files/397631/AGR2_blood_biomarker.txt)

And these are the pickled parsed sentences
[AGR2_blood_biomarker_sentences.txt](https://github.com/HazyResearch/snorkel/files/397635/AGR2_blood_biomarker_sentences.txt)

**Comment by ajratner** [comment]
Hi @varun-tandon ,

I took another brief look just now: there is something weird going on with how this document is being parsed by the CoreNLP parser (an external package we use)... I will have to continue looking a bit later; for now renaming the issue

Will hopefully update you soon and again thanks for pointing this out in such detail!!

Thanks,
Alex

**Comment by ajratner** [comment]
Ok, so took another quick look: I'm not quite sure what's going on still, but am pretty sure it's something with CoreNLP, not on our side.

In the example you pointed me too, the issue is with one sentence; we pass in:
`u'Sample location on the\n96-well plate were randomized in order to eliminate\nplate bias.'`

And the "original text" that CoreNLP returns (and that crucially its character offsets refer to) is:
`u'Sample location on the\n96-well plate were ra\x00\x00\x00\x00\x00\x00\x00\x00ndomized in order to eliminate\nplate bias.'`

Either way, we now default to following CoreNLP's output, and throw a warning if it diverges from the document text.  This means **everything should now work fine for you**; however, if the above CoreNLP issue occurs, as it does in this case, the character offsets we reference (and which we index candidates by) will not map nicely back onto the original document text... we can reopen this later / submit as an issue on the CoreNLP repo

**Comment by varun-tandon** [comment]
Cool, thanks for the help!
