### ISSUE TITLE
Make helper function to print feature names for a given candidate

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#369]
Currently will accept candidates[:0] as input but not candidates[0]. Should be a simple fix.

**Comment by bhancock8** [comment]
Added print_features(candidate) method to Featurizer. Will merge once the big ORM-learning_refactor merge has happened.

**Comment by ajratner** [comment]
Awesome!  Want to merge this into the learning-refactor branch for now?

**Comment by ajratner** [comment]
And agreed this is a better option, I think accepting both single candidates and lists/sets would be confusing

**Comment by bhancock8** [comment]
Yeah, I didn't think all the way through that transform() just returns a sparse matrix anyway, which isn't helpful if you're just trying to see which features are being generated on a particular candidate. Yep, I'll merge it into learning-refactor.
