### ISSUE TITLE
Support for higher-arity relations

### ISSUE THREAD

**Issue by cmorbaab** [HazyResearch/snorkel#370]
I am trying to make a relations object that contains 4 different objects. I know that currently relations object are made for two objects, but is there any way I can make a 4-object relation and if not are there any good alternatives?

**Comment by ajratner** [comment]
Hi @cmorbaab ,

Can you give me an example?  Is there a way to approach this first as several pairwise relations, or is it definitely a 4-way relation?

We don't currently have this built in; no major technical issue, just not built as of yet, sorry...

**Comment by ajratner** [comment]
Either way this is definitely on our list of todos

**Comment by bhancock8** [comment]
Subsumed by #358.
