### ISSUE TITLE
Improve parsing of batch text from cells by CoreNLP

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#371]
The current approach is to parse one table at a time (to avoid overreaching the character size limit). We separate each cell with a period and space and record cell start/end indices and then re-slice the parse from CoreNLP. Better solution would be to get CoreNLP to do auto-separation as well as a user-defined delimiter.

**Comment by bhancock8** [comment]
Solved! After a deep dive into the world of CoreNLP options...but we now get approximately 2x speedup on small sets.

**Comment by ajratner** [comment]
Nice!!  What was the exact solution- could you put a brief description both
b/c sounds awesome and I'm curious, and for future reference?  Thanks!

**Comment by bhancock8** [comment]
Fairly straightforward: I parse with the option "ssplit.htmlBoundariesToDiscard:delim", and the text I pass it is "delim.join(cell.text for cell in table.cells)" where delim in both of those is just "<NC>" for new cell. (Though there's a gotcha--don't include the braces in the parser option, do include them in the text). I keep track of the starting character locations of each cell, and then reslice it up after it's parsed. They had a few other options for providing artificial boundaries to separate on, but many of those either didn't discard the boundaries or tried to base it off of whitespace, which I wanted to avoid since tables are likely to have plenty of odd whitespace issues of their own.
