### ISSUE TITLE
how to access final results

### ISSUE THREAD

**Issue by sangha123** [HazyResearch/snorkel#372]
After building a satisfactory model what is the path to obtaining the prediction. I followed the tutorial on learning. It does not have a step that writes the predicted outcome for each candidate to a file.

**Comment by ajratner** [comment]
use `DDLiteModel.get_predicted()`, see https://github.com/HazyResearch/snorkel/blob/master/snorkel/snorkel.py#L1178

However this will be changing soon as we finish the v0.3 refactor; this will include a new tutorial, and we'll be sure to show how to specifically do this there as well!

**Comment by sangha123** [comment]
Thanks,

I have a demo tomorrow & this is immensely helpful.

--Sangha.

**Comment by chrismre** [comment]
Great to hear! Definitely keep us posted about demos--this week is crazy
(grants etc). Thanks for being understanding!

**Comment by sangha123** [comment]
Hi Chris,

Thanks for the support. Alex has been great about helping us.

--Sangha.

**Comment by MattMorgis** [comment]
Is there an updated way to do this now that you're on `v0.5`?

**Comment by ajratner** [comment]
Hi @MattMorgis ,

Thanks for bringing this up again!  Currently there are two basic ways.  The first is to use the `score` function as in Intro Tutorials 4 and 5; e.g.:
```
tp, fp, tn, fn = disc_model.score(session, L_test, L_gold_test)
```
Will give you four sets of candidates, corresponding to the true positives, false positives, true negatives, false negatives (note that if you are doing a categorical prediction, it will return two error buckets for correct / incorrect).

If you'd actually like to store predicted marginals to the database you can use the `save_marginals` and `load_marginals` helper functions (with `train=False` to signify predicted end marginals), see
https://github.com/HazyResearch/snorkel/blob/master/snorkel/annotations.py#L384.  We'll add this to the Intro Tutorial soon (re-opening until we do this!)
