### ISSUE TITLE
Track provenance of candidates

### ISSUE THREAD

**Issue by varun-tandon** [HazyResearch/snorkel#373]
Hi,

In an older version of Snorkel, Matchers could be labelled using the parameter label="label"; however this cannot be done in the current version of Snorkel.

Is there any other way to label a Matcher?

Thanks,
Varun

**Comment by ajratner** [comment]
Not currently, is this an important feature for your workflow?

**Comment by varun-tandon** [comment]
Hi Alex,
Although this would be useful, it is not necessary for us.

**Comment by ajratner** [comment]
Okay, if you end up thinking of somewhere where it would be, let us know!

In general, I can think of some uses, but we're not including at the moment
for simplicity.  Happy to reconsider down the road.  Thanks!

**Comment by ajratner** [comment]
@varun-tandon Another team noted that this would be helpful for debugging candidate extraction... reopening!

Also, specifically, we will want to track provenance in dictionaries too

**Comment by ajratner** [comment]
Nvm actually, waiting till post-ORM
