### ISSUE TITLE
Support for relations (higher arity Candidates)

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#375]
Summary from 8/3 session with Braden, Alex, Sen, and Jason:

If we're extracting (part number, storage temperature) pairs from sentences, we could use the following commands/classes (where ngrams is a CandidateSpace object, part_matcher/temp_matcher are Matcher objects, and candidates is a Candidates object):

```python
parts              = EntityExtractor(ngrams, part_matcher)
temp               = EntityExtractor(ngrams, temp_matcher)
relation_extractor = RelationExtractor(parts, temp, join_attribute='sentence_id')
candidates         = relation_extractor.apply(corpus.get_contexts())
```

The context_id attribute for higher-arity candidates will be created compositionally from its component entities.

Eventually, we can create a Joiner object (instead of the join_attribute argument) so that joins could occur by key, by attribute, by range (e.g., entities within a certain pixel distance in an image), etc.

Candidates of arity > 2 could either be handles by passing RelationExtractor more EntityExtractors, or by building up (e.g., a candidates object consisting of (a,b,c) can be made of an (a,b) candidate and a (c) candidate)

Comments welcome.

**Comment by ajratner** [comment]
Okay new syntax, which I am implementing with Steve now:
```python
relation_extractor = CandidateExtractor([ngrams, ngrams], [parts, temp], join_attribute=None)
```

In particular:
* `ngrams` is a `CandidateSpace` object, `parts,temp` are `Matcher` objects
* The output candidate type (in this case `SpanPair`) is implied by the context (in this case `Sentences`)
* The join attribute is by default implied by the generator of contexts passed in, i.e. if a generator of `Sentences` is passed in, then the implicit join is on parts and temperature spans being in the same sentence
* We'll have a check which will handle relations of the same unary type e.g. protein-protein
* Note that `Ngrams` is a `CandidateSpace` object, which generates a certain set of `Span` objects (renamed from `Ngram`)
