### ISSUE TITLE
CandidateSpace splitter shouldn't split on Penn TreeBank Tokens

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#378]
Currently, special tokens like -LRB- and -RRB- will get split by the CandidateSpace object when char splits are defined. All the CoreNLP/PennTreeBank markup should be ignored during the split.

**Comment by ajratner** [comment]
@jason-fries is this one closed now too?

**Comment by jason-fries** [comment]
Also fixed!
