### ISSUE TITLE
Generating candidates that aren't in the text verbatim

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#392]
For the IoT project with tables, we would like to be able to have candidates that are _inferred_ from a span without actually being present. For example, given a list of part numbers “BC348...350”, we would like to return ["BC348", "BC349", "BC350"], despite "BC349" never actually showing up in the text. Basic options I see:

1. Expand this list in preprocessing. I don't love that idea.
2. Incorporate this in a Matcher. I don't know that this will work with our current setup, since Matchers are basically just filters that return a True/False on their inputs.
3. Incorporate this in a CandidateSpace. This seems like a better fit than the matcher, because here we can actually "generate" options for becoming candidates. Though it does go against the usual flow that we've seen so far where the Matcher is where most user preferences are expressed, rather than the CandidateSpace.

The main issue I see here then is just that the text of the candidate won't actually correspond to true character offsets, so get_span('words') and friends may not work as expected. I'm sure there's a way to make this all work regardless, but I wanted to see if any of you (esp. @ajratner, @stephenbach, @lukehsiao) have any immediate thoughts on this for a particularly elegant solution.

**Comment by ajratner** [comment]
Similar to #138

I agree that #3 is the nicest way to go!

**Comment by ajratner** [comment]
(Meant option 3, not issue number 3)

**Comment by bhancock8** [comment]
Ah yes, that is a relevant thread. There could be two issues here though:
1) composite mentions (maybe allowing char_start and char_end to be lists?)
2) hallucinated mentions (adding a mention that isn't actually in the text, but is in inferred, as in our case)

**Comment by ajratner** [comment]
Yeah so I agree with you completely that modifying the candidate space is
the way to go. And then yes we just need to think though the downstream
effects

**Comment by bhancock8** [comment]
Additional examples:
Lists: BC348A/348B/348C
Ranges: BC348...350
Groups: Group A (where BC348A, BC349A, and BC350A are all referenced in the table somewhere)

**Comment by bhancock8** [comment]
A thought on the implicit spans that we may use to address this issue:

Since they're created after the initial parse that creates the corpus, they won't necessarily have all the CoreNLP tags that all verbatim spans have. We could either resolve this by:

a) allowing the user to specify if/how they would like to define the POSes, lemmas, etc. for the implicit spans they create and add additional error handling for those methods (such as get_span()) that expect these attributes to always be non-None

b) calling the CoreNLP server again on the words in these implicit spans and have all those attributes populated automatically. pro: less handling of edge cases. con: more calls to CoreNLP, which may cause a performance hit?

I vote (b), since most of the time, people won't be using a CandidateSpace that does range splitting, so it's a non-issue, and those that _are_ providing their own range-splitting rules and likely willing to take the (probably very small) hit to have their ranges enumerated.

**Comment by bhancock8** [comment]
This is incorporated via ImplicitSpan objects in the tables_master branch. Coming soon to a master branch near you.
