### ISSUE TITLE
Relation Annotation: Add Single/Multi Relation Mode to Viewer

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#405]
Currently, the viewer lists all relations within a single document. During annotation, this introduces the need for extra clicking to navigate through individual relations. We should have an annotation mode that only shows one relation per document, generating multiple views of the same doc.

**Comment by ajratner** [comment]
I'm going to close this for now, as I think the current viewer mode should be better here now, but feel free to reopen!
