### ISSUE TITLE
fit_transform dev-ppi branch

### ISSUE THREAD

**Issue by sangha123** [HazyResearch/snorkel#410]
F = span_featurizer.fit_transform(c.candidates)

AttributeError: 'SpanFeaturizer' object has no attribute 'fit_transform'

Is fit_transform not written as yet?

**Comment by ajratner** [comment]
Hi @sangha123 ,

Unfortunately this branch is still in "dev" mode so documentation is a little lacking: If you see in the [code](https://github.com/HazyResearch/snorkel/blob/dev-ppi/snorkel/features.py#L14), the featurizer is now based around saving and then loading from the database (which will just be sqlite if you don't set anything up); so:

1. First you can generate features which are saved to the db using `featurize_and_save(session, candidates)`;

2. Then, you load them back in as a sparse matrix, and also fit the feature space (`load_and_fit(session, candidate_set)`) or just load without fitting (`load(session, candidate_set)`).

Anyway, we'll have documentation up for all of this soon when we merge it into `master`.  In the meantime thanks for being adventurous on the dev branch!

-Alex
