### ISSUE TITLE
regex matcher possible improvement

### ISSUE THREAD

**Issue by DrPinkACN** [HazyResearch/snorkel#414]
Any interest in expanding to support lookahead and lookbehind? e.g. `(?<=VB DT )NNP(?= NNP)`

Maybe this already exists and I don't know whare it is.

**Comment by ajratner** [comment]
It should support this already?  It uses python's default `re` library which has support according to: https://docs.python.org/2/library/re.html

**Comment by ajratner** [comment]
Let me know if this is not the case for some odd reason?

**Comment by DrPinkACN** [comment]
So, re.match() starts at the beginning of the text so anything leading or trailing get truncated. re.findall is really the only way to use la/lb. I want the surrounding POSes to add context to the extraction, but not actually be included in the extraction.

**Comment by ajratner** [comment]
Ah okay, my mistake.  I would be inclined to say that this sort of logic would be better expressed as a labeling function rather than a hard filter in the candidate extraction stage.  But we can look into this / discuss in person perhaps

**Comment by ajratner** [comment]
Hi @DrPinkACN I'm going to close this for now, but let's discuss this in person & feel free to reopen!

**Comment by DrPinkACN** [comment]
Sounds good. Thanks for the heads-up.
