### ISSUE TITLE
Modify README.md to make python2 clear

### ISSUE THREAD

**Issue by artclarke** [HazyResearch/snorkel#420]
(Minor feedback, but figured you'd want it):

I suggest modifying the README.md to note that Snorkel is based on Python 2, and change the virtual env instructions to explicitly tell folks to use python3.

`virtualenv -p python2.7 <path-to-virtual-env>`

Why: My mac is set up to default to python3, and I lost 20-mins on set-up downloading all the requirements and core-NLP (admittedly I was on a crappy network connection, but still) before my notebooks failed immediately due to the python2 dependency, and I had to re-download the python dependencies again in a new python2 virtualenv.

**Comment by ajratner** [comment]
Hi @artclarke ,

Sorry about the trouble, but thanks for the suggestion!  I just pushed an edit to the README.  Excited that you're trying out the system!

-Alex
