### ISSUE TITLE
Update text in Intro Tutorial

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#426]
The first page of the [Intro Tutorial](https://github.com/HazyResearch/snorkel/blob/41914615d11e95e76b090b51242fd12ed77f41e1/tutorials/intro/Intro_Tutorial_1.ipynb) in the `tables_merge` branch has a typo.

The intro walks through finding spouses in the news, but contains the text

> We'll start by defining a DocParser class to read in Pubmed abstracts from Pubtator), where they are stored along with "gold" (i.e. hand-annotated by experts) chemical and disease mention annotations. We'll use the XMLDocParser class, which allows us to use XPath queries to specify the relevant sections of the XML format.

and the text

> We will rerun the same operations for the other two CDR corpora: development and test. All we do is change the path that the XMLMultiDocParser uses.

both of which references PubMed and a different task. Update this to reflect the task of finding spouses in the news.

To Do:
- [ ] Fix text block 1
- [ ] Fix text block 2

**Comment by stephenbach** [comment]
Hi @lukehsiao Thanks for the feedback on the tutorial! Would you mind also trying out the intro tutorial on the tutorial branch? That's the most up to date version, which has this fixed. We can then merge that branch into others.

**Comment by lukehsiao** [comment]
Ah, the `tutorial` branch looks great. Thanks!
