### ISSUE TITLE
Need access to session in LF

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#427]
Many table-related LFs rely on the text in "aligned" cells. To get aligned cells, I currently use something like:

`axis_name = "row_num"`
`aligned_cells = [cell for cell in root_cell.table.cells if getattr(cell, axis_name) == getattr(root_cell, axis_name)  and cell != root_cell]`

This obviously has terrible time complexity because we need to touch every cell in the table anytime we look at aligned cells. It would be nice to be able to do a SQL query on the Cells table, but to do that, I believe we need to have access to the session variable, which currently isn't passed. Any objections to me adjusting annotations.py to pass in session to each annotation_generator?

**Comment by stephenbach** [comment]
I think the ideal here would be to define things like getting aligned cells as methods of the appropriate contexts, rather than expanding the LF signature. An object can access its current session using http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.object_session
so something like
```
session = SnorkelSession.object_session(self)
```

You could even put this directly in the LFs you're developing as a quick fix.

**Comment by bhancock8** [comment]
Oh, perfect! Good to know they can access their own session. I'll go down that route instead. Thanks!

**Comment by bhancock8** [comment]
So I made a quick-fix version that gets the session in the LF and does a proper query. But the new version is a lot slower (>10x) than the old version (which already wasn't fast). Could it be that there's just too much overhead to getting the session and doing the query? I suppose the next thing I could do is begin storing with each cell a list of the ids of cells that are in its row and col, but then to actually get those cells' contents, I think I'd still need to get the session and do a query, right?

# WITHOUT SQL:
def _get_aligned_cells(root_cell, axis, infer=False):
    axis_name = axis + '_num'
    other_axis = 'row' if axis=='col' else 'col'
    aligned_cells = [cell for cell in root_cell.table.cells
        if getattr(cell, axis_name) == getattr(root_cell, axis_name)
        and cell != root_cell]
    return [_get_nonempty_cell(cell, other_axis) for cell in aligned_cells] if infer else aligned_cells 

# WITH SQL:
def _get_aligned_cells(root_cell, axis, infer=False):
    session = SnorkelSession.object_session(root_cell)
    if axis == 'row':
        aligned_cells = session.query(Cell).filter(
            Cell.table_id == root_cell.table_id).filter(
            Cell.row_num == root_cell.row_num).filter(
            Cell.id != root_cell.id).all()
        other_axis = 'col'
    else:
        aligned_cells = session.query(Cell).filter(
            Cell.table_id == root_cell.table_id).filter(
            Cell.col_num == root_cell.col_num).filter(
            Cell.id != root_cell.id).all()
        other_axis = 'row'
    return [_get_nonempty_cell(cell, other_axis) for cell in aligned_cells] if infer else aligned_cells

**Comment by stephenbach** [comment]
Why can't the "without SQL" version be implemented as a class method?

Using SQLAlchemy methods to traverse the structure is doing essentially the same thing: using root_cell's internal session to issue queries as needed. The performance difference might be due simply to SQLAlchemy generating the query more efficiently and/or generating a more efficient query.

**Comment by bhancock8** [comment]
I think the "without SQL" version _can_ be implemented as a class method, I was just trying the "quick fix" version first to get a quick comparison on runtime, since even as a class method, it will be performing essentially the same steps/query.
