### ISSUE TITLE
CandidateSet.stats() minor text change

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#428]
In the [CandidateSet stats() function](https://github.com/HazyResearch/snorkel/blob/f83623e12c6778c73c5fc8d7b7000497287bbd8d/snorkel/models/candidate.py#L58) the output looks like `0.XX%`. Really, it should either be `0.XX` or `XX%`.

**Comment by ajratner** [comment]
Closed in v0.5.0
