### ISSUE TITLE
CoreNLP dependency in tutorial

### ISSUE THREAD

**Issue by Gijs-Koot** [HazyResearch/snorkel#433]
The dependency on the CoreNLP java library isn't explicitly mentioned as something you'd need to install. If you don't, the tutorial will just hang idly on the lines 

   from snorkel.parser import CorpusParser

   cp = CorpusParser(doc_parser, sent_parser)
   %time corpus = cp.parse_corpus(session, 'News Training')

with no warning. I digged into the source files to find out what was going on (CoreNLP not found in the `JAVAPATH`). This could be friendlier for people trying out the system.

**Comment by ajratner** [comment]
Hi @Gijs-Koot ,

Thanks for the note!  If you ran the notebooks using the `run.sh` script, it will check if the parser is installed and install it if not.  However, we'll add a note to the install instructions as well!

-Alex
