### ISSUE TITLE
GridSearch back up and running in a tutorial

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#436]
Looks like most of the code is already there. Hopefully very little tweaking is required to get it in one of the tutorials again.

**Comment by ajratner** [comment]
@henryre When we get a chance let's discuss how to get all the good stuff from DDLite back in here!

**Comment by henryre** [comment]
Just so I remember to do this: let's put in a random searcher for tutorial speed

**Comment by henryre** [comment]
Closed by #439
