### ISSUE TITLE
Corpus.stats() broken for tables

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#437]
The stack trace is below. I suspect it has something to do with the fact that for tables, a Document has more types of children than 1 (i.e., not just Sentences; a Document has Table, Cell, and Phrase children). The error is reproducible on the tables_master branch if you Clean and Run All in the Tables_Sandbox.ipynb notebook.

---

ValueError                                Traceback (most recent call last)
<ipython-input-4-f977e04f404d> in <module>()
----> 1 get_ipython().magic(u"time corpus = cp.parse_corpus(name='Sandbox', session=session)")
      2 print "%d Phrases in %s" % (
      3     len([phrase for doc in corpus.documents for phrase in doc.phrases]), corpus)

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2334         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2335         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2336         return self.run_line_magic(magic_name, magic_arg_s)
   2337 
   2338     #-------------------------------------------------------------------------

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2255                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2256             with self.builtin_trap:
-> 2257                 result = fn(_args,_*kwargs)
   2258             return result
   2259 

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, _a, *_k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, _a, *_k: f(_a, *_k)
    194 
    195         if callable(arg):

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1165         else:
   1166             st = clock2()
-> 1167             exec(code, glob, local_ns)
   1168             end = clock2()
   1169             out = None

<timed exec> in <module>()

/Users/bradenhancock/snorkel/snorkel/parser.py in parse_corpus(self, session, name)
     46         if session is not None:
     47             session.commit()
---> 48         corpus.stats() # Note: corpus.stats breaks with OmniParser
     49         return corpus
     50 

/Users/bradenhancock/snorkel/snorkel/models/context.py in stats(self)
     49         """Print summary / diagnostic stats about the corpus"""
     50         print "Number of documents:", len(self.documents)
---> 51         self.child_context_stats(Document)
     52 
     53     def child_context_stats(self, parent_context):

/Users/bradenhancock/snorkel/snorkel/models/context.py in child_context_stats(self, parent_context)
     73             # Render as panadas dataframe histogram
     74             df = pd.read_sql(query.statement, query.session.bind)
---> 75             df.hist(label)
     76 
     77             # Recurse to grandchildren

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/pandas/tools/plotting.pyc in hist_frame(data, column, by, grid, xlabelsize, xrot, ylabelsize, yrot, ax, sharex, sharey, figsize, layout, bins, **kwds)
   2891     fig, axes = _subplots(naxes=naxes, ax=ax, squeeze=False,
   2892                           sharex=sharex, sharey=sharey, figsize=figsize,
-> 2893                           layout=layout)
   2894     _axes = _flatten(axes)
   2895 

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/pandas/tools/plotting.pyc in _subplots(naxes, sharex, sharey, squeeze, subplot_kw, ax, layout, layout_type, *_fig_kw)
   3378 
   3379     # Create first subplot separately, so we can share it if requested
-> 3380     ax0 = fig.add_subplot(nrows, ncols, 1, *_subplot_kw)
   3381 
   3382     if sharex:

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/matplotlib/figure.pyc in add_subplot(self, _args, *_kwargs)
   1003                     self._axstack.remove(ax)
   1004 
-> 1005             a = subplot_class_factory(projection_class)(self, _args, *_kwargs)
   1006 
   1007         self._axstack.add(key, a)

/Users/bradenhancock/anaconda/lib/python2.7/site-packages/matplotlib/axes/_subplots.pyc in __init__(self, fig, _args, *_kwargs)
     62                     raise ValueError(
     63                         "num must be 1 <= num <= {maxn}, not {num}".format(
---> 64                             maxn=rows*cols, num=num))
     65                 self._subplotspec = GridSpec(rows, cols)[int(num) - 1]
     66                 # num - 1 for converting from MATLAB to python indexing

ValueError: num must be 1 <= num <= 0, not 1

**Comment by zzdang** [comment]
how did u solve it?
thanks

**Comment by bhancock8** [comment]
@zzdang I commented it out. :) Further inspection will need to happen at some point to figure out what's causing the break.

**Comment by zzdang** [comment]
Could you tell me whether I should amend parser.py and context.py or not? 
What files you amended?
thanks a lot.

**Comment by bhancock8** [comment]
I just commented out the line in parser.py in the CorpusParser object that says "corpus.stats()"

**Comment by ajratner** [comment]
Closed in v0.5.0
