### ISSUE TITLE
Need to clip values in odds_to_prob

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#448]
For large numbers will return `NaN` because `np.exp` returns `inf`, rather than approaching 1.0

**Comment by chrismre** [comment]
Use clamp :) :+1:

**Comment by bhancock8** [comment]
I'm seeing numpy.clip(), not clamp. Is that what you're referring to?

**Comment by henryre** [comment]
clamp is Julia :)
We were using clip before
