### ISSUE TITLE
change `case_sensitive` to `lowercase` in lf_helpers

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#456]
Many of the current [lf_helpers.py](https://github.com/HazyResearch/snorkel/blob/bab510cb33651e7d908f982216c1a672b661fd02/snorkel/lf_helpers.py) functions have a parameter called `case_sensitive`. But, what that actually does is:

>case_sensitive: If false, all ngrams will be returned in lower case

We probably want to rename these all to `lowercase`, so that user's don't think that the case of their comparison strings doesn't matter when using these functions.

**Comment by bhancock8** [comment]
Done.
