### ISSUE TITLE
Paragraphs outside tables are being assigned table numbers

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#457]
This will eventually be fixed with the new parser, but currently in `VSMIS03793-1.html`, the phrase `- 50` appears outside of a table in the HTML, but is being assigned to the most recent table:

```
Phrase(Doc: VSMIS03793-1, Table: 5, Row: X, Col: X, Position: 0, Text: - 50 %C)
In [31]:
```

This is causing LFs that try to label temperatures outside of tables to not fire.

**Comment by bhancock8** [comment]
Not anymore.
