### ISSUE TITLE
Bug in get_left_ngrams and get_right_ngrams

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#458]
Given a phrase:
```
Phrase(Doc: PNJIS01593-1, Table: X, Row: X, Col: X, Position: 0, Text: Typical Thermal Resistance, Junction to Ambient                          R % JA                                                     375                                          o C/W Operating Junction and Storage Temperature   Range                 T J ,T STG                                           -50 to 150                                       o C)
```
With the words
```
[u'Typical', u'Thermal', u'Resistance', u',', u'Junction', u'to', u'Ambient', u'R', u'%', u'JA', u'375', u'o', u'C/W', u'Operating', u'Junction', u'and', u'Storage', u'Temperature', u'Range', u'T', u'J', u',', u'T', u'STG', u'-50', u'to', u'150', u'o', u'C']
```

We noticed that the `window` parameter seems to just start at the beginning of the phrase all the time. So, `get_left_ngrams` returns nothing, while `get_right_ngrams` with `window=7` is returning:

```
[u'thermal', u'resistance', u',', u'junction', u'to', u'ambient', u'r']
```

It looks like the reference point is always "Typical", the start of this particular phrase.

The span itself is:
```
ImplicitSpan("-50", parent=7724, words=[0,0], position=[0])
```
which looks like it thinks it is the start of the phrase, even though it isn't.

**Comment by bhancock8** [comment]
The issue was in the way ImplicitSpans were not overwriting the function looks up their word index in their parent. Fixed now.
