### ISSUE TITLE
Whats the best approach for extracting many relations?

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#461]
So far, most of the tutorials walk through extracting a single relation in 5 steps, where each step is in a separate notebook.

What's the recommended way to organize a Snorkel application if we want to extract multiple relations? For example, rather than just `has_spouse`, we want `is_cousin`, `is_sibling`, `is_parent`, etc. 

How should this be organized? How should all the results be aggregated together?

**Comment by xiao-cheng** [comment]
I think the way it is being set up right now, you have to create separate candidate classes/LFs but can share the same snorkel.db

**Comment by ajratner** [comment]
Hi @lukehsiao I think this is a great question

First of all, these can definitely live in the same database and I would do this

Second: this brings up the (actually quite important) question of how we should encourage users to organize their notebooks / code in general; ideally many LFs could be reused between the different relations, as well as other code, so should be organized correctly

Third: in DeepDive, we might want to represent the (presumably) exclusive nature of some of these relationships as factors in a factor graph.  We don't currently have this level of expressive power in Snorkel (on purpose), but we should discuss if it might be useful.  Can we do okay just by sharing certain LFs (but with flipped polarities)?  Or should we support templates for models that have simple exclusivity factors, if this is a general enough use case?  Let's discuss further!

**Comment by ajratner** [comment]
This is still a good question / area for further effort but no immediate action item (I think?) so closing for now!
