### ISSUE TITLE
fast_annotations causes computer crash

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#464]
I don't have many details, but when running fast_annotations on about 100k candidates, my computer completely freezes, requiring a hard reset.

For the cell:

```
from snorkel.models import CandidateSet
from snorkel.fast_annotations import FeatureManager
from snorkel.utils import get_ORM_instance

train = get_ORM_instance(CandidateSet, session, 'Hardware Training Candidates')
dev   = get_ORM_instance(CandidateSet, session, 'Hardware Development Candidates')

feature_manager = FeatureManager()
%time F_train = feature_manager.create(session, train, 'Train Features')
%time F_dev = feature_manager.update(session, dev, 'Train Features', expand_key_set=False)
```

I get the output:

```
[=========================================] 100%

Bulk upserting 23332483 annotations...
```

at which point my computer is completely unresponsive.

**Comment by xiao-cheng** [comment]
have you checked the RAM usage right before it? In order to bulk insert it keeps a list of rows. 23 million rows could take around 4~8GB of RAM

According to the output the freezing happens during the bulk insertion, so the problem is either we shouldn't keep so many rows or it's some problem with the underlying DB engine. (SQLite probably not good for this)

**Comment by lukehsiao** [comment]
I have 16GB of memory on this machine. I haven't checked RAM usage right before, yet.

**Comment by lukehsiao** [comment]
I believe this was caused by perhaps unrelated problems on that particular machine. On my laptop, I do not see this problem at all. Going to close this for now. Can reopen if this is actually a problem, but I suspect that it isn't.

**Comment by xiao-cheng** [comment]
This shouldn't be a problem later as fast_annotation is getting deprecated. New async_annotation runs feature extraction in map reduce style which only needs constant memory regardless of the size of input.
