### ISSUE TITLE
Trying the intro tutorial 1

### ISSUE THREAD

**Issue by cognitronz** [HazyResearch/snorkel#474]
Hi,

A newbie question about Snorkel.  I tried to run the 1st tutorial.  everything seems to be setup nicely, but I am stuck in teh corpus parsing.  I understand the corpus can take a while, but i looked at the training text file, it's only a few MB, so I dont expect it to take more than 10 min.  So I am just wondering if anyone has had trouble finishing the parser (see attachment below)

![image](https://cloud.githubusercontent.com/assets/6811782/19952779/2b1d0fc2-a125-11e6-9364-e12c11fcdb39.png)

BTW, nicely done.  Great documentation!

**Comment by stephenbach** [comment]
Hi,
Thanks for trying out Snorkel and the feedback!

Parsing in that tutorial does take 10-20 minutes on many systems. Most of this time is spent in CoreNLP, the awesome natural language processing tool that does things like split documents into sentences and identify all the named entities.

Hopefully it shouldn't take longer than that. Let us know if it seems to be hanging beyond 20 minutes, but otherwise that is expected behavior.

**Comment by cognitronz** [comment]
Thanks for the quick reply.  I know what caused the delay, but not sure how to fix it (see attachment).

I am running the snorkel on a m4.large server, and log onto the jupyter remotely via https.  i see the corenlp is trying to access 127.0.01:12345  not sure if that's the issue here.

![image](https://cloud.githubusercontent.com/assets/6811782/19952952/5a3f8ef0-a126-11e6-831b-79a77d248730.png)

**Comment by cognitronz** [comment]
Ah, i dont have the right version of Java.  do you which versoin of Java i should install on Ubuntu to properly use coreNLP?

**Comment by stephenbach** [comment]
Should be Java 8. Perhaps this is helpful: http://titipata.github.io/2016/03/02/stanford-nlp.html

**Comment by cognitronz** [comment]
Thanks! SO close.  I successfully finished the coreNLP, but it failed at the session.commit().  any ideas?


![image](https://cloud.githubusercontent.com/assets/6811782/19953720/76141c60-a12e-11e6-92df-2134bba83fab.png)

![image](https://cloud.githubusercontent.com/assets/6811782/19953703/41a4509e-a12e-11e6-9780-d7d60977c954.png)

**Comment by bhancock8** [comment]
You're right--you're SO close. That "UNIQUE constraint failed" message comes when you're trying to insert something into the snorkel.db database that's already there. You probably succeeded in partially inserting something before, and now you're violating that constraint. Try deleting the snorkel.db file and letting a new one be created when you run again. See if that fixes it. If not, there's a possibility that you actually do have a duplicate and you may be parsing two documents with identical names and contents.
