### ISSUE TITLE
Document new dependencies for tables_master

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#475]
There are some new dependencies required (opencv, poppler, editdistance) for `tables_master`. It would be great if these could just be added to the virtual environment by adding to `python-package-requirement.txt`. But, that may not be possible. In any case, let's make sure to document what needs to be installed and provide instructions.

**Comment by bhancock8** [comment]
Notes:
Add edit_distance to python-package-requirement.txt
Get poppler with apt-get like we do CoreNLP?
But cv2 comes from opencv and cannot be pip'd (and conda downgrades other packages); find a way to download and move into the right path in the virtual env...?
