### ISSUE TITLE
features.py - unexpected keyword argument keywords

### ISSUE THREAD

**Issue by edoughty** [HazyResearch/snorkel#489]
On dev, I got an error when running the following code:
`%time F_train = feature_manager.create(session, cands, 'train features')
`
The error (not showing the full traceback):
```

/Users/Emily/Documents/lab/deepdive/dd-bio-examples/snorkel_v0.4/snorkel/snorkel/features.py in get_span_feats(candidate, stopwords)
     45 
     46             # Apply TDL features
---> 47             for f in get_tdl_feats(xmltree.root, s1_idxs, s2_idxs, stopwords=stopwords):
     48                 yield 'TDL_' + f, 1
     49     else:

TypeError: apply_relation() got an unexpected keyword argument 'stopwords'

```
I modified line 47 in features.py to fix the issue

Original:
Line 47:            for f in get_tdl_feats(xmltree.root, s1_idxs, s2_idxs, stopwords=stopwords):

Fixed by commenting:
Line 47:            for f in get_tdl_feats(xmltree.root, s1_idxs, s2_idxs): #, stopwords=stopwords):

**Comment by henryre** [comment]
Hey @edoughty, are you on the dev branch? Shouldn't happen in `master`. Fix is to switch to the `stopwords` branch in the `treedlib` submodule. I'll update the branch pointer tomorrow.

**Comment by afritzler** [comment]
I updated the treedlib to master and I am still seeing the same error. :-(

**Comment by henryre** [comment]
Hi @afritzler. The changes have been pulled into master on treedlib. Make sure both snorkel and treedlib are up to date and on their respective master branches. Let me know if that works.

**Comment by afritzler** [comment]
Hm strage, snorkel and treedlib are all on master on my side. 

To make it work, I commented out the line as proposed by @edoughty 
```
Fixed by commenting:
Line 47: for f in get_tdl_feats(xmltree.root, s1_idxs, s2_idxs): #, stopwords=stopwords):
```

**Comment by henryre** [comment]
Hey @afritzler. You're totally right, and our build was failing from this error. We're fixing it now, so I'll comment back here when it's done

**Comment by henryre** [comment]
Ok all set. Just pull from master (on Snorkel) and you should be fine.
