### ISSUE TITLE
Visual html to pdf

### ISSUE THREAD

**Issue by xiao-cheng** [HazyResearch/snorkel#502]
Is there a particular reason why we are introducing the dependency on selenium instead of just invoking the phantomjs script with os.shell by passing in formatting arguments? Generally we want to avoid external dependencies because it makes maintenance and reproducing our results harder.

Currently create_pdf crashes with `connection reset by peer error` during parsing when it can not find a pdf corresponding to a html.

**Comment by ajratner** [comment]
Think this is old... reopen if needed
