### ISSUE TITLE
Install Enhancements

### ISSUE THREAD

**Issue by thomasklau** [HazyResearch/snorkel#506]
Hi All, 

Have a new notes about the installation instructions:

Running pip installs dependencies for python3. I had to run pip2 to correctly install the dependencies for python2.

I didn't have source in my shell. See [this](http://askubuntu.com/questions/20953/sudo-source-command-not-found). Therefore, I just ran '. set_env.sh' manually.

I saw that someone else also had these problems following the installation instructions so thought I would post.

**Comment by thomasklau** [comment]
Also, running the environment script didn't correctly append snorkel to my path in jupyter. It did for python via the shell. See below:

Code: 
import sys
print(sys.path)

Ouput in shell:
['', '/home/thomas/Desktop/gym', '/home/thomas/snorkel', '/home/thomas/snorkel/treedlib', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0']

Output in Jupyter:
['', '/home/thomas/Desktop/gym', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/local/lib/python2.7/dist-packages/IPython/extensions', '/home/thomas/.ipython']

Had to manually add it to my path in jupyter.

**Comment by thomasklau** [comment]
Update: Found out that the path was different because I ran sudo to start jupyter notebook. Worked fine when I ran the environment script as sudo

**Comment by thomasklau** [comment]
Also, in tutorial 1, Snorkel wasn't able to do the request without running jupyter in sudo.

**Comment by ajratner** [comment]
Hey @thomasklau thanks for posting these notes!!  We'll incorporate them into the install instructions on our next pass

**Comment by ajratner** [comment]
Closing this but referencing it in README, thanks!
