### ISSUE TITLE
Additional instructions needed to configure Jupyter within Virtualenv

### ISSUE THREAD

**Issue by b-ad** [HazyResearch/snorkel#508]
Following the installation instructions using virtualenv resulted in a Jupyter notebook that only looked to global and user libraries, not to the snorkel packages and dependencies installed within the virutalenv.  I was able to fix this by following instructions here: http://help.pythonanywhere.com/pages/IPythonNotebookVirtualenvs

I realize that this is a function of how Jupyter works, not a problem with Snorkel.  And this may have been obvious to more experienced users than me.  But since you have (very kindly!) written your installation instructions for less-experienced users, you might want to anticipate other users encountering this problem.  I don't know if the fix can be written into the install script, or if just requires more explanation.

Thank for your work on this!

**Comment by b-ad** [comment]
It looks like this is the same observation as here, but I didn't understand the problem enough to recognize that as the answer :) : https://github.com/HazyResearch/snorkel/issues/506#issuecomment-264687739

**Comment by ajratner** [comment]
Thanks, adding this to README now!
