### ISSUE TITLE
Python 3 compatability

### ISSUE THREAD

**Issue by dhimmel** [HazyResearch/snorkel#509]
I didn't see [any dependencies](https://github.com/HazyResearch/snorkel/blob/40dfdc586b72412f9825b0f5f16d02b0ed98626a/python-package-requirement.txt) that are 3 incompatible. Is the lack of Python 3 support just because it's not a priority?

It would be nice to snorkel in Python 3 pipelines. Especially since for analyzing text the default unicode strings would be convenient.

I tend to be extreme on these issues, but I'd even advocate for dropping 2 support to make development cleaner.

This is not a major issue for me, as workarounds are easy -- but just wanted to get the perspectives of the developers.

**Comment by ajratner** [comment]
@dhimmel primarily just busy :)  We will most likely want to move to Python 3 at some point once we catch up on other development priorities!

**Comment by ajratner** [comment]
Should be closed now!

**Comment by dhimmel** [comment]
Tagging @danich1. Hopefully we can upgrade `greenelab/snorkeling` to python 3 now.
