### ISSUE TITLE
cdr/CDR_learning.ipynb bug

### ISSUE THREAD

**Issue by danich1** [HazyResearch/snorkel#513]
I was testing out the cdr/CDR_learning.ipynb notebook file and encountered an error. Wanted to know if there is a workaround towards this issue:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-1255920fc4ce> in <module>()
      1 from snorkel.features import get_span_feats
      2 
----> 3 get_ipython().magic(u"time F_train_span = feature_manager.create(session, train, 'training span feats', get_span_feats)")

/home/davidnicholson/anaconda3/envs/p27/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/home/davidnicholson/anaconda3/envs/p27/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-59> in time(self, line, cell, local_ns)

/home/davidnicholson/anaconda3/envs/p27/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/home/davidnicholson/anaconda3/envs/p27/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1178         else:
   1179             st = clock2()
-> 1180             exec(code, glob, local_ns)
   1181             end = clock2()
   1182             out = None

<timed exec> in <module>()

/home/davidnicholson/Documents/snorkel/snorkel/annotations.pyc in create(self, session, candidate_set, new_key_set, f)
    124         session.commit()
    125 
--> 126         return self.update(session, candidate_set, key_set, True, f)
    127 
    128     def update(self, session, candidate_set, key_set, expand_key_set, f=None):

/home/davidnicholson/Documents/snorkel/snorkel/annotations.pyc in update(self, session, candidate_set, key_set, expand_key_set, f)
    179         for i, candidate in enumerate(candidate_set):
    180             pb.bar(i)
--> 181             for key_name, value in annotation_generator(candidate):
    182                 # Check if the AnnotationKey already exists, and gets its id
    183                 key_id = session.execute(key_select_query, {'name': key_name}).first()

/home/davidnicholson/Documents/snorkel/snorkel/features/relative_features.pyc in get_binary_span_feats(sidxs, sentence, stopwords)
     55         # Apply TDL features
     56         for f in get_tdl_feats(xmltree.root, s1_idxs, s2_idxs,
---> 57                                stopwords=stopwords):
     58             yield 'TDL_' + f, 1
     59 

TypeError: apply_relation() got an unexpected keyword argument 'stopwords'

**Comment by henryre** [comment]
Hi @danich1. This can be fixed by pulling the master branch of [treedlib](https://github.com/HazyResearch/treedlib). The CDR tutorial is a work in progress right now, so just as a heads up you may run into other issues.

**Comment by danich1** [comment]
Ah I gotcha. Thanks!!
