### ISSUE TITLE
Progress bar critical error

### ISSUE THREAD

**Issue by henryre** [HazyResearch/snorkel#525]
![error](https://cloud.githubusercontent.com/assets/7783678/22044207/4bdc41f4-dcc8-11e6-8d82-c6cf9dae81a8.png)

**Comment by ajratner** [comment]
I think your architecture is probably not deep enough or too simple, have you even tried peepholing your LSTM brah (https://en.wikipedia.org/wiki/Long_short-term_memory#Peephole_LSTM)?

**Comment by henryre** [comment]
Ok I think I actually know what the problem is but I just really don't care enough to test it

https://github.com/HazyResearch/snorkel/blob/master/snorkel/udf.py#L74

**Comment by ajratner** [comment]
This is the comment of someone who doesn't care enough about progress bars, yup.  I'm gonna wait this one out...
