### ISSUE TITLE
Can I disable the stable label table?

### ISSUE THREAD

**Issue by henryre** [HazyResearch/snorkel#545]
Mission critical

**Comment by stephenbach** [comment]
At this time, users are not able to disable the stable label table.

Snorkel relies on the stable label table to be able to map stable labels to and from other label tables.

**Comment by henryre** [comment]
👏 👏 👏 👏 👏

**Comment by stephenbach** [comment]
#684

**Comment by henryre** [comment]
Prescience AND art, wrapped into one PR title. Can one nominate oneself the Nobel Prize?

**Comment by stephenbach** [comment]
Nevermind.
