### ISSUE TITLE
PDF Compatibility

### ISSUE THREAD

**Issue by Tsmith5151** [HazyResearch/snorkel#548]
Hi @henryre, is snorkel currently compatible to process searchable PDF documents? Also, is there a maximum number of documents that can be processed and additionally, is there any restrictions on the number of external labels for the testing set?

**Comment by henryre** [comment]
Hi @Tsmith5151. The stable release doesn't support PDF parsing just yet, but it's under active development. You can either check out the [`semi-structured` branch](https://github.com/HazyResearch/snorkel/tree/semi-structured) (at your own risk!), or use a [utility like `pdftotext`](http://www.tutorialspoint.com/unix_commands/pdftotext.htm) to convert to plain text documents first and then feed those into Snorkel.

**Comment by henryre** [comment]
Hey @Tsmith5151, sorry completely missed your other questions. There is no maximum number of documents (up to storage on your machine) and there is no restriction on the number of labels. You can attribute labels to different annotators by using the `annotator_name` argument when initializing a `StableLabel`, effectively giving you multiple label sets.
