### ISSUE TITLE
ZeroDivision Error

### ISSUE THREAD

**Issue by subarnas** [HazyResearch/snorkel#552]
Hi,

I got a ZeroDivision Error when I was running the CDR tutorial. The error seems to be in this line:gen_model.train(
    L_train, deps=deps, epochs=20, decay=0.95, step_size=0.1/L_train.shape[0], init_acc=2.0, reg_param=0.0
)

Any ideas on what could be an issue.
Below is a snapshot of the error message:

Running UDF...
[=                                       ] 0%-- listing properties --
port=12345
timeout=600000
Starting server on port 12345 with timeout of 600000 milliseconds.
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
        at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
        at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
        at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.run(StanfordCoreNLPServer.java:692)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:756)
[========================================] 100%%

Exited here.
Documents: 1500
Sentences: 14001
/usr/lib/pymodules/python2.7/matplotlib/__init__.py:1173: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Clearing existing...
Running UDF...
[========================================] 100%

/usr/lib/python2.7/dist-packages/scipy/sparse/sputils.py:141: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(M) == 0 and np.rank(N) == 0:
/usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:130: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.indices) != 1 or np.rank(self.indptr) != 1:
/usr/lib/python2.7/dist-packages/scipy/sparse/coo.py:200: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.row) != 1 or np.rank(self.col) != 1:
Traceback (most recent call last):
  File "CDR_Tutorial_2_new.py", line 292, in <module>
    L_train, deps=deps, epochs=20, decay=0.95, step_size=0.1/L_train.shape[0], init_acc=2.0, reg_param=0.0
ZeroDivisionError: float division by zero

**Comment by henryre** [comment]
Hi @subarnas. It's a little hard to tell from the info here, but since there's no traceback, it looks like `L_train.shape[0]` is zero. That is, there are no rows in the label function matrix. I can think of two reasons why:

* Candidate extraction hasn't been run. You can check the number of training candidates by running
```
from snorkel import SnorkelSession
from snorkel.models import candidate_subclass

session = SnorkelSession()
ChemicalDisease = candidate_subclass('ChemicalDisease', ['chemical', 'disease'])
train_cands = session.query(ChemicalDisease).filter(ChemicalDisease.split == 0).all()
print "There are {0} training candidates".format(len(train_cands))
```

* The labeling functions haven't been applied.
```
# Define LFs as in the tutorial
from snorkel.annotations import LabelAnnotator
labeler = LabelAnnotator(f=LFs)
L_train = labeler.load_matrix(session, split=0)
print "{0} labeling functions have been applied".format(L_train.shape[1])
```

**Comment by subarnas** [comment]
Thanks. It was an issue with candidate extraction. I made a mistake in merging the first two tutorials.

I did run into a type error issue in the gen_model.train() when I ran the code after I fixed the issue. 

Traceback (most recent call last):
  File "CDR_Tutorial_2_new.py", line 304, in <module>
    L_train, deps=deps, epochs=20, decay=0.95, step_size=0.1/L_train.shape[0], init_acc=2.0, reg_param=0.0
  File "/DATA/subarna/snorkel/snorkel2/snorkel-master/snorkel/learning/gen_learning.py", line 199, in train
    self._process_dependency_graph(L, deps)
  File "/DATA/subarna/snorkel/snorkel2/snorkel-master/snorkel/learning/gen_learning.py", line 305, in _process_dependency_graph
    setattr(self, dep_name, getattr(self, dep_name).tocoo(copy=True))
TypeError: tocoo() got an unexpected keyword argument 'copy'

**Comment by henryre** [comment]
Glad that got fixed. The `copy` issue looks like your version of `scipy` isn't updated to one of the last few releases. You can use `pip` or `conda` to upgrade `scipy`.
