### ISSUE TITLE
Article 256 in articles.tsv kills execution on raiders

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#559]
Running the intro tutorial (fresh out of the box, no changes) on my local machine works just fine, but running it on raiders7, execution of the first notebook (parsing the corpus) always stops dead in its tracks when it hits article 256 in articles.tsv. This seems to suggest it's a raiders issue rather than a Snorkel issue, but I thought I'd give a heads up in case anyone else runs into this. Also, I would be curious to see if anyone else experiences this on raiders?

**Comment by bhancock8** [comment]
Looking at that article, it's a bunch of headlines broken by newlines and ellipses rather than periods, yielding some very long "sentences". That could make CoreNLP time out on some processors and not others. Should we replace 256 with another sentence from the corpus of 1M articles?

**Comment by stephenbach** [comment]
Redid the intro tutorial.
