### ISSUE TITLE
CDR tutorial broken out of the box on master

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#564]
I'm trying to run the CDR out of the box (freshly downloaded data, brand new db) on master and getting the same error on both raiders and my local machine (stack trace below). Is this expected behavior, or does it work for you?

```
Clearing existing...
Running UDF...
[= ] 0%

DataError Traceback (most recent call last)
in ()
1 for k, sents in enumerate([train_sents, dev_sents, test_sents]):
----> 2 candidate_extractor.apply(sents, split=k, parallelism=1)
3 print "Number of candidates:", session.query(ChemicalDisease).filter(ChemicalDisease.split == k).count()

/lfs/raiders7/ssd/bradenjh/snorkel/snorkel/candidates.pyc in apply(self, xs, split, **kwargs)
180
181 def apply(self, xs, split=0, **kwargs):
--> 182 super(PretaggedCandidateExtractor, self).apply(xs, split=split, **kwargs)
183
184 def clear(self, session, split, **kwargs):

/lfs/raiders7/ssd/bradenjh/snorkel/snorkel/udf.pyc in apply(self, xs, clear, parallelism, progress_bar, count, **kwargs)
38 print "Running UDF..."
39 if parallelism is None or parallelism < 2:
---> 40 self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
41 else:
42 self.apply_mt(xs, parallelism, clear=clear, **kwargs)

/lfs/raiders7/ssd/bradenjh/snorkel/snorkel/udf.pyc in apply_st(self, xs, progress_bar, count, **kwargs)
61
62 # Apply UDF and add results to the session
---> 63 for y in udf.apply(x, **kwargs):
64
65 # Uf UDF has a reduce step, this will take care of the insert; else add to session

/lfs/raiders7/ssd/bradenjh/snorkel/snorkel/candidates.pyc in apply(self, context, clear, split, check_for_existing, **kwargs)
266 for key, value in candidate_args.items():
267 q = q.where(getattr(self.candidate_class, key) == value)
--> 268 candidate_id = self.session.execute(q).first()
269 if candidate_id is not None:
270 continue

/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.pyc in execute(self, clause, params, mapper, bind, **kw)
1105
1106 return self._connection_for_bind(
-> 1107 bind, close_with_result=True).execute(clause, params or {})
1108
1109 def scalar(self, clause, params=None, mapper=None, bind=None, **kw):

/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.pyc in execute(self, object, *multiparams, **params)
943 raise exc.ObjectNotExecutableError(object)
944 else:
--> 945 return meth(self, multiparams, params)
946
947 def _execute_function(self, func, multiparams, params):

/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.pyc in _execute_on_connection(self, connection, multiparams, params)
261 def _execute_on_connection(self, connection, multiparams, params):
262 if self.supports_execution:
--> 263 return connection._execute_clauseelement(self, multiparams, params)
264 else:
265 raise exc.ObjectNotExecutableError(self)

/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.pyc in _execute_clauseelement(self, elem, multiparams, params)
1051 compiled_sql,
1052 distilled_params,
-> 1053 compiled_sql, distilled_params
1054 )
1055 if self._has_events or self.engine._has_events:

/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.pyc in _execute_context(self, dialect, constructor, statement, parameters, *args)
1187 parameters,
1188 cursor,
-> 1189 context)
1190
1191 if self._has_events or self.engine._has_events:

/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.pyc in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
1391 util.raise_from_cause(
1392 sqlalchemy_exception,
-> 1393 exc_info
1394 )
1395 else:

/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.pyc in raise_from_cause(exception, exc_info)
200 exc_type, exc_value, exc_tb = exc_info
201 cause = exc_value if exc_value is not exception else None
--> 202 reraise(type(exception), exception, tb=exc_tb, cause=cause)
203
204 if py3k:

/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.pyc in _execute_context(self, dialect, constructor, statement, parameters, *args)
1180 statement,
1181 parameters,
-> 1182 context)
1183 except BaseException as e:
1184 self._handle_dbapi_exception(

/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.pyc in do_execute(self, cursor, statement, parameters, context)
467
468 def do_execute(self, cursor, statement, parameters, context=None):
--> 469 cursor.execute(statement, parameters)
470
471 def do_execute_no_params(self, cursor, statement, context=None):

DataError: (psycopg2.DataError) invalid input syntax for integer: "D008775"
LINE 3: ...se_id = 15509 AND chemical_disease.chemical_cid = 'D008775' ...
^
[SQL: 'SELECT chemical_disease.id \nFROM chemical_disease, candidate \nWHERE chemical_disease.disease_id = %(disease_id_1)s AND chemical_disease.chemical_cid = %(chemical_cid_1)s AND chemical_disease.chemical_id = %(chemical_id_1)s AND chemical_disease.disease_cid = %(disease_cid_1)s AND candidate.split = %(split_1)s'] [parameters: {'chemical_id_1': 15505, 'disease_cid_1': u'D002386', 'split_1': 0, 'disease_id_1': 15509, 'chemical_cid_1': u'D008775'}]
```

**Comment by bhancock8** [comment]
Looks like changing line 107 in candidate.py to store cids as Strings instead of Integers fixes it. Any reason why cids need to be Integers?

**Comment by henryre** [comment]
Good find, thanks for bringing this up. Looks like it had been passing tests on SQLite but not Postgres. Let me check out the CDR data format, then I can make the change.

**Comment by ajratner** [comment]
Looks like this is already fixed; if not I'll bring it up again when working on CDR tomorrow / next week!

**Comment by subarnas** [comment]
I am trying the latest release (snorkel-0.6.2) and ran into a similar issue. 

Please see error trace below.
Clearing existing...
Running UDF...
^M[=                                       ] 0%^M[=                                       ] 0%Traceback (most recent call last):
  File "cgr.py", line 68, in <module>
    candidate_extractor.apply(sents, split=k)
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/candidates.py", line 186, in apply
    super(PretaggedCandidateExtractor, self).apply(xs, split=split, **kwargs)
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/udf.py", line 43, in apply
    self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/udf.py", line 66, in apply_st
    for y in udf.apply(x, **kwargs):
  File "/DATA/subarna/snorkel/snorkel-0.6.2/snorkel/candidates.py", line 272, in apply
    candidate_id = self.session.execute(q).first()
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/DATA/subarna/anaconda2/envs/py2Env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input syntax for integer: "18609(Tax:10090)"
LINE 3: WHERE chemical_gene.gene_cid = '18609(Tax:10090)' AND chemic...
                                       ^
 [SQL: 'SELECT chemical_gene.id \nFROM chemical_gene, candidate \nWHERE chemical_gene.gene_cid = %(gene_cid_1)s AND chemical_gene.chemical_cid = %(chemical_cid_1)s AND chemical_gene.chemical_id = %(chemical_id_1)s AND candidate.split = %(split_1)s AND chemical_gene.gene_id = %(gene_id_1)s'] [parameters: {'gene_cid_1': u'18609(Tax:10090)', 'chemical_cid_1': u'MESH:C556941', 'split_1': 0, 'gene_id_1': 58, 'chemical_id_1': 57}]

**Comment by ajratner** [comment]
Actually I think this might just be a problem of having an old database where this fix wasn't implemented?
