### ISSUE TITLE
Make all learning code work with `session=None`

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#569]
A lot of the learning code (by design) works just with generic `scipy.sparse` matrices, however some of it--e.g. scoring, hyperparam search--needs a `session` object and will throw an error.

We should just add in some default modes so that these methods can run with `session=None`; this should both be relatively easy *and* super high impact :)!

**Comment by ajratner** [comment]
@henryre we can work on this early next week maybe, if I don't get to myself this weekend

**Comment by henryre** [comment]
If we assume that the candidate/feature input and the label matrix are row-aligned, we really don't need the session at all (correct me if I'm wrong). Seems like a reasonable requirement.

**Comment by ajratner** [comment]
Yes exactly
