### ISSUE TITLE
Annotator results not persisting

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#578]
In the CDR tutorial, the results of the 'apply' function of an Annotator instance don't seem to persist in some circumstances. Here's a sample input/output demonstrating the behavior. Note how many stored elements L_train has before and after L_dev is calculated. It happens for both single threaded and multi threaded execution.

![image](https://cloud.githubusercontent.com/assets/12646092/23634062/49ab89aa-027d-11e7-84f9-32986abe6f1b.png)

**Comment by henryre** [comment]
Hey @bhancock8, did you try using `apply_existing` for `L_dev` so that the key set isn't overwritten? What labels are these?

**Comment by henryre** [comment]
Ignore my previous comment. Let me see if I can reproduce this.

**Comment by bhancock8** [comment]
The notebook I've been working in is the CDR tutorial. I don't think this particular flow ever happens in the tutorial (where you use train, then dev, then train again) in its current form.

**Comment by henryre** [comment]
Jk, unignore my previous comments. It should be 

```
L_dev = labeler.apply_existing(split=1)
```

As it is now, calling `labeler.apply(split=1)` clears the labels for all splits. It just happens to work find because, as you noted, the workflow doesn't reload any LF matrices. I'll leave this open until I change the syntax in the tutorial.

**Comment by bhancock8** [comment]
Ah, perfect. It's working just fine now with that little '_existing' in there. Thanks!
