### ISSUE TITLE
CandidateExtractor not returning Ngram subspans

### ISSUE THREAD

**Issue by elboy** [HazyResearch/snorkel#583]
Calling CandidateExtractor.apply() with Ngrams(n_max) as the candidate space only returns candidates that are n-grams of length == n_max. The bug I'm reporting is that CandidateExtractor.apply() should return candidates that are n-grams of length <= n_max. As a feature request, it would be great to be able to pass in a range of indices and extract all candidates that are n-grams in that range.

====================
Reproducing the bug:
```
    ngrams         = Ngrams(n_max=3)
    my_matcher = MyRegexMatcher()
    cand_extractor = CandidateExtractor(candidate, 
                                        [ngrams], 
                                        [my_matcher],
                                        symmetric_relations=False)
    cand_extractor.apply(sentences, split=0)

    # train_candidates will only contain 3-grams. will not contain 1-grams or 2-grams
    train_candidates = session.query(candidate).filter(candidate.split == 0)
```
I have written a small program that reproduces the bug. I can send to Alex or pull request if it would be helpful. 

=====================
Discoveries: 
- I found the bug:
    on line 68 of /snorkel/matchers.py
```
            if self.f(c) and (not self.longest_match_only or not any([self._is_subspan(c, s) for s in seen_spans])):
                if self.longest_match_only:
                    seen_spans.add(self._get_span(c))
                yield c
```

1-grams and 2-grams won't be returned because of the check self._is_subspan(c, s). 1/2-grams are      subspans of 3-grams. I changed matchers.py to just check if c is in seen_spans, rather than if c _is_subspan of a span in seen_spans, and the candidate extractor works as expected, returning all 1-grams, 2-grams, and 3-grams.

- Ngrams seems to be working:
    Played around with Ngrams class in /snorkel/candidates.py and it appears to be functioning as expected.

**Comment by elboy** [comment]
@ajratner

**Comment by ajratner** [comment]
@elboy thanks for posting!!  I'll let you know if we need your code but pretty sure we'll be fine- as you were able to locate, this is just something that used to be a flag (for whether to include non-longest-matches, e.g. subsequences of candidate), and must have gotten dropped.  I think we didn't notice because most people use matchers like `DictionaryMatch` where this is almost always the desired behavior...

Either way will fix soon!

**Comment by ajratner** [comment]
My bad for not answering this properly the first time / the delay in following up: the `longest_match_only` flag is indeed implemented, so here you would just do e.g.:
```
my_matcher = MyRegexMatcher(longest_match_only=False)
```
and then this will work as desired above
