### ISSUE TITLE
Labeling Candidates in the Viewer

### ISSUE THREAD

**Issue by NurzatRakhman** [HazyResearch/snorkel#584]
Hello, 

I labeled candidates in the viewer but cannot access it. In third tutorial, it says use annotator's name as the AnnotationKey. 

![screen shot 2017-03-27 at 5 51 20 pm](https://cloud.githubusercontent.com/assets/7561907/24365660/09606a5a-1317-11e7-92b6-25a5bfabd224.png)
![screen shot 2017-03-27 at 5 51 06 pm](https://cloud.githubusercontent.com/assets/7561907/24365680/0ffb96aa-1317-11e7-88e4-80a41a83b9bd.png) 

Even though I labeled the candidates in the viewer, the resultant matrix of labeled instances is empty.  

Am I accessing labels wrong? 

Appreciate any info. 

Best regards, 
Nurzat

**Comment by ajratner** [comment]
Hi @NurzatRakhman, sorry for the delayed response!  It seems like you're putting in "AnnotationKey" as your annotator name; instead you should use the username for yourself when you made annotations.

By default this will use your username (as returned by `getpass.getuser()`, see https://github.com/HazyResearch/snorkel/blob/master/snorkel/viewer.py#L57), however you can also explicitly pass in an annotator user name when you call sentence viewer, e.g.
```
sv = SentenceNgramViewer(dev_cands, session, annotator_name='Bob')
```

**Comment by NurzatRakhman** [comment]
Thanks Alex, 

sorry for delayed response, it is working  :) 

Best regards, 
Nurzat

**Comment by ajratner** [comment]
Great!
