### ISSUE TITLE
NUL (0x00) characters error in sqlalchemy during parse (intro tutorial)

### ISSUE THREAD

**Issue by thomwolf** [HazyResearch/snorkel#587]
Hi,

I am having an issue running the CoreNLP parser on the intro tutorial.

After a long series of API calls to CoreNLP (seen in the terminal) the ipython script stop with the following NUL character error in sqlalchemy

CoreNLP shows a few warning  like `AVERTISSEMENT: Untokenizable:  (U+E007, decimal: 57351) but generally seems to work.

I use postgresql on a macbook under a python2 environment in conda.

Do you have any hint ?

---------------------------------------------------------------------------

`Clearing existing...
Running UDF...

ValueError                                Traceback (most recent call last)
<ipython-input-3-98edacc8b218> in <module>()
      2 
      3 corpus_parser = CorpusParser()
----> 4 get_ipython().magic(u'time corpus_parser.apply(doc_preprocessor)')

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-59> in time(self, line, cell, local_ns)

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1174         if mode=='eval':
   1175             st = clock2()
-> 1176             out = eval(code, glob, local_ns)
   1177             end = clock2()
   1178         else:

<timed eval> in <module>()

/Users/thomaswolf/Documents/Thomas/Code/HF/snorkel/snorkel/udf.pyc in apply(self, xs, clear, parallelism, progress_bar, count, **kwargs)
     38         print "Running UDF..."
     39         if parallelism is None or parallelism < 2:
---> 40             self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
     41         else:
     42             self.apply_mt(xs, parallelism, clear=clear, **kwargs)

/Users/thomaswolf/Documents/Thomas/Code/HF/snorkel/snorkel/udf.pyc in apply_st(self, xs, progress_bar, count, **kwargs)
     70 
     71         # Commit session and close progress bar if applicable
---> 72         udf.session.commit()
     73         if pb:
     74             pb.bar(n)

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/session.pyc in commit(self)
    872                 raise sa_exc.InvalidRequestError("No transaction is begun.")
    873 
--> 874         self.transaction.commit()
    875 
    876     def prepare(self):

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/session.pyc in commit(self)
    459         self._assert_active(prepared_ok=True)
    460         if self._state is not PREPARED:
--> 461             self._prepare_impl()
    462 
    463         if self._parent is None or self.nested:

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/session.pyc in _prepare_impl(self)
    439                 if self.session._is_clean():
    440                     break
--> 441                 self.session.flush()
    442             else:
    443                 raise exc.FlushError(

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/session.pyc in flush(self, objects)
   2137         try:
   2138             self._flushing = True
-> 2139             self._flush(objects)
   2140         finally:
   2141             self._flushing = False

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/session.pyc in _flush(self, objects)
   2257         except:
   2258             with util.safe_reraise():
-> 2259                 transaction.rollback(_capture_exception=True)
   2260 
   2261     def bulk_save_objects(

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.pyc in __exit__(self, type_, value, traceback)
     58             exc_type, exc_value, exc_tb = self._exc_info
     59             self._exc_info = None   # remove potential circular references
---> 60             compat.reraise(exc_type, exc_value, exc_tb)
     61         else:
     62             if not compat.py3k and self._exc_info and self._exc_info[1]:

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/session.pyc in _flush(self, objects)
   2221             self._warn_on_events = True
   2222             try:
-> 2223                 flush_context.execute()
   2224             finally:
   2225                 self._warn_on_events = False

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.pyc in execute(self)
    382                 while set_:
    383                     n = set_.pop()
--> 384                     n.execute_aggregate(self, set_)
    385         else:
    386             for rec in topological.sort(

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.pyc in execute_aggregate(self, uow, recs)
    640                              [self.state] +
    641                              [r.state for r in our_recs],
--> 642                              uow)
    643 
    644     def __repr__(self):

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/persistence.pyc in save_obj(base_mapper, states, uowtransaction, single)
    179         _emit_insert_statements(base_mapper, uowtransaction,
    180                                 cached_connections,
--> 181                                 mapper, table, insert)
    182 
    183     _finalize_insert_update_commands(

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/orm/persistence.pyc in _emit_insert_statements(base_mapper, uowtransaction, cached_connections, mapper, table, insert, bookkeeping)
    797 
    798             c = cached_connections[connection].\
--> 799                 execute(statement, multiparams)
    800 
    801             if bookkeeping:

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/base.pyc in execute(self, object, *multiparams, **params)
    943             raise exc.ObjectNotExecutableError(object)
    944         else:
--> 945             return meth(self, multiparams, params)
    946 
    947     def _execute_function(self, func, multiparams, params):

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/sql/elements.pyc in _execute_on_connection(self, connection, multiparams, params)
    261     def _execute_on_connection(self, connection, multiparams, params):
    262         if self.supports_execution:
--> 263             return connection._execute_clauseelement(self, multiparams, params)
    264         else:
    265             raise exc.ObjectNotExecutableError(self)

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/base.pyc in _execute_clauseelement(self, elem, multiparams, params)
   1051             compiled_sql,
   1052             distilled_params,
-> 1053             compiled_sql, distilled_params
   1054         )
   1055         if self._has_events or self.engine._has_events:

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/base.pyc in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1187                 parameters,
   1188                 cursor,
-> 1189                 context)
   1190 
   1191         if self._has_events or self.engine._has_events:

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/base.pyc in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1394                 )
   1395             else:
-> 1396                 util.reraise(*exc_info)
   1397 
   1398         finally:

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/base.pyc in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1157                         statement,
   1158                         parameters,
-> 1159                         context)
   1160             elif not parameters and context.no_parameters:
   1161                 if self.dialect._has_events:

/Users/thomaswolf/anaconda/envs/python2/lib/python2.7/site-packages/sqlalchemy/engine/default.pyc in do_executemany(self, cursor, statement, parameters, context)
    465 
    466     def do_executemany(self, cursor, statement, parameters, context=None):
--> 467         cursor.executemany(statement, parameters)
    468 
    469     def do_execute(self, cursor, statement, parameters, context=None):

ValueError: A string literal cannot contain NUL (0x00) characters.

`

**Comment by thomwolf** [comment]
To be precise, the intro tutorial works with SQLite but not PostgreSQL in my case

**Comment by ajratner** [comment]
Hi @thomwolf,

So it seems that Postgres doesn't allow these characters (e.g. see http://stackoverflow.com/questions/28813409/are-null-bytes-allowed-in-unicode-strings-in-postgresql-via-python/28816294#28816294, or https://www.postgresql.org/docs/9.2/static/functions-string.html).  But I'm confused as to where this is coming from; are you just running the basic tutorial, or did you modify any of the data?

**Comment by thomwolf** [comment]
Hi, thanks for the reply.
I was just following the intro tutorial and uncommented the line `os.environ['SNORKELDB'] = 'postgres:///snorkel-intro'` to test it (and installed psycopg2 as requested)
The directory comes straight from a `git clone`

**Comment by uenewsar** [comment]
I got the same error message that tells `ValueError: A string literal cannot contain NUL (0x00) characters.` when I enable `os.environ['SNORKELDB'] = 'postgres:///snorkel-intro'`.

In addition, when I deleted all non-ascii characters from `data/articles.tsv`, this error message did not happen.

**Comment by jason-fries** [comment]
CoreNLP will sometimes insert non-breaking characters into parsed text. You can disable this now by forcing strict Penn TreeBank parsing as follows:
```
corpus_parser = CorpusParser(strict_ptb=True)
corpus_parser.apply(doc_preprocessor, parallelism=10)
```
You may still have to scrub input documents, but this fixed some issues for us.

**Comment by henryre** [comment]
Quick note: the functionality @jason-fries mentioned has been temporarily removed, but should be restored soon

**Comment by arjasethan1** [comment]
Even  I have the same issue .. when I tried this

corpus_parser = CorpusParser(strict_ptb=True)
corpus_parser.apply(doc_preprocessor, parallelism=10)

I got this error 

TypeError                                 Traceback (most recent call last)
<ipython-input-8-b2253a454f6f> in <module>()
      1 from snorkel.parser import CorpusParser
      2 
----> 3 corpus_parser = CorpusParser(strict_ptb=True)
      4 #%time corpus_parser.apply(doc_preprocessor)
      5 corpus_parser.apply(doc_preprocessor, parallelism=10)

TypeError: __init__() got an unexpected keyword argument 'strict_ptb'

**Comment by henryre** [comment]
@arjasethan1 see the note above. The `strict_ptb` option will be restored soon.

**Comment by jason-fries** [comment]
The recent parser refactor should fix this issue.

**Comment by ajratner** [comment]
@jason-fries @henryre What's the status here?

**Comment by MattMorgis** [comment]
For anyone who runs into this, if the `strict_ptb` option is still disabled, I ran the following command to remove all non-ASCII characters from `data/articles.tsv`.

```perl
perl -pi -e 's/[^[:ascii:]]//g' filename
```

Additionally, I used this to run it in parallel with Postgresql:

```python
from snorkel.parser import CorpusParser

corpus_parser = CorpusParser()
%time corpus_parser.apply(doc_preprocessor, parallelism=20)
```

**Comment by ajratner** [comment]
Thanks for noting this!

**Comment by jason-fries** [comment]
Hi @MattMorgis,

The `strict_ptb` functionality is actually implemented -- we just removed the shortcut parameter. You just need to manually initialize the annotator options as follows:


```
annotators=['tokenize', 'ssplit', 'pos', 'lemma', 'depparse', 'ner']
annotator_opts = {}
annotator_opts['tokenize'] = {"invertible": True,
                              "normalizeFractions": False,
                              "normalizeParentheses": False,
                              "normalizeOtherBrackets": False,
                              "normalizeCurrency": False,
                              "asciiQuotes": False,
                              "latexQuotes": False,
                              "ptb3Ellipsis": False,
                              "ptb3Dashes": False,
                              "escapeForwardSlashAsterisk": False,
                              "strictTreebank3": True}

corenlp_server = StanfordCoreNLPServer(annotators=annotators, 
                                       annotator_opts=annotator_opts,
                                       version="3.6.0", num_threads=4)
corpus_parser = CorpusParser(corenlp_server)
corpus_parser.apply(doc_preprocessor, parallelism=1)
```
