### ISSUE TITLE
Add Tika to tutorials

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#593]
Either add blurb to existing intro tutorial, or make new tutorial!

**Comment by thammegowda** [comment]
@ajratner  👍  happy to collaborate on the tutorial.

If we don't want to disturb existing intro tutorial, we can start a new one!

**Comment by ajratner** [comment]
Great!  Also can brainstorm with the folks working on Snorkel for semi-structured data as we discussed @SenWu @xiao-cheng @lukehsiao @bhancock8

**Comment by thammegowda** [comment]
Sounds good. 

In #591 we are using Tika in its default settings where it extracts human readable text content without caring much about the structure.
For semi-structured extraction, Tika has  XHTML Handler.

Please include me in discussions (mailing list ? slack channel? both works for me)

**Comment by ajratner** [comment]
Will definitely do!
