### ISSUE TITLE
No module named psycopg2

### ISSUE THREAD

**Issue by arjasethan1** [HazyResearch/snorkel#597]
I got an error when trying to run the first cell in the tutorial 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-92bf8fd6b0b5> in <module>()
      8 os.environ['SNORKELDB'] = 'postgres:///snorkel-intro'
      9 
---> 10 from snorkel import SnorkelSession
     11 session = SnorkelSession()
     12 

/Users/arjasethan/OpenSource/snorkel/snorkel/__init__.py in <module>()
----> 1 from .models import SnorkelSession
      2 
      3 __version__ = 0.5

/Users/arjasethan/OpenSource/snorkel/snorkel/models/__init__.py in <module>()
     36     import snorkel.models
     37 """
---> 38 from .meta import SnorkelBase, SnorkelSession, snorkel_engine, snorkel_postgres
     39 from .context import Context, Document, Sentence, TemporarySpan, Span
     40 from .context import construct_stable_id, split_stable_id

/Users/arjasethan/OpenSource/snorkel/snorkel/models/meta.py in <module>()
     41 # We initialize the engine within the models module because models' schema can depend on
     42 # which data types are supported by the engine
---> 43 SnorkelSession = new_sessionmaker()
     44 snorkel_engine = SnorkelSession.kw['bind']
     45 

/Users/arjasethan/OpenSource/snorkel/snorkel/models/meta.py in new_sessionmaker()
     30     # open, multiple processes, etc.
     31     if snorkel_postgres:
---> 32         snorkel_engine = create_engine(snorkel_conn_string, isolation_level="AUTOCOMMIT")
     33     else:
     34         snorkel_engine = create_engine(snorkel_conn_string)

/Users/arjasethan/OpenSource/anaaconda2/lib/python2.7/site-packages/sqlalchemy/engine/__init__.pyc in create_engine(*args, **kwargs)
    385     strategy = kwargs.pop('strategy', default_strategy)
    386     strategy = strategies.strategies[strategy]
--> 387     return strategy.create(*args, **kwargs)
    388 
    389 

/Users/arjasethan/OpenSource/anaaconda2/lib/python2.7/site-packages/sqlalchemy/engine/strategies.pyc in create(self, name_or_url, **kwargs)
     78                 if k in kwargs:
     79                     dbapi_args[k] = pop_kwarg(k)
---> 80             dbapi = dialect_cls.dbapi(**dbapi_args)
     81 
     82         dialect_args['dbapi'] = dbapi

/Users/arjasethan/OpenSource/anaaconda2/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.pyc in dbapi(cls)
    552     @classmethod
    553     def dbapi(cls):
--> 554         import psycopg2
    555         return psycopg2
    556 

ImportError: No module named psycopg2

**Comment by henryre** [comment]
Hi @arjasethan1, it looks like you don't have `psycopg2` installed. If you're using pip, you can do 
```
pip install psycopg2
```
from your shell command line.
