### ISSUE TITLE
How to understand this Probability Distribution in zhang's paper?

### ISSUE THREAD

**Issue by eromoe** [HazyResearch/snorkel#600]
Hi,

I am reading [DeepDive: A Data Management System for
Automatic Knowledge Base Construction][1]. From there how they define the Probability Distribution is especially hard to me.

1. In page 26,

    > Given a possible world Iσ, for any t = (f id, v1, . . . , vaj) ∈ Fj , define gj (t, Iσ)= wjfj (σ(v1), . . . , σ(vaj)), vars(f id) = {v1, . . . , vaj }.

    I can't understand above three definition , what's their meanings?? 

2. How and why do them define Probability Distribution like this? 
   
    [![enter image description here][3]][3]

The things I known:

- Σ: add up all 
- exp(n): n power of natural base e 
- normal distribution can use to present system error rate, but here I don't see normal distribution. Just use exp(xxx) can stand for a probability distribution ?

Just add up all `gj`, and use the add up as power of nature base e would show the probability ? Completely can't understand....

  [1]: https://cs.stanford.edu/people/czhang/zhang.thesis.pdf
  [2]: https://i.stack.imgur.com/AYyAy.png
  [3]: https://i.stack.imgur.com/JhjnT.png

**Comment by ajratner** [comment]
Hi @eromoe ,

That section is describing a [factor graph](http://deepdive.stanford.edu/inference), which consists of a set of factor functions, variables which are the arguments of these factor functions, and weights for each factor.  Z is then the exp of the weighted sum of the factor functions for some "possible world" i.e. assignment of the variables, and some set of learned.  This is then normalized (2.2) to get a valid probability for this possible world / variable assignment.

Snorkel uses a specific class of factor graphs to represent the generative model used for denoising labeling functions!  However the above is more relevant to DeepDive, so I would direct further questions there: https://github.com/HazyResearch/deepdive

Closing this issue for now; thanks for the questions!
