### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by fsonntag** [HazyResearch/snorkel#602]
Hey,
I wanted to ask if you are open for Python 3 compatibility. I've already made it running for me locally. After some further checks if it's still compatible with Python 2.7, I could do a PR 🙂

**Comment by ajratner** [comment]
Hey @fsonntag,

We probably will not extend for Python 3 compatibility if it adds any non-negligible overhead to the codebase, as Snorkel is still an in-development research project and we value keeping things (somewhat) simple :)

However, if you are close to a PR, we'd love to see it and if the changes required are fairly lightweight, we might be open!

And either way, thanks so much for your help here!!

-Alex

**Comment by jonathan-zageno** [comment]
@fsonntag I would encourage a PR :)

**Comment by jonathan-s** [comment]
@fsonntag I would encourage a PR

**Comment by ajratner** [comment]
Check to make sure we didn't break anything with the big merge we just did from dev into master, but closing this for now- thanks for all the great help here!

**Comment by AndriiNeverov** [comment]
Seems like text.decode('string_escape', errors='ignore') has been introduced in a few places since and it doesn't work with python3

**Comment by chrismre** [comment]
+1 for Python3 compatibility.
