### ISSUE TITLE
Several Errors in Running a CorpusParser of Intro_Tutorial_1

### ISSUE THREAD

**Issue by KevinChung70** [HazyResearch/snorkel#617]
Hi,
While I was running a CorpusParser in Intro_Tutorial_1, I got the following errors.
Would you please let me know how to resolve it?

Besides, I think it would be nicer if the data used in Tutorials are simpler (such as metric data).
I'm interested in Tutorial 4 and 5 only, but I have to resolve all the text-processing-related issues first in order to run the two Turorials.

Thanks!
Sangoh.

=========================================================================
from snorkel.parsers import CorpusParser

corpus_parser = CorpusParser()
%time corpus_parser.apply(doc_preprocessor)

Clearing existing...
Running UDF...

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-4-dbf7dddf60f1> in <module>()
      2 
      3 corpus_parser = CorpusParser()
----> 4 get_ipython().magic(u'time corpus_parser.apply(doc_preprocessor)')

/home/sangoh/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/home/sangoh/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-59> in time(self, line, cell, local_ns)

/home/sangoh/anaconda2/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/home/sangoh/anaconda2/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1174         if mode=='eval':
   1175             st = clock2()
-> 1176             out = eval(code, glob, local_ns)
   1177             end = clock2()
   1178         else:

<timed eval> in <module>()

/home/sangoh/snorkel/snorkel/udf.pyc in apply(self, xs, clear, parallelism, progress_bar, count, **kwargs)
     38         print "Running UDF..."
     39         if parallelism is None or parallelism < 2:
---> 40             self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
     41         else:
     42             self.apply_mt(xs, parallelism, clear=clear, **kwargs)

/home/sangoh/snorkel/snorkel/udf.pyc in apply_st(self, xs, progress_bar, count, **kwargs)
     61 
     62             # Apply UDF and add results to the session
---> 63             for y in udf.apply(x, **kwargs):
     64 
     65                 # Uf UDF has a reduce step, this will take care of the insert; else add to session

/home/sangoh/snorkel/snorkel/parsers/doc_preprocessors.pyc in apply(self, x, **kwargs)
     47         """Given a Document object and its raw text, parse into processed Sentences"""
     48         doc, text = x
---> 49         for parts in self.req_handler.parse(doc, text):
     50             parts = self.fn(parts) if self.fn is not None else parts
     51             yield Sentence(**parts)

/home/sangoh/snorkel/snorkel/parsers/corenlp.pyc in parse(self, document, text, conn)
    215             blocks = json.loads(content, strict=False)['sentences']
    216         except:
--> 217             warnings.warn("CoreNLP skipped a malformed sentence.\n{}".format(text), RuntimeWarning)
    218             return
    219 

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 17: ordinal not in range(128)

**Comment by SofianHamiti** [comment]
I have the same issue

**Comment by jason-fries** [comment]
Hi @KevinChung70 and @SofianHamiti -- pull the latest commit and this bug should be fixed. Let us know if you have any other issues. Thanks!
