### ISSUE TITLE
Candidates missing in the viewer

### ISSUE THREAD

**Issue by JoMynta** [HazyResearch/snorkel#620]
My candidates consist of a relation between a person and a number. So if I have 3 persons and 4 numbers in a sentence, I would expect there to be 12 candidates. Unfortunately the viewer didn't let me label all 12 combinations, only some of them. All persons and numbers were marked yellow, so all of them were at least part of one relation. When I deleted the database and started again, the viewer let me label different candidates than before, but again some were missing. Do you have an idea why that happens?

**Comment by ajratner** [comment]
Hi @JoMynta sorry for the delayed response!

A few questions:
* Are the relation mentions in the same sentence (by default we only extract intra-sentence candidates)?
* If you get the length of the candidate set you're feeding into the viewer, is it 12 (i.e. is this a Viewer issue or an extractor issue)?

If you have a code snippet / example notebook that's helpful too!

Thanks,
Alex

**Comment by JoMynta** [comment]
Hi Alex,

- the relation mentions are in the same sentence
- the NER labels the numbers as numbers and the persons as persons
- the problem is not in the viewer but with candidate extraction, the viewer shows all candidates that are extracted
- if I delete the database and run the notebook again, I get different candidates, although there seems to be a pattern

This is my test sentence and the candidates I get:


> This is a test sentence including Joe Brown, age 40, and his wife Jane, 35, and their daughter Mary (7), and an additional number 12.

First run:
> Age(Span("Joe Brown", sentence=2, chars=[34,42], words=[6,7]), Span("40", sentence=2, chars=[49,50], words=[10,10]))
Age(Span("Joe Brown", sentence=2, chars=[34,42], words=[6,7]), Span("12", sentence=2, chars=[130,131], words=[31,31]))
Age(Span("Joe Brown", sentence=2, chars=[34,42], words=[6,7]), Span("35", sentence=2, chars=[72,73], words=[17,17]))
Age(Span("Joe Brown", sentence=2, chars=[34,42], words=[6,7]), Span("7", sentence=2, chars=[101,101], words=[24,24]))
Age(Span("Jane", sentence=2, chars=[66,69], words=[15,15]), Span("12", sentence=2, chars=[130,131], words=[31,31]))
Age(Span("Jane", sentence=2, chars=[66,69], words=[15,15]), Span("35", sentence=2, chars=[72,73], words=[17,17]))
Age(Span("Jane", sentence=2, chars=[66,69], words=[15,15]), Span("7", sentence=2, chars=[101,101], words=[24,24]))
Age(Span("Mary", sentence=2, chars=[95,98], words=[22,22]), Span("35", sentence=2, chars=[72,73], words=[17,17]))
Age(Span("Mary", sentence=2, chars=[95,98], words=[22,22]), Span("7", sentence=2, chars=[101,101], words=[24,24]))

Second run:

> Age(Span("Jane", sentence=2, chars=[66,69], words=[15,15]), Span("35", sentence=2, chars=[72,73], words=[17,17]))
Age(Span("Jane", sentence=2, chars=[66,69], words=[15,15]), Span("7", sentence=2, chars=[101,101], words=[24,24]))
Age(Span("Jane", sentence=2, chars=[66,69], words=[15,15]), Span("40", sentence=2, chars=[49,50], words=[10,10]))
Age(Span("Jane", sentence=2, chars=[66,69], words=[15,15]), Span("12", sentence=2, chars=[130,131], words=[31,31]))
Age(Span("Mary", sentence=2, chars=[95,98], words=[22,22]), Span("7", sentence=2, chars=[101,101], words=[24,24]))
Age(Span("Mary", sentence=2, chars=[95,98], words=[22,22]), Span("40", sentence=2, chars=[49,50], words=[10,10]))
Age(Span("Mary", sentence=2, chars=[95,98], words=[22,22]), Span("12", sentence=2, chars=[130,131], words=[31,31]))
Age(Span("Joe Brown", sentence=2, chars=[34,42], words=[6,7]), Span("40", sentence=2, chars=[49,50], words=[10,10]))
Age(Span("Joe Brown", sentence=2, chars=[34,42], words=[6,7]), Span("12", sentence=2, chars=[130,131], words=[31,31]))

I also attached the notebook to this example:
[joebrownexample.zip](https://github.com/HazyResearch/snorkel/files/1040865/joebrownexample.zip)

**Comment by ajratner** [comment]
Hi @JoMynta thanks so much for the notebook and for pointing this out!  Merging in a fix as soon as passes review.  In mean time, note you can also sidestep this bug by setting `symmetric_relations=True`.

Sorry for the trouble with this!
