### ISSUE TITLE
Short Tutorial on Adding Custom Factors with Numbskull

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#632]
Can we put together a simple tutorial on adding custom factors for Numbskull?
- [ ] here's a checkbox for @ajratner 
- [ ] and one for @bryan-he

**Comment by ajratner** [comment]
Love the check boxes :) . I actually think @thodrek is doing this right now!

**Comment by ajratner** [comment]
Going to close this for now based on conversation today- I think it's better if this goes in the Numbskull repo perhaps?
