### ISSUE TITLE
Compliance with 80 character width in all files

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#636]
Per PEP-8 :)

**Comment by henryre** [comment]
Low priority?

**Comment by chrismre** [comment]
@henryre ... now it's both low and high priority, to accurately capture both the world's and @ajratner's feelings about it.

**Comment by ajratner** [comment]
You guys can fight me in the comments- I'm focused on winning the ground war.  One passive-aggressive commit at a time...

**Comment by ajratner** [comment]
My noble fight has come to an end.
