### ISSUE TITLE
Not an issue, just a question: How do i load preprocessed (by NLP) TSV file to database?

### ISSUE THREAD

**Issue by cognitronz** [HazyResearch/snorkel#645]
I am trying to use the pre-parsed TSV file from the DD's data repository.  How do I load this data to PSQL database?  The examples on the notebook are not quite complete.

**Comment by cognitronz** [comment]
I found this to be rather useful in DeepDive.  Is there something like this in Snorkel?
![image](https://cloud.githubusercontent.com/assets/6811782/26611832/c84e0dc0-4565-11e7-8e03-68cb4fa818b9.png)

**Comment by ajratner** [comment]
Hi @cognitronz ,

The main difference in Snorkel, as far as raw data representation goes, is that now raw input data is represented as a hierarchy of `Context` objects.  In the default case right now, just `Document`s and `Sentence`s.

So to load data like this in, you'd first need to create a `Document` object for each doc_id in the TSV file.  E.g. something like
```python
docs = {}
for doc_id in doc_ids:
    docs[doc_id] = Document(name=doc_id, stable_id=doc_id)
```

Then, you would add the sentences, and add these to the DB session (which will also add the docs); something like:
```python
for s in tsv_sents:
    session.add(Sentence(
        document=docs[s['doc_id']],
        position=s['sentence_index'],
        text=s['sentence_text'],
        words=s['tokens'],
        ...
    ))
session.commit()
```

One issue is that Snorkel keeps track of things using character-level offsets _relative to the sentence start_ (and stores the sentence absolute offsets in the stable_id, see e.g. [here](https://github.com/HazyResearch/snorkel/blob/master/snorkel/parser/corenlp.py#L277)) so would need to do some conversion here.  And then `dep_types = dep_labels` and `dep_tokens = dep_parents`.

Of course, this might not be the most efficient way to load in data by any means, but is fairly straight forward.  Hope this helps!

**Comment by ajratner** [comment]
Closing for now but feel free to reopen- will try to clean up + add something like the above to a tutorial in #647
