### ISSUE TITLE
naming the database

### ISSUE THREAD

**Issue by sangha123** [HazyResearch/snorkel#665]
I had been using,
os.environ["SNORKELDB"]="sqlite:///test_name1.0.db"
session = SnorkelSession()

for naming databases. Currently snorkel is not taking the environment name and defaulting to snorkel.db. What is a good way to fix this?

**Comment by stephenbach** [comment]
Hi!

Can you post the broader context? The environment variable needs to be set before importing Snorkel. (This is because setting up the data model classes requires a connection.)

**Comment by sangha123** [comment]
I think that is the problem. I set the name after importing snorkel. Thank You.
