### ISSUE TITLE
ImportError: cannot import name SnorkelSession

### ISSUE THREAD

**Issue by yanivh** [HazyResearch/snorkel#666]
Hi , 

install using Pip install , result to folder under py2env->Lib->site-packages : snorkel &snorkel-0.0.12.dist-info

from notebook run 
import snorkel                                   - success
from snorkel import SnorkelSession -  cannot import name SnorkelSession

please help !!

thanks 
yaniv

**Comment by stephenbach** [comment]
Hi,

Can you elaborate on the commands you ran? Did you use the README or run `pip install snorkel`. If the latter, that installs a different package, which would explain this behavior.

**Comment by ajratner** [comment]
Closing for now, feel free to re-open!

**Comment by weihua04** [comment]
I have the same problem with you, do your  problem has been resolved?

**Comment by weihua04** [comment]
I have solved this problem. I run in the path of "snorkel-master" with command"./run.sh",then open the web "http://localhost:8888/tree#",and create a new notebooks.that's done! Hope useful to you
