### ISSUE TITLE
StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:12345 taking forever

### ISSUE THREAD

**Issue by ArghyaPal** [HazyResearch/snorkel#667]
Hi,

It seems 
>> `corpus_parser = CorpusParser()`

is taking forever time - though you have mentioned it will take at the max 10 mins..
Here is the output:

`corpus_parser = CorpusParser()
>>> -- listing properties --
port=12345
threads=1
timeout=600000
Starting server on port 12345 with timeout of 600000 milliseconds.
StanfordCoreNLPServer listening at /0:0:0:0:0:0:0:0:12345`

I am running Intro_Tutorial_1.ipynb. Please help..!!

**Comment by ajratner** [comment]
Hi @ArghyaPal ,

Hard for me to know how long it should take without knowing your computer specs, but two things to check:
1. In the shell/terminal where you are running the notebook from, do you see CoreNLP output printing once you start running the parser (besides what you posted above?)
2. In the very first cell, there's an if/then statement which limits the `max_docs` to 50 if the tutorial is being run in automated testing; you could try setting `max_docs` to a similarly small number to see if this runs, which should not take longer than a minute or two

**Comment by ArghyaPal** [comment]
Hi @ajratner , 

Thank you so much for your quick reply. To be more precise:

My Os is: 
Ubuntu 16 (64 bit)
Processor: Intel® Xeon(R) CPU E5620 @ 2.40GHz × 8 
Graphics: Gallium 0.4 on NVA8

I am under Virtualenv, Python 2.7 
I didn't get any issues while doing pip requirement.txt installaition
I am running Intro_Tutoral_1
Cell 3: 
`from snorkel.parser import CorpusParser
corpus_parser = CorpusParser()
%time corpus_parser.apply(doc_preprocessor)
`

Output I get is as below:

`Clearing existing...
Running UDF...

---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
<ipython-input-3-98edacc8b218> in <module>()
      2 
      3 corpus_parser = CorpusParser()
----> 4 get_ipython().magic(u'time corpus_parser.apply(doc_preprocessor)')

/home/arghya/py27_env/local/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2158         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2159         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2160         return self.run_line_magic(magic_name, magic_arg_s)
   2161 
   2162     #-------------------------------------------------------------------------

/home/arghya/py27_env/local/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2079                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2080             with self.builtin_trap:
-> 2081                 result = fn(*args,**kwargs)
   2082             return result
   2083 

<decorator-gen-60> in time(self, line, cell, local_ns)

/home/arghya/py27_env/local/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/home/arghya/py27_env/local/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1179         if mode=='eval':
   1180             st = clock2()
-> 1181             out = eval(code, glob, local_ns)
   1182             end = clock2()
   1183         else:

<timed eval> in <module>()

/home/arghya/snorkel/snorkel/udf.pyc in apply(self, xs, clear, parallelism, progress_bar, count, **kwargs)
     38         print "Running UDF..."
     39         if parallelism is None or parallelism < 2:
---> 40             self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
     41         else:
     42             self.apply_mt(xs, parallelism, clear=clear, **kwargs)

/home/arghya/snorkel/snorkel/udf.pyc in apply_st(self, xs, progress_bar, count, **kwargs)
     61 
     62             # Apply UDF and add results to the session
---> 63             for y in udf.apply(x, **kwargs):
     64 
     65                 # Uf UDF has a reduce step, this will take care of the insert; else add to session

/home/arghya/snorkel/snorkel/parser/corpus_parser.pyc in apply(self, x, **kwargs)
     29         """Given a Document object and its raw text, parse into Sentences"""
     30         doc, text = x
---> 31         for parts in self.req_handler.parse(doc, text):
     32             parts = self.fn(parts) if self.fn is not None else parts
     33             yield Sentence(**parts)

/home/arghya/snorkel/snorkel/parser/corenlp.pyc in parse(self, document, text, conn)
    204         if isinstance(text, unicode):
    205             text = text.encode('utf-8', 'error')
--> 206         resp = conn.post(self.endpoint, data=text, allow_redirects=True)
    207         text = text.decode('utf-8')
    208         content = resp.content.strip()

/home/arghya/py27_env/local/lib/python2.7/site-packages/requests/sessions.pyc in post(self, url, data, json, **kwargs)
    558         """
    559 
--> 560         return self.request('POST', url, data=data, json=json, **kwargs)
    561 
    562     def put(self, url, data=None, **kwargs):

/home/arghya/py27_env/local/lib/python2.7/site-packages/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    511         }
    512         send_kwargs.update(settings)
--> 513         resp = self.send(prep, **send_kwargs)
    514 
    515         return resp

/home/arghya/py27_env/local/lib/python2.7/site-packages/requests/sessions.pyc in send(self, request, **kwargs)
    621 
    622         # Send the request
--> 623         r = adapter.send(request, **kwargs)
    624 
    625         # Total elapsed time of the request (approximately)

/home/arghya/py27_env/local/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    502                 raise ProxyError(e, request=request)
    503 
--> 504             raise ConnectionError(e, request=request)
    505 
    506         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=12345): Max retries exceeded with url: /?properties=%7B%22annotators%22:%20%22tokenize,ssplit,pos,lemma,depparse,ner%22,%22outputFormat%22:%20%22json%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62677bacd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

`



Thank you again,
With Best Regards,
Arghya

**Comment by stephenbach** [comment]
Hi Arghya,

One thing that can cause this is not having CoreNLP installed. Can you confirm it's installed, perhaps by running `install-parser.sh` in the top level directory?

**Comment by ArghyaPal** [comment]
Hi @stephenbach,
Thyank you so much for your reply. 
As per your suggestion I have tried:
`./install-parser.sh`
and I get:

`./install-parser.sh 
--2017-06-16 13:09:46--  http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip
Connecting to 192.168.0.13:3128... connected.
Proxy request sent, awaiting response... 302 Moved Temporarily
Location: https://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip [following]
--2017-06-16 13:09:47--  https://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip
Connecting to 192.168.0.13:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 403157240 (384M) [application/zip]
Saving to: ‘stanford-corenlp-full-2015-12-09.zip.1’

stanford-corenlp-full-2015-12-09.zip.1             100%[================================================================================================================>] 384.48M  1.53MB/s    in 2m 57s  

2017-06-16 13:12:45 (2.17 MB/s) - ‘stanford-corenlp-full-2015-12-09.zip.1’ saved [403157240/403157240]

Archive:  stanford-corenlp-full-2015-12-09.zip
   creating: stanford-corenlp-full-2015-12-09/
  inflating: stanford-corenlp-full-2015-12-09/xom-1.2.10-src.jar  
  inflating: stanford-corenlp-full-2015-12-09/CoreNLP-to-HTML.xsl  
  inflating: stanford-corenlp-full-2015-12-09/README.txt  
  inflating: stanford-corenlp-full-2015-12-09/LIBRARY-LICENSES  
   creating: stanford-corenlp-full-2015-12-09/sutime/
  inflating: stanford-corenlp-full-2015-12-09/sutime/defs.sutime.txt  
  inflating: stanford-corenlp-full-2015-12-09/sutime/english.sutime.txt  
  inflating: stanford-corenlp-full-2015-12-09/sutime/english.holidays.sutime.txt  
 extracting: stanford-corenlp-full-2015-12-09/ejml-0.23-src.zip  
  inflating: stanford-corenlp-full-2015-12-09/input.txt.xml  
  inflating: stanford-corenlp-full-2015-12-09/build.xml  
  inflating: stanford-corenlp-full-2015-12-09/pom.xml  
  inflating: stanford-corenlp-full-2015-12-09/stanford-corenlp-3.6.0.jar  
   creating: stanford-corenlp-full-2015-12-09/tokensregex/
  inflating: stanford-corenlp-full-2015-12-09/tokensregex/color.input.txt  
  inflating: stanford-corenlp-full-2015-12-09/tokensregex/retokenize.txt  
  inflating: stanford-corenlp-full-2015-12-09/tokensregex/color.properties  
  inflating: stanford-corenlp-full-2015-12-09/tokensregex/color.rules.txt  
  inflating: stanford-corenlp-full-2015-12-09/javax.json-api-1.0-sources.jar  
  inflating: stanford-corenlp-full-2015-12-09/protobuf.jar  
  inflating: stanford-corenlp-full-2015-12-09/StanfordDependenciesManual.pdf  
   creating: stanford-corenlp-full-2015-12-09/patterns/
  inflating: stanford-corenlp-full-2015-12-09/patterns/example.properties  
 extracting: stanford-corenlp-full-2015-12-09/patterns/otherpeople.txt  
 extracting: stanford-corenlp-full-2015-12-09/patterns/goldplaces.txt  
  inflating: stanford-corenlp-full-2015-12-09/patterns/stopwords.txt  
  inflating: stanford-corenlp-full-2015-12-09/patterns/presidents.txt  
  inflating: stanford-corenlp-full-2015-12-09/patterns/names.txt  
 extracting: stanford-corenlp-full-2015-12-09/patterns/places.txt  
  inflating: stanford-corenlp-full-2015-12-09/patterns/goldnames.txt  
  inflating: stanford-corenlp-full-2015-12-09/slf4j-simple.jar  
  inflating: stanford-corenlp-full-2015-12-09/input.txt  
  inflating: stanford-corenlp-full-2015-12-09/input.txt.out  
  inflating: stanford-corenlp-full-2015-12-09/joda-time.jar  
  inflating: stanford-corenlp-full-2015-12-09/xom.jar  
  inflating: stanford-corenlp-full-2015-12-09/StanfordCoreNlpDemo.java  
  inflating: stanford-corenlp-full-2015-12-09/stanford-corenlp-3.6.0-sources.jar  
  inflating: stanford-corenlp-full-2015-12-09/slf4j-api.jar  
  inflating: stanford-corenlp-full-2015-12-09/jollyday-0.4.7-sources.jar  
  inflating: stanford-corenlp-full-2015-12-09/ejml-0.23.jar  
  inflating: stanford-corenlp-full-2015-12-09/javax.json.jar  
  inflating: stanford-corenlp-full-2015-12-09/Makefile  
  inflating: stanford-corenlp-full-2015-12-09/stanford-corenlp-3.6.0-models.jar  
  inflating: stanford-corenlp-full-2015-12-09/corenlp.sh  
  inflating: stanford-corenlp-full-2015-12-09/joda-time-2.9-sources.jar  
  inflating: stanford-corenlp-full-2015-12-09/stanford-corenlp-3.6.0-javadoc.jar  
  inflating: stanford-corenlp-full-2015-12-09/jollyday.jar  
  inflating: stanford-corenlp-full-2015-12-09/ShiftReduceDemo.java  
  inflating: stanford-corenlp-full-2015-12-09/SemgrexDemo.java  
  inflating: stanford-corenlp-full-2015-12-09/LICENSE.txt  
`
Is this correct?


With Best Regards,
Arghya.

**Comment by stephenbach** [comment]
Looks right. Does it fix the problem? :)

**Comment by ArghyaPal** [comment]
Hi @stephenbach  sorry to bother you. The problem is still there.
Here is a snapshopt..
![prob](https://user-images.githubusercontent.com/19369111/27237232-fc6c2fe6-52e5-11e7-8de3-e08a3f6477be.png)

Thank you,
With Best Regards,
Arghya

**Comment by ArghyaPal** [comment]
Hi @ajratner  @stephenbach ,
Though I am not sure but could it be possible that the `port 12345` is creating problem. I speculating, this **port 12345** is blocked by my collage. Presently, I am testing it. 


However if it is true (the 12345 is blocked), then may I use any other port? 
Thank you for your quick response all the time,
Regards,
Arghya

**Comment by jason-fries** [comment]
Hi @ArghyaPal

You can run on other ports, just provide your target port as a parameter when initializing the CoreNLP server
```
corenlp_server = StanfordCoreNLPServer(version="3.6.0", num_threads=4, port=12348)
corpus_parser = CorpusParser(corenlp_server)
corpus_parser.apply(doc_preprocessor, parallelism=1)
```

**Comment by ajratner** [comment]
HI @ArghyaPal ,

Hopefully Jason's comment and/or the v0.6 release fixes this; you can also try the new (default) spacy parser and see if that works!  Closing for now but please re-open if still unresolved!

**Comment by gmachiraju** [comment]
@ajratner and @ArghyaPal, what fixed it for me is inspired form the tutorial — there must have been  slight update with from version of Snorkel I was using prior. I just needed to instantiate the CorpusParser with Spacy as the parser param:

`from snorkel.parser.spacy_parser import Spacy
corpus_parser = CorpusParser(parser=Spacy())`

My Connection issue was resolved this way! Best of luck to anyone else who runs into this~

**Comment by ajratner** [comment]
Just as an FYI: This is just switching to using the Spacy parser (which is
a fine solution) but is not a fix to the CoreNLP connection issue
