### ISSUE TITLE
Make version with only LSTM end extractor + "light" CoreNLP?

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#668]
Only need tokens for current LSTM + maybe POS / NER tags for extractors... at least try this for intro tutorial?

**Comment by jason-fries** [comment]
Does this amount to turning off all dependency parsing in CoreNLP? You can specify a specific set of CoreNLP annotators in the new parser class, so it's easy to get a minimal tag set.

**Comment by ajratner** [comment]
Yeah that's what I was thinking... this might be a one line diff in the Intro tutorial.  But I could also see it being pretty easy to make a new even lighter tutorial that doesn't use CoreNLP at all

**Comment by jason-fries** [comment]
I agree. We'd only need to implement / add some light-weight sentence boundary detectior and tokenizer. I guess it might be worth adding a simple, 2 line NLTK parser for this? Sent from Nylas Mail, the best free email app for work
          
            
            On Jun 12 2017, at 12:15 pm, Alex Ratner <notifications@github.com> wrote:
            
            
              Yeah that's what I was thinking... this might be a one line diff in the Intro tutorial.  But I could also see it being pretty easy to make a new even lighter tutorial that doesn't use CoreNLP at all

**Comment by henryre** [comment]
spacy ftw

**Comment by ajratner** [comment]
Yeah exactly; or just `.split()` for a very simple intro tutorial.  Ref splitting up the tutorials, #624 and #634

**Comment by ajratner** [comment]
Spacy could work too.  But I think this is separate- just about making the intro tutorial as fast and simple as possible (maybe spacy tokenizer + LSTM?)
