### ISSUE TITLE
Viewer: Empty Panel upon First Render

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#670]
When instantiating the `SentenceNgramViewer` class from a list of `Candidate` objects, the viewer's first first panel renders as blank
```
from snorkel.viewer import SentenceNgramViewer
SentenceNgramViewer(labeled, session)
```
![empty](https://user-images.githubusercontent.com/348682/27263110-788261ee-5418-11e7-974d-e7dc370caeb8.jpg)

Navigating forward then backward fixes the issue
![filled](https://user-images.githubusercontent.com/348682/27263122-91f0f320-5418-11e7-83e2-9707a291a3c1.jpg)

So some javascript render event isn't firing properly upon init?

**Comment by ajratner** [comment]
@jason-fries I've never had this happen, is this just on the default Spouses tutorial?

**Comment by ajratner** [comment]
Hi @jason-fries can't reproduce this issue in the intro tutorial, where should we look for it?  Maybe just merge everything in and then see if it's still happening after the release?

**Comment by jason-fries** [comment]
I just tested this again on the public AWS instance and I can reproduce the error on:

_Google Chrome_  59.0.3071.115 (Official Build) (64-bit)
_Firefox_ 54.0.1  (64-bit) 
_Safari_ 10.1.1 (10603.2.5)

See Slack for the connection information to test on your machine :)
