### ISSUE TITLE
quering data labelled in the viewer

### ISSUE THREAD

**Issue by sangha123** [HazyResearch/snorkel#674]
Is it possible to query the data that has been labelled from the viewer?

**Comment by ajratner** [comment]
Yes, the annotations you make in the `Viewer` are stored as [`GoldLabel`](https://github.com/HazyResearch/snorkel/blob/master/snorkel/models/annotation.py#L103) objects, in the `gold_label` table of the database.  You can write a query joining these with the `Candidate` objects (or the candidate subclass you defined) that they label.  Hope this helps!
