### ISSUE TITLE
Warning not error: This call to matplotlib.use() has no effect because the backend has already been chosen?

### ISSUE THREAD

**Issue by hiber-niu** [HazyResearch/snorkel#677]
When I executed following code
```
import re
from snorkel.lf_helpers import (
    get_left_tokens, get_right_tokens, get_between_tokens,
    get_text_between, get_tagged_text,
)
```
the code will throw this 

> warning: /usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect because the backend has already been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot, or matplotlib.backends is imported for the first time.    warnings.warn(_use_error_msg)

**Comment by ajratner** [comment]
Hi @hiber-niu that's just a harmless warning, you can completely ignore it!

That being said, this is annoying, so we can leave this open and we'll fix soon- thanks for pointing out

**Comment by stephenbach** [comment]
Not able to recreate this error on `new_intro` branch.

Running
```
import matplotlib.pyplot as plt
plt.hist([1, 2, 3, 4], bins=20)
plt.show()

import re
from snorkel.lf_helpers import (
    get_left_tokens, get_right_tokens, get_between_tokens,
    get_text_between, get_tagged_text,
)
```
doesn't produce the warning. The imports in lf_helpers haven't changed, but it's possible something deeper in the import DAG did.

Closing for now. If someone sees it again, we need to identify what's calling `matplotlib.use()`.
