### ISSUE TITLE
Disable the StableLable Table

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#684]
Yes, this is a shock to the system to even think about.

However, the only rationale for having this table is to make sure that human annotations created in the `Viewer` are saved in some format that references stable_ids.  However, as we transition away from using the `Viewer` for labeling and move to BRAT / loading in external annotations, we shouldn't need this anymore.

Getting rid of this table will not only simplify code a lot but will also get rid of a massive slowdown in loading external annotations

**Comment by ajratner** [comment]
@stephenbach should we close this (and #545)?

**Comment by stephenbach** [comment]
Yes.
