### ISSUE TITLE
Add "smart" Viewer sampling

### ISSUE THREAD

**Issue by henryre** [HazyResearch/snorkel#69]
Rather than a fully random sample, do we want
- Some all-abstained candidates?
- Some high conflict candidates?
- Some low conflict candidates?
- Some candidates with probability close to 0.5?

**Comment by ajratner** [comment]
This should now be easier to do with `Viewer`, however we could still have some nice default methods as listed, so will leave open

**Comment by ajratner** [comment]
+ class-balanced (as in #195)

**Comment by henryre** [comment]
Any updates?

**Comment by jason-fries** [comment]
I bet [elastic search](https://www.elastic.co/) could help here 💯
