### ISSUE TITLE
Not an Issue just a query

### ISSUE THREAD

**Issue by ArghyaPal** [HazyResearch/snorkel#709]
Hi, Thank you for your new version. It's now working fine. I have a query regarding your **crowdsourcing.ipynb**. Question is:

It is not very clear to me, what is a `Candidate`, a `Context`, and a `Label`. For example, if I have the following: (I am assuming **labeling function** as **crowd worker**)

   Tweet_1 +ve for labeling_function_1, 
   Tweet_1 -ve for labeling_function_2,
   Tweet_1 +ve for labeling_function_3, 
   Tweet_1 -ve for labeling_function_4,

   Tweet_2 -ve for labeling_function_1, 
   Tweet_2 -ve for labeling_function_2,
   Tweet_2 -ve for labeling_function_3, 
   Tweet_2 -ve for labeling_function_4,

   Tweet_3 +ve for labeling_function_1, 
   Tweet_3 +ve for labeling_function_2,
   Tweet_3 +ve for labeling_function_3, 
   Tweet_3 -ve for labeling_function_4,

   Tweet_4 -ve for labeling_function_1, 
   Tweet_4 -ve for labeling_function_2,
   Tweet_4 -ve for labeling_function_3, 
   Tweet_4 -ve for labeling_function_4,

then what is a  `Candidate`, a `Context`, and a `Label`?

Thank you,
Arghya

**Comment by ajratner** [comment]
Hi @ArghyaPal ,

Good questions- this is not the same exact setup as in the Intro tutorial but shows off some of Snorkel's flexibility. Here the `Candidate` is a tweet, the `Context` is the body text of the tweet, and the `Label` is the label from the task- see the tutorial for more details?
