### ISSUE TITLE
Overlap-Conflict

### ISSUE THREAD

**Issue by neda-abolhassani** [HazyResearch/snorkel#711]
Hi,
I ran Snorkel for my project. When I print the labeling function statistics (after applying the labeler), my conflicts and overlaps are equal to each other. It doesn't sound correct. Do you know why this happens?

j | Coverage | Overlaps | Conflicts
-- | -- | -- | --
0 | 0.648161 | 0.648161 | 0.648161
1 | 1.000000 | 0.648161 | 0.648161

Thanks,
Neda

**Comment by dolphin-zs** [comment]
Well, this problem, I guess, is that you only have two labeling functions, so overlaps or conflicts only happen between these two labeling functions.

According to the paper of Data Programming, _overlap_ is defined as the percentage of objects with more than one label and _conflict_ is the percentage of objects with conflicting labels.

**Comment by ajratner** [comment]
Looks like the two LFs are always disagreeing as @dolphin-zs said?  Closing for now, feel free to re-open if any more questions / discussion!
