### ISSUE TITLE
i try to run /snorkel-newftrs/test/LSTMTests.py but it showed errors about "Entities not found"

### ISSUE THREAD

**Issue by yyht** [HazyResearch/snorkel#712]
![image](https://user-images.githubusercontent.com/14133687/28114936-7abd8b2a-6735-11e7-9f84-69a634dedc21.png)

**Comment by ajratner** [comment]
Hi @yyht ,

That test has been been deleted from master and is no longer supported; please see the `RNN` classes used in the tutorials!
