### ISSUE TITLE
Semantic Versioning?

### ISSUE THREAD

**Issue by MattMorgis** [HazyResearch/snorkel#714]
Hi Snorkel Team,

We had a demo on Monday and wanted to revert back to `v0.5` to make sure we didn't hit any bugs or snags with the new `v0.6` release. 

However, the tag for `v0.5` is from January and there were 570~ commits between the `v0.5` and `v0.6` tags. Is there any easy way to revert to a previous version of Snorkel? Especially going forward as it seems the team pushes to `master` frequently. 

Also, for what it's with, I _just_ noticed the `v0.6.1` tag that was pushed about 12 hours ago. Can we expect more frequent tags as updates and fixes are merged into `master`?

**Comment by ajratner** [comment]
Hi @MattMorgis ,

You can just use git to revert to any commit that you want to.  We'll also start tagging more frequently if this helps

-Alex

**Comment by MattMorgis** [comment]
I ended up pulling a commit to revert, but was unsure if it was a stable one or not. But sounds good, thank you! Just wanted to bring it up!
