### ISSUE TITLE
intro tutorial super slow on gen_model.marginals(L_train)

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#718]
I'm running the intro tutorial out of the box with a fresh install of v0.6, and in Intro_Tutorial_2, the call "train_marginals = gen_model.marginals(L_train)" is taking over 30 minutes; it is making it through the triple nested loops, just very slowly. I'm assuming this is unexpected behavior?

**Comment by stephenbach** [comment]
Yup, definitely unexpected. Not seeing this locally. Can you confirm you're actually on 0.6.1?

**Comment by bhancock8** [comment]
On master and up-to-date with origin/master. Pulled 10 minutes ago and relaunched the notebooks; problem still there.

**Comment by bhancock8** [comment]
Looks like other funny business is going on. I'm now seeing it hang for "self.clear(session, **kwargs)" in UDFRunner class as well. Don't see how the two are connected yet, but I'll keep digging and report back here.

**Comment by bhancock8** [comment]
With 500 documents it runs in 20 seconds. I assume that's still unusual? The tutorial completes with reasonable results.

**Comment by bhancock8** [comment]
I cleared the database and ran again with the full set of spouse documents. It took 7.5 mins for the gen_model.marginals(L_train) command, and the final F1 score was 0.41. I think it's right; it's just slow?

**Comment by bhancock8** [comment]
It happens for both the CDR tutorial (1 min for 8272 marginals) and intro tutorial (7.5 min for 22195 marginals)--my final F1 scores and the dimensions (and nnz) for L_train match the saved values in the tutorials. For reference, how long does this line take when you run it in either tutorial?

**Comment by stephenbach** [comment]
Ah, ok, the issue is just a regression in how the label matrix subclass handles slicing. Reverting the commit that changed snorkel.annotations.csr_LabelMatrix drops the execution time on full intro docs to ~5 seconds. We're looking into how to fix or just revert. Will release an 0.6.2 shortly with a fix.

**Comment by stephenbach** [comment]
A workaround in the meantime is

```
from scipy.sparse import csr_matrix

train_marginals = gen_model.marginals(csr_matrix(L_train))
```

**Comment by ajratner** [comment]
@bhancock8 thanks for catching this!!  FYI fixing now, and regarding the `clear` operation being slow, we'll pin that to #719

**Comment by bhancock8** [comment]
Beautiful! Thanks a bunch for the quick fixes!

**Comment by ajratner** [comment]
No thanks for catching it so quickly :)!
