### ISSUE TITLE
Slow clearing of existing features for large feature spaces using PostgreSQL

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/snorkel#719]
Currently, clearing large feature sets can be very slow. For example, say I have a database with >375K `feature_key` entries built over a candidate set. I then want to then wipe that set and create features over a different set of candidates. Running the standard feature extraction code via the `apply` function hangs for hours on `Clearing existing...` Running `DELETE FROM feature_key;` directly similarly takes forever.

So are there some implicit `CASCADE DELETE` operations going on here? 

In general, DB operations involving inserting feature key/value pairs are very slow in a default install of PostgreSQL. 

Is there a better way to address with this?

**Comment by stephenbach** [comment]
Some more info would help narrow down whether it's a Postgres thing or a Snorkel thing.

Can you run EXPLAIN ANALYZE VERBOSE DELETE FROM feature_key (when the database is full again) and post the results?

**Comment by danich1** [comment]
Hopefully, I can add some insight to this problem. I actually have a similar issue except the database I'm working with has ~4M rows. Tried to run the above statement but that was hanging for a while, so instead I deleted only a 1000 rows. Here is the output:
>Delete on public.feature_key  (cost=34.93..8290.00 rows=1000 width=34) (actual time=10.308..10.308 rows=0 loops=1)
   ->  Nested Loop  (cost=34.93..8290.00 rows=1000 width=34) (actual time=1.786..8.168 rows=1000 loops=1)
         Output: feature_key.ctid, "ANY_subquery".*
         ->  HashAggregate  (cost=34.50..44.50 rows=1000 width=32) (actual time=1.762..2.272 rows=1000 loops=1)
               Output: "ANY_subquery".*, "ANY_subquery".id
               Group Key: "ANY_subquery".id
               ->  Subquery Scan on "ANY_subquery"  (cost=0.00..32.00 rows=1000 width=32) (actual time=0.026..1.228 rows=1000 loops=1)
                     Output: "ANY_subquery".*, "ANY_subquery".id
                     ->  Limit  (cost=0.00..22.00 rows=1000 width=4) (actual time=0.020..0.727 rows=1000 loops=1)
                           Output: feature_key_1.id
                           ->  Seq Scan on public.feature_key feature_key_1  (cost=0.00..89091.21 rows=4050121 width=4) (actual time=0.017..0.530 rows=1000 loops=1)
                                 Output: feature_key_1.id
         ->  Index Scan using feature_key_pkey on public.feature_key  (cost=0.43..8.24 rows=1 width=10) (actual time=0.005..0.005 rows=1 loops=1000)
               Output: feature_key.ctid, feature_key.id
               Index Cond: (feature_key.id = "ANY_subquery".id)
 Planning time: 0.530 ms
 Trigger RI_ConstraintTrigger_a_6869322 for constraint feature_key_id_fkey: time=156648.600 calls=1000
 Execution time: 156659.353 ms
(18 rows)

**Comment by stephenbach** [comment]
There might be useful info in #976, which adds indices to dramatically speed up clearing documents and candidates. We didn't actually touch the feature or feature key classes though because the annotation and annotation key mixin classes use all their foreign keys as primary keys.

I'm still not sure why that sequential scan is in the middle of the query plan...

**Comment by ajratner** [comment]
Closing this for now, feel free to re-open!
