### ISSUE TITLE
Running unseen data through trained model (Not an issue, just a question)

### ISSUE THREAD

**Issue by 8ballbb** [HazyResearch/snorkel#726]
When applying the trained model to unseen data, is it advised to create a new separate database for this data (ie. when preprocessing, parsing and extracting candidates)? Also, when applying a trained SparseLogisticRegression model to this data, what is the approach to applying the previously found features?

If I am incorrect in how I am approaching using a trained model with new unseen data, could you please provide me with some advice?

**Comment by ajratner** [comment]
Hi @8ballbb ,

Take a look at how we handle the test set in the intro tutorial- this is the "unseen data" in that setting, so you can follow the same steps.  You can also make new splits (i.e. splits 2,3,...) for different sets of unseen data if you'd like.

-Alex

**Comment by 8ballbb** [comment]
Thank you. I had tried this but the database was being cleared when I re-ran the CorpusParser on new data. I will have another look to see if there is an argument I didn't set to stop this from happening.

**Comment by ajratner** [comment]
Closing for now; feel free to re-open!
