### ISSUE TITLE
Viewer overflow

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#727]
The viewer frequently overflows (as shown below, for example), with no way of scrolling down or expanding the viewing window to see everything. Is there a way for it to either dynamically adjust its size to fit its contents or add a slider?

![screen shot 2017-07-20 at 1 28 44 pm](https://user-images.githubusercontent.com/12646092/28437457-8d91f6bc-6d4f-11e7-913e-1e056b4c8d6b.png)

**Comment by ajratner** [comment]
So there are some quick current ways to handle this: either set `n_per_page` or `height` when initializing the `Viewer` (see: http://snorkel.readthedocs.io/en/master/etc.html); i.e. you can reduce the number of candidates per page and/or increase the height of the viewer.  Perhaps we should change the defaults if this is happening commonly in the intro tutorial?

As for a proper fix, will try to get to it at some point soon, although quickly going beyond my hobbyist-level web dev capabilities :/...

**Comment by bhancock8** [comment]
Oh, perfect! I should've read the documentation more carefully. I'll use those parameters for a quick fix.
