### ISSUE TITLE
Details about the generative model (Just a question)

### ISSUE THREAD

**Issue by dolphin-zs** [HazyResearch/snorkel#736]
Hi, I'm very interested in this awesome system for information extraction. But when I tried to dive into details about the data programming paradigm, I find few materials that describe the detailed learning or inference procedure of the factor graph. In snorkel, this generative modeling is done by calling another system, numbskull. 

I have checked the pseudo code in the paper that performs a gradient step like sampling plus sgd.
I feel that it's a little bit similar to contrastive divergence for the products of experts model, but I'm not sure.
I'm not very familiar with PGM, do you have any reference about this?

Thanks!

**Comment by ajratner** [comment]
Hi @dolphin-zs ,

Thanks for the interest, and sorry for the delayed response!

[Numbskull](https://github.com/HazyResearch/numbskull) is used as the learning & inference engine in Snorkel to do Gibbs sampling and stochastic gradient descent for learning the generative label model in snorkel (the `GenerativeModel` class; represented as a factor graph).  We indeed interleave Gibbs sampling and SGD steps, which is very similar to contrastive divergence; you can check out one of our latest papers for slightly more detail here: https://github.com/HazyResearch/numbskull.

Overall, a great reference for PGMs more broadly is the Koller and Friedman textbook.  Hope this helps!

-Alex

**Comment by dolphin-zs** [comment]
Hi @ajratner ,

Thanks for your reply!
Indeed I plan to learn more about PGM by the textbook of Koller and Friedman.
You seems to mention that numbskull has relevant papers?
But I haven't found them on the github page of numbskull, haven't them beed published yet? 

Thanks!
-Shun

**Comment by ajratner** [comment]
No papers for Numbskull yet but we'll post everything to the snorkel.stanford.edu page whenever stuff comes out!

**Comment by dolphin-zs** [comment]
Thanks very much, and looking forward to your new breakthroughs!

**Comment by dolphin-zs** [comment]
Hi @ajratner ,

I find that [this paper](https://arxiv.org/pdf/1703.00854.pdf) of your group has properly addressed my questions, which states details about the learning process.
I think others interested in details about the denoising generative model may find it to be useful too.

Thanks for your kind reply.
-Shun

**Comment by ajratner** [comment]
Great to hear!

**Comment by ajratner** [comment]
Closing but will be accessible via the Q&A link!
