### ISSUE TITLE
Matcher functions problems

### ISSUE THREAD

**Issue by gengkunling** [HazyResearch/snorkel#739]
I was trying to build an organization matcher using "snorkel.matchers.OrganizationMatcher". However, the matcher seems only works for Stanford CoreNLP, but not Spacy. 

I looked into the code and found that:
```
kwargs['rgx'] = 'ORGANIZATION' 
```
It does not work for SpaCy because for the NER results, spaCy returns "ORG" rather than ''ORGANIZATION''.

Similar issues for other matchers. Is there a simple way to fix this?

**Comment by ajratner** [comment]
Hi @gengkunling -
I pushed a fix, will merge in as soon as tests pass.

More broadly, these matchers are all subclasses of [`snorkel.matchers.RegexMatchEach`](https://github.com/HazyResearch/snorkel/blob/issue-739-fix/snorkel/matchers.py#L241), which matches a specified attribute (e.g. the NER tags) of each token against a supplied regex.  So in your case, for example, you could instead just use:
```
org_matcher = RegexMatchEach(rgx='ORG', attrib='ner_tags')
```

Hope this helps!
Alex

**Comment by ajratner** [comment]
This should be fixed?  If not re-open
