### ISSUE TITLE
Travis builds taking way too long

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#748]
They're right up at the 50min limit, which means they often hit the limit and time out...

**Comment by paidi** [comment]
Is use of conda essential? I got the build time down to 34min by removing conda and using pip to manage all dependencies: https://travis-ci.org/paidi/snorkel/builds/268679880

**Comment by ajratner** [comment]
Thanks!!  This is a great tip- we'll integrate this change.  (Just to double check: you cleared the travis cache and this still worked?  I seemed to remember we had issues without conda... but maybe was doing something dumb)

Either way, thanks so much!  (Also, will get to your PR soon- sorry!  Team has been underwater for a deadline, almost done...)

**Comment by paidi** [comment]
Yes - I tried clearing the travis cache and everything still worked fine: https://travis-ci.org/paidi/snorkel/builds/268834989

The changes I made to the build script are here: https://github.com/HazyResearch/snorkel/compare/master...paidi:remove-conda. I can create a PR with these changes, if you like, but I presume you will also want to update the instructions in the README if you remove conda from the CI.
