### ISSUE TITLE
test_TF_notebook failing

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#751]
I created a branch (call "temp") from the up-to-date master branch, added a blank file and pushed, and now it fails the test_TF_notebook notebook test. This seems like undesirable behavior...

![image](https://user-images.githubusercontent.com/12646092/28835716-32159a78-769b-11e7-9433-4ce297f01e85.png)

**Comment by ajratner** [comment]
Is this still failing or fixed now?  Forgot

**Comment by bhancock8** [comment]
Passing now that I lowered the required accuracy down to 0.97, though that number was totally arbitrary.

**Comment by ajratner** [comment]
Sounds fine to me
