### ISSUE TITLE
Training, test and validation set splits

### ISSUE THREAD

**Issue by 8ballbb** [HazyResearch/snorkel#754]
Is there a way to split these sets based on the candidate level?

Splitting based on sentences has the issue of sentences can have varying number of candidates. So you end up with sets with imperfect sizes.

**Comment by ajratner** [comment]
Hi @8ballbb ,

We don't have anything built for that right now, but it's just an attribute of the Candidate object (col in the DB) that you can change, if you want to do something custom here!

**Comment by 8ballbb** [comment]
Thank you. 

I figured this might be the case but wanted to confirm.
