### ISSUE TITLE
unable to see the tags created by Spacy

### ISSUE THREAD

**Issue by suvinks** [HazyResearch/snorkel#768]
Hi 

Am new to using snorkel. I am trying out the Intro example. In there it says
"A Matcher heuristically filters the candidates we use. In this case, we just use a pre-defined matcher which looks for all n-grams tagged by Spacy as "PERSON". The keyword argument longest_match_only means that we'll skip n-grams contained in other n-grams."

Is there a way i can display the tags and ngrams that spacy creates? I could not find any documentation to help me with it. 

If there is documentation on each class, with their attributes and functions, please let me know. I did check on http://snorkel.readthedocs.io/en/master/index.html#

Thanks
Suvin

**Comment by ajratner** [comment]
Hi @suvinks,

You can look at the attributes of the `Sentence` object where this information is stored- for example `Sentence.pos_tags` or `Sentence.ner_tags`.  For the full set, see https://github.com/HazyResearch/snorkel/blob/master/snorkel/models/context.py#L60.

Hope this helps!

**Comment by ajratner** [comment]
Closing--will be viewable under Q&A--but feel free to re-open!
