### ISSUE TITLE
how to train multi-type NER according to swellshark

### ISSUE THREAD

**Issue by yyht** [HazyResearch/snorkel#770]
hi, i'v read swellshark for unlabeled ner, from the original paper, it said that "assume each entity is a binary classification task, i.e., each tagger predicts one entity type, although our method generalizes to multi-class settings without extensive changes". I'm not sure how to extend it to multi-class settings.

**Comment by chentc** [comment]
https://github.com/HazyResearch/snorkel/issues/604

**Comment by ajratner** [comment]
Hi @yyht sorry for the delayed response- see the advanced tutorial for categorical classification!
