### ISSUE TITLE
Index out of bounds error due to batching in SLR score function

### ISSUE THREAD

**Issue by chrisg1622** [HazyResearch/snorkel#787]
Dear Hazy Research Team,

I've run into a minor issue with the Sparse Logistic Regression development set checkpointing. An index out of bounds error is thrown by the score function when the size of my development set is not an exact multiple of the batch size. The function attempts to slice the Scipy csr matrix, but for the last batch (see below) b+batch_size is greater than the size of the first dimension of the matrix.

`File "snorkel/snorkel/learning/disc_learning.py", line 255, in marginals
    batch_marginals.append(self._marginals_batch(X[b:b+batch_size]))`

All the best,
Chris

**Comment by ajratner** [comment]
Hi Chris,

Great catch and sorry for the delayed response!  Fixed this bug ([PR](https://github.com/HazyResearch/snorkel/pull/813) is just pending tests then I'll merge in)

Thanks,
Alex
