### ISSUE TITLE
Intro tutorial not backend-agnostic

### ISSUE THREAD

**Issue by bhancock8** [HazyResearch/snorkel#790]
Running the intro tutorial with postgres yields candidate set sizes of 22254, 2811, and 2701. Running it with sqlite yields candidate set sizes of 22195, 2796, 2697. 

My guess is that somewhere the sqlite version is quietly tossing candidates with unicode conversion issues whereas postgres is keeping them, but that's just a hunch.

**Comment by bhancock8** [comment]
Follow-up observation: both backends result in the same number of Documents and Sentences. So the difference isn't just due to some documents being rejected and their candidates never getting a chance to be extracted.

**Comment by ajratner** [comment]
@bhancock8 any updates on this?  Would love some help here if you have ideas :)!

**Comment by bhancock8** [comment]
I think the answer is to go full on Python3 in v0.7. :) Get rid of these unicode issues.

**Comment by ajratner** [comment]
:D

**Comment by stephenbach** [comment]
TODO: check if this is still true in 0.7, which supports Python 2 and 3. We don't plan to stop Python 2 support until 0.8.
