### ISSUE TITLE
Is the problem with core nlp parser resolved?Getting connection error while parsing

### ISSUE THREAD

**Issue by Pooja-Palod** [HazyResearch/snorkel#793]
![image](https://user-images.githubusercontent.com/18054531/29776301-b921b8a0-8bf7-11e7-91f4-d822b3714e9d.png)

**Comment by ajratner** [comment]
I'm not sure what's going on here and can't see the actual error at the bottom of the trace?

**Comment by jason-fries** [comment]
@Pooja-Palod If you don't absolutely need CoreNLP, the SpaCy parser provided with Snorkel actually works quite well too!

**Comment by ajratner** [comment]
Closing for lack of further info, but feel free to re-open!

**Comment by aniket-sen** [comment]
![screenshot from 2018-06-22 18-18-42](https://user-images.githubusercontent.com/39578932/41777396-cc31587e-7648-11e8-9415-3761bb52bd96.png)
Do you have any fix for this?
