### ISSUE TITLE
Will snorkel support Chinese language?

### ISSUE THREAD

**Issue by BenDerPan** [HazyResearch/snorkel#797]
Will snorkel support Chinese language? How to do it with Chinese?

**Comment by ajratner** [comment]
Hi @BenDerPan - sorry for the delayed response!  We don't currently have Chinese support built in, but are aware of users deploying Snorkel over Chinese language data and believe that it should be easy to extend (it's all unicode, and the parsing modules we rely on have support for Chinese).  We'd be happy to work with you if interested in pushing on this and submitting a PR!

**Comment by francescoyang** [comment]
Hi  @ajratner  Which language parsing module is used?
