### ISSUE TITLE
Categorical LF training stats need to be fixed!

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/snorkel#800]

**Comment by kyrillp** [comment]
Hello, do you mean `csr_LabelMatrix.lf_stats(self, session, labels=None, est_accs=None)` or `GenerativeModel.learned_lf_stats(self)`?
I encountered the behavior that in the categorical setting I'm working in, csr_LabelMatrix.lf_stats gives values larger than 1.0 for coverage, overlaps and conflicts.
GenerativeModel.learned_lf_stats seems to return reasonable fractions.

**Comment by ajratner** [comment]
@kyrillp yup- should be fixed by @regoldman's PR #804 just merged in!
