### ISSUE TITLE
Using snorkel for Image Clasification/Detection

### ISSUE THREAD

**Issue by anilmaddala** [HazyResearch/snorkel#802]
I am working on a binary classifier/detector involving Images. True if a particular object in present in the image and false if it doesnt. Is there an example to make snorkel work on Image data? Thanks.

**Comment by ajratner** [comment]
Hi @anilmaddala ,

Sounds awesome! Can you give me more detail on your setup? Are your labeling functions written over the images as well, or over some associated text data?

If the former, we have a whole project (on the coral branch, merged into master soon) focused on this!  If the latter, the pipeline should be very similar to what's in the current notebooks... and we have an example tutorial which will be posted at some point soon as well

-Alex

**Comment by anilmaddala** [comment]
Thanks @ajratner for the quick response.

I am currently doing labelling entirely upon Images, nothing to do with text. Basically an opencv based edge detector which classifes the image into blurry/non-blurry. Incendentally the object I am trying to detect is always moving, so slightly blurry.

So its a bit of cheating to create my training data based on blurriness and then to train a network on the object present in the training data. Any thoughts? 

I will checkout the coral branch and looking forward for a tutorial.

**Comment by ajratner** [comment]
@paroma any thoughts here?  Seems like good fit for Coral?

**Comment by paroma** [comment]
First of all sorry for the late response, somehow missed the notification

The use case of detecting whether an object exists in an image is definitely a good fit for Coral. We have a private repo for that project that I can add you to if you think it would be useful!

**Comment by iskode** [comment]
Hello, I'm also interested in that. I'm work on image segmentation via pixel-wise classification.
I've a set of image processing methods that segments quickly many images but with about 85% of accuracy. So I'm wondering if I could not consider it as noisy label and use your framework to train a better model to segment my images. Is that a good fit for Coral? if yes, please add me to the private repo. Thank you so much.

**Comment by aparnaseshasayi** [comment]
I am interested to understand how to use Snorkel for labeling certain actions of hands in images

**Comment by johanna-codes** [comment]
> First of all sorry for the late response, somehow missed the notification
> 
> The use case of detecting whether an object exists in an image is definitely a good fit for Coral. We have a private repo for that project that I can add you to if you think it would be useful!

Is still  the repo for Coral private? If not, can I be added? Thanks :)

**Comment by paroma** [comment]
added @johanna-codes and @iskode to the private Coral repo
Also check out the image tutorial here: https://github.com/HazyResearch/snorkel/tree/master/tutorials/images

Closing this for now!

**Comment by Mainara** [comment]
Is still the repo for Coral private? If is possible, can you add me? I'm also trying to use the Snorkel and Coral to label images.

**Comment by harshgs** [comment]
Hi,

I want to use for classification problem on medical images. The main classification would be if the image has lesion or no lesion. I would love to know the labeling functions that i can create for these image data sets

**Comment by ArghyaPal** [comment]
Hi @paroma @ajratner I am also interested in applying data programming on **medical image domain**. I had a paper: Adversarial Data Programming (https://arxiv.org/abs/1803.05137) CVPR 2018, based on the idea of Data Programming. I will be happy to be a part of the project - if you kindly add me to the private repo of Image Classification.

Regards,
Arghya Pal.

**Comment by wingedrasengan927** [comment]
Hello,
First, the link for the image tutorial is not working. request the team to update the link.
and I'd request the team to add me into the private coral repo as I'm interested to use snorkel for labeling images for object detection.

**Comment by Jatin6004** [comment]
Hi, 
I am interested in how to label image data. I would request the team to add me to the coral repo.
Thanks.

**Comment by nthhiep** [comment]
Hi,
I'm interested in using Snorkel for labeling images, at both pixel and image-level. Could you please add me to the Coral repo. 
Thank you.

**Comment by TRT-AmyG** [comment]
Hello, Could I be added to the Coral repo? I'd like to apply weak supervision to image classification tasks
