### ISSUE TITLE
Tagging sequence markup for entity extraction 

### ISSUE THREAD

**Issue by hoagy-davis-digges** [HazyResearch/snorkel#810]
How can I use a tagging sequence such as IOB with snorkel features?

**Comment by jason-fries** [comment]
Hi @hoagy-davis-digges 

The easiest way to implement IOB tagging is to treat every word as a candidate and then use categorical variables, similar to the tutorial at: https://github.com/HazyResearch/snorkel/blob/master/tutorials/advanced/Categorical_Classes.ipynb

Here your labeling functions would output labels in the space `B, I , O, abstain`. This approach doesn't model dependencies between labels (like a CRF would), but not all problems actually need this. 

We're working on a formal entity tagging paper, so these types of tasks will be easier to work with in Snorkel in the near future.

**Comment by hoagy-davis-digges** [comment]
Awesome, thanks!

**Comment by ajratner** [comment]
Closing for now--will be accessible via the "Q&A" link in README--but feel free to re-open!

**Comment by jbkoh** [comment]
Hi @jason-fries 
Is there any update on the entity tagging with Snorkel you mentioned above? It'd be awesome if I could try it out for my use case. I've been doing research on entity resolution in metadata of buildings. I can also contribute if there is a room for it.

Thanks for the great project!

**Comment by thak123** [comment]
Any update in this regard?

**Comment by mpgxc** [comment]
Any update in this regard?

**Comment by jason-fries** [comment]
Hi @mpgxc,

The general idea behind sequence labeling with off-the-shelf Snorkel is outlined in Issue #1254. More technical details are available in the [manuscript](https://www.nature.com/articles/s41467-021-22328-4). There is also a demo notebook for weakly supervised NER at https://github.com/som-shahlab/trove/
