### ISSUE TITLE
dealing with multi-class label

### ISSUE THREAD

**Issue by chentc** [HazyResearch/snorkel#811]
Hello, 

I would like to train a sequence tagging model on potentially sensitive data. Right now we have collected some annotations on a text corpus, but each sentence just has one observation from the crowd. So my idea is to write some pattern based labeling function and integrate it with the crowd annotation to come up with a denoised version of the training set. I went through the tutorials but found out they are only for binary classification problems. 

In this post (https://github.com/HazyResearch/snorkel/issues/599), I notice there is an upcoming paper on entity recognition, which would be very relevant to what I would like to have for the labeling function. So I write this post to check with you guys if there is something somewhere that can help me to come up with LFs which can annotate different kinds of entities in a sentence. 

I am also wondering if there are some pointers available to show how to integrate LFs with crowd labels. Thanks!

**Comment by ajratner** [comment]
Hi @chentc ,

Overall, sounds like a great plan to combine crowd labels + other pattern-based LFs!

Snorkel does in fact have full support for categorical classification- see [this tutorial](https://github.com/HazyResearch/snorkel/blob/master/tutorials/advanced/Categorical_Classes.ipynb) for example!  We also have a tutorial for a crowdsourcing [here](https://github.com/HazyResearch/snorkel/tree/master/tutorials/crowdsourcing)!

As for more stuff on NER tagging in particular, we will be adding some stuff from recent research (see @jason-fries ) at some point soon, will keep you posted

Thanks,
Alex

**Comment by ajratner** [comment]
Closing for now--will be accessible via the "Q&A" link in README--but feel free to re-open!
