### ISSUE TITLE
LF for binary text classification

### ISSUE THREAD

**Issue by ProudHoosier** [HazyResearch/snorkel#815]
How do we write the labeler function for a binary text classification problem? Especially when they are short sentences and very fluid and colloquial in nature and it's difficult to write the regex for such sentences.

**Comment by ajratner** [comment]
Hi @ProudHoosier hard to say without further information about the problem... hopefully looking through some of the examples in the tutorials gives some ideas though!  You can also check out some of the blog posts on snorkel.stanford.edu e.g. the post on other weak supervision strategies people have played with in practice, many of which can be expressed in Snorkel as LFs.  Hope this helps a bit!

**Comment by ajratner** [comment]
Closing for now- will be accessible via "Q&A" link, and feel free to re-open!
