### ISSUE TITLE
Stats on label conflict

### ISSUE THREAD

**Issue by chentc** [HazyResearch/snorkel#823]
So I have written some basic labeling functions to recognize ORG and PERSON based on the internal ner tags and crowd annotations, over the Enron dataset. I have configured to use all candidates which are up to 6 grams. I have generated the following lists for the candidates. 
 
List of ORG candidates:
> ['Enron', 'Enron', 'Astros', 'Enron', 'Enron', 'Enron', 'Enron', 'ENA', 'EOL', 'Enron', 'Enron', 'Net', 'Works', 'NDA', 'LLC', 'Enron', 'Enron', 'Enron Net', 'Enron Net Works', 'Enron Net Works LLC', 'Net Works', 'Net Works LLC', 'Works LLC', 'Enron', 'Enron', 'Enron', 'Enron', 'Net', 'Works', 'NDA', 'Enron', 'Enron', 'Enron Net', 'Enron Net Works', 'Net Works', 'Net Works LLC', 'Works LLC', 'LLC', 'ENA', 'EOL', 'Enron Net Works LLC', 'Enron', 'Enron', 'http://pep.corp.enron.com', '/pep.corp.enron.com', 'PEP', 'Help', 'PEP Help Desk', 'Help Desk', 'PEP', 'PEP Help', 'Desk', 'BOWEN', 'CLAIR', 'Corp.', 'Enron Corp.', 'Enron', 'Enron Corp.', 'Party', 'Corp.', 'Enron', 'Party', 'Credit', 'Sons Company', 'Donnelley', 'Donnelley &', 'Donnelley & Sons', '&', 'Donnelley & Sons Company', '& Sons', 'Sons', '& Sons Company', 'Company', 'ClickPaper', 'Backup', 'Backup Adnan', 'Adnan', 'Patel', 'Global Counterparty', 'Counterparty', 'Backup Adnan Patel', 'Adnan Patel', 'Global', 'ClickPaper', 'ClickPaper', 'ClickPaper', 'Sigma', 'Sigma Factor', 'Factor', 'Sigma', 'NDA', 'EOL', 'EOL', 'Group', 'Sam', 'Sam Schott', 'Liquids', 'EOL Sam', 'EOL Sam Schott', 'Schott', 'the', 'the Global', 'Global', 'the Global Counterparty', 'Global Counterparty', 'the Global Counterparty Group', 'Global Counterparty Group', 'Global Counterparty Group', 'Counterparty', 'Counterparty Group', 'Product Control - Houston', 'Portland', 'Portland West', 'Portland West Desk', 'West', 'West Desk', 'West Desk', 'Desk', 'the', 'Preliminary', 'the Preliminary Name', 'the Preliminary Name Change', 'the Preliminary Name Change/', 'Preliminary Name Change', 'Preliminary Name Change/', 'the Preliminary Name Change/Merger', 'Name', 'Preliminary Name Change/Merger', 'Name Change', 'Name Change/', 'Change', 'Change/', 'Name Change/Merger', 'Change/Merger', '/Merger', 'Merger', 'the Preliminary', 'Preliminary Name', 'Global Contracts and Facilities', 'Enron Europe Global CounterParty', '/', 'EnronCredit', 'NDA', 'NDA', 'NDA', 'Confidential', 'Confidential Information', 'Information', 'I2', 'NDA', 'Tana', 'Tana Jones', 'Jones', 'NDA']

--------
List of PERSON candidates:
> ['Reagan Lehmann', 'Reagan Lehmann', 'Reagan', 'Lehmann', 'Reagan', 'Reagan', 'Wade', 'Wade', 'Gary', 'Gary', 'Wade', 'Wade', 'Mary', 'Mary', 'John', 'John', 'Brian', 'Brian', 'Glad', 'Nugent', 'Tana', 'John', 'John Nugent', 'John Nugent', 'John', 'John', 'John -', 'John - The', '-', '- The', 'The', 'Paul', 'Paul Finken', 'Paul Finken', 'Finken', 'John Nugent', 'John Nugent', 'Nugent', 'Tana', 'John', 'ROBERTA M NEVES', 'M', 'M NEVES', 'NEVES', 'MICHEAL T SEVER', 'T', 'T SEVER', 'SEVER', 'STEPHANIE G', 'STEPHANIE G ST', 'G', 'G ST', 'ST', 'MICHEAL', 'MICHEAL T', 'BRADLEY', 'BRADLEY M', 'M', 'STEPHANIE', 'BOWEN, ROBERT J', 'DIEBNER, BRADLEY M', 'ROBERTA', 'BRADLEY M MILLIGAN', 'M MILLIGAN', 'MILLIGAN', 'MILLIGAN, ROBERTA M', 'ROBERTA M', 'Taylor', 'Mark', 'Mark Taylor', 'Mark Taylor', 'Tom', 'Tom', 'R.R.', 'Stacey Richardson', 'Stacey Richardson', 'Richardson', 'Stacey', 'Linda Bryan', 'Linda Bryan', 'Bryan', 'Linda', 'Stacey', 'Stacey', 'Samuel Schott', 'Samuel Schott', 'Stacey', 'Bryan', 'Linda Bryan', 'Linda Bryan', 'Karen', 'Mary Gosnell', 'Mary Gosnell', 'Stacey Richardson', 'Stacey Richardson', 'Richardson', 'Samuel', 'Schott', 'Adnan Patel', 'Mary', 'Gosnell', 'Karen Lambert', 'Karen Lambert', 'Lambert', 'Linda', 'Samuel', 'Samuel', 'Samuel x3-9890', 'Samuel x3-9890 -', 'x3-', '-', 'x3-9890', 'x3-9890 -', '9890', 'Samuel x3-9890 - Attached', '9890 -', '-9890', 'x3-9890 - Attached', '-9890 - Attached', '9890 - Attached', '- Attached', 'Attached', '-9890 -', 'x3', 'Samuel x3', '-', 'Samuel x3-', 'Nanette', 'Nanette', 'NGL', 'NGL Supply', 'Supply', 'Sam Schott', 'Product', 'Product Control', 'Product Control -', 'Product Control - Houston', 'Control - Houston', '- Houston', 'Control', 'Control -', '-', 'Houston', 'Cheryl', 'Cheryl x3', 'Cheryl x3-', 'Cheryl x3-3103', 'x3', 'x3-', '-', 'x3-3103', '-3103', '3103', 'J - Attached', '- Attached', 'Attached', 'Daren', 'Daren J', 'Daren J', 'Enron', 'Enron Europe', 'Europe', 'J', 'Daren J -', 'J -', '-', 'Daren J - Attached', 'Fri', 'Gillian', 'Jope', 'Jope Hirl', 'Jope Hirl', 'Hirl', 'Peter', 'Peter', 'Tana Jones', 'Tana', 'Conner', 'Mathis', 'Mathis Conner', 'Mathis Conner']

As you can see, there are some conflicts in these two categories, such as "Sam Schott" and "Tana Jones" are treated as candidates for both classes. However, I got zero conflicts report in the lf_stats function. Any ideas why? Thanks!

**Comment by ajratner** [comment]
Hi @chentc sorry for the delay- just merged in PR #804 this should fix this issue?  Re-open if not!
