### ISSUE TITLE
Exception raised importing from snorkel.parser 

### ISSUE THREAD

**Issue by pcheng00** [HazyResearch/snorkel#827]
Hi, 

I get the following exception when trying to import from snorkel.parser:

>>> from snorkel.parser import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "snorkel/parser/__init__.py", line 5, in <module>
    from .spacy_parser import *
  File "snorkel/parser/spacy_parser.py", line 11, in <module>
    raise Exception("spaCy not installed. Use `pip install spacy`.")
Exception: spaCy not installed. Use `pip install spacy`.

I believe the exception is being raised because of line 9 in the spacy_parser.py module:

try:
  6     import spacy
  7     from spacy.cli import download
  8     from spacy import util
  9     from spacy.deprecated import resolve_model_name
 10 except:
 11     raise Exception("spaCy not installed. Use `pip install spacy`.")

I currently have spaCy 2.0.2 installed and it does not have the spacy.deprecated module. Does snorkel depend on an older version of spaCy? If so, what version?

Note I had to install spaCy via conda since the recommended pip install --requirement python-package-requirement.txt failed to install spaCy for me.  

Thank you.

**Comment by piordanov** [comment]
Downgrading to spacy==1.10.0 should resolve the errors. Spacyv2.0 seems to have some major differences that are breaking snorkel at time of this writing.

**Comment by ajratner** [comment]
Should be fixed by downgrading spacy as @piordanov says, fixed in PR #834
