### ISSUE TITLE
Windows7 and no tensforflow for python 2.7?

### ISSUE THREAD

**Issue by TuulaP** [HazyResearch/snorkel#832]
I've been following the installation instructions, but there seems to bit of chicken and egg problem with windows environment  Snorkel seems to require python 2.7, with tensorflow. But nowadays there is [no Tensorflow for python 2.7](https://stackoverflow.com/a/45328447/364931) but only for 3.6. 

Has anyone experienced or overcome this? 
I'm currently thinking it might be easiest to try snorkel with some unix machine  instead.

conda install tensorflow 
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7*
  - tensorflow -> html5lib ==0.9999999 -> python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by nutsci** [comment]
I had the same realization after working through several other issues specific to Windows. Switched to ubuntu and everything runs smoothly.
