### ISSUE TITLE
Error in writing files into /tmp/ 

### ISSUE THREAD

**Issue by huruifeng** [HazyResearch/snorkel#845]
I ran the codes in Intro_Tutorial_1, When I am running the codes:

```python
from snorkel.parser import TSVDocPreprocessor
doc_preprocessor = TSVDocPreprocessor('data/articles.tsv', max_docs=n_docs)
```

that will write a file 'tika.log' into /tmp/ directory,But it shows me a Permission Denies error.
Because someone else ran the codes before and there already existed a file named tika.log in /tmp, so I could not overwrite that file.

I think the author should fix it to avoid this situation to be happened. such as using `mktemp` to make a temp directory for each user to ran it

**Comment by ajratner** [comment]
Hi @huruifeng ,

This is very strange: `tika` is only conditionally imported if you use the `TikaPreprocessor` class; if you grep, you'll see it doesn't appear anywhere else. So I'm a bit lost as to what's going on here? Any other details you could provide?

Thanks,
Alex
