### ISSUE TITLE
Negative LF votings in categorical setting

### ISSUE THREAD

**Issue by fsonntag** [HazyResearch/snorkel#848]
Hey,
maybe I'm overseeing something, but is there a way to have label functions with negative votes in the categorical setting.
I basically can only give positive votes towards a class, but I want to generally disregard certain candidates.
Overall I'm facing the issue of high recall and low accuracy in the categorical setting, as I can't really downvote bad candidates...

**Comment by ajratner** [comment]
Hi @fsonntag the default I'd recommend would be to create a label for negatives- for example in the [Categorical tutorial](https://github.com/HazyResearch/snorkel/blob/master/tutorials/advanced/Categorical_Classes.ipynb), an example is:
```python
Relationship = candidate_subclass(
   'Relationship',
   ['person1', 'person2'],
   values=['Married', 'Employs', False]
)
```
So here, `False` is the class representing negative votes!  Let me know if this helps?  Good question!

**Comment by fsonntag** [comment]
Thanks for the quick answer.
Okay, I just realized that I can make my label functions return `False` instead of `0` and that the generative model will take this as a negative label into account. Thanks!

**Comment by ajratner** [comment]
Great!  Will close, have link to Q&A answers so this can help others- thanks for posting!
