### ISSUE TITLE
Can I use snorkel for Japanese sentence ?

### ISSUE THREAD

**Issue by kento1109** [HazyResearch/snorkel#854]
Hi,

I'm new to nlp and interested in snorkel.
Snorkel uses Stanford CoreNLP for pre-processing text.
But, I think this does not cover for Japanese text.
I can't imagine how to use snorkel for Japanese sentence.
Can I use snorkel after extracting candidate by using pre-processing tool ?

**Comment by ajratner** [comment]
Hi @kento1109,

Awesome!  You could definitely use Snorkel starting right after the candidate extraction stage- you just need to populate the database like we do for English with CoreNLP or spacy, but you could definitely use another tool instead

Hope this helps,
Alex

**Comment by kento1109** [comment]
Hi @ajratner 

Thank you for quick response!
I'll try using Snorkel for Japanese sentence!

**Comment by ajratner** [comment]
@kento1109 awesome let us know how it goes!
