### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by haixiaoyan7** [HazyResearch/snorkel#858]
**Hi everone! I want to use snorkel to process some chinese text,so i have to use stanfordcorenlp,but these error occured. what should I do** 

NewConnectionError                        Traceback (most recent call last)
d:\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    600                                                   body=body, headers=headers,
--> 601                                                   chunked=chunked)
    602 

d:\Anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    356         else:
--> 357             conn.request(method, url, **httplib_request_kw)
    358 

d:\Anaconda3\lib\http\client.py in request(self, method, url, body, headers, encode_chunked)
   1238         """Send a complete request to the server."""
-> 1239         self._send_request(method, url, body, headers, encode_chunked)
   1240 

d:\Anaconda3\lib\http\client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1284             body = _encode(body, 'body')
-> 1285         self.endheaders(body, encode_chunked=encode_chunked)
   1286 

d:\Anaconda3\lib\http\client.py in endheaders(self, message_body, encode_chunked)
   1233             raise CannotSendHeader()
-> 1234         self._send_output(message_body, encode_chunked=encode_chunked)
   1235 

d:\Anaconda3\lib\http\client.py in _send_output(self, message_body, encode_chunked)
   1025         del self._buffer[:]
-> 1026         self.send(msg)
   1027 

d:\Anaconda3\lib\http\client.py in send(self, data)
    963             if self.auto_open:
--> 964                 self.connect()
    965             else:

d:\Anaconda3\lib\site-packages\urllib3\connection.py in connect(self)
    165     def connect(self):
--> 166         conn = self._new_conn()
    167         self._prepare_conn(conn)

d:\Anaconda3\lib\site-packages\urllib3\connection.py in _new_conn(self)
    149             raise NewConnectionError(
--> 150                 self, "Failed to establish a new connection: %s" % e)
    151 

NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000000000B5D96D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
d:\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    439                     retries=self.max_retries,
--> 440                     timeout=timeout
    441                 )

d:\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    667                                 release_conn=release_conn, body_pos=body_pos,
--> 668                                 **response_kw)
    669 

d:\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    667                                 release_conn=release_conn, body_pos=body_pos,
--> 668                                 **response_kw)
    669 

d:\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    667                                 release_conn=release_conn, body_pos=body_pos,
--> 668                                 **response_kw)
    669 

d:\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    667                                 release_conn=release_conn, body_pos=body_pos,
--> 668                                 **response_kw)
    669 

d:\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    667                                 release_conn=release_conn, body_pos=body_pos,
--> 668                                 **response_kw)
    669 

d:\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    638             retries = retries.increment(method, url, error=e, _pool=self,
--> 639                                         _stacktrace=sys.exc_info()[2])
    640             retries.sleep()

d:\Anaconda3\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    387         if new_retry.is_exhausted():
--> 388             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    389 

MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=12345): Max retries exceeded with url: /?properties=%7B%22annotators%22:%20%22tokenize,ssplit,pos,lemma,depparse,ner%22,%22outputFormat%22:%20%22json%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000B5D96D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
F:\snorkel\snorkel\parser\corenlp.py in parse(self, document, text, conn)
    223         try:
--> 224             content = conn.post(self.endpoint, text)
    225             content = content.decode(self.encoding)

F:\snorkel\snorkel\parser\parser.py in post(self, url, data, allow_redirects)
    105         '''
--> 106         resp = self.request.post(url, data=data, allow_redirects=allow_redirects)
    107         return resp.content.strip()

d:\Anaconda3\lib\site-packages\requests\sessions.py in post(self, url, data, json, **kwargs)
    554 
--> 555         return self.request('POST', url, data=data, json=json, **kwargs)
    556 

d:\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    507         send_kwargs.update(settings)
--> 508         resp = self.send(prep, **send_kwargs)
    509 

d:\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    617         # Send the request
--> 618         r = adapter.send(request, **kwargs)
    619 

d:\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    507 
--> 508             raise ConnectionError(e, request=request)
    509 

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=12345): Max retries exceeded with url: /?properties=%7B%22annotators%22:%20%22tokenize,ssplit,pos,lemma,depparse,ner%22,%22outputFormat%22:%20%22json%22%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000B5D96D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<timed eval> in <module>()

F:\snorkel\snorkel\udf.py in apply(self, xs, clear, parallelism, progress_bar, count, **kwargs)
     46         print("Running UDF...")
     47         if parallelism is None or parallelism < 2:
---> 48             self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
     49         else:
     50             self.apply_mt(xs, parallelism, clear=clear, **kwargs)

F:\snorkel\snorkel\udf.py in apply_st(self, xs, progress_bar, count, **kwargs)
     69 
     70             # Apply UDF and add results to the session
---> 71             for y in udf.apply(x, **kwargs):
     72 
     73                 # Uf UDF has a reduce step, this will take care of the insert; else add to session

F:\snorkel\snorkel\parser\corpus_parser.py in apply(self, x, **kwargs)
     35         """Given a Document object and its raw text, parse into Sentences"""
     36         doc, text = x
---> 37         for parts in self.req_handler.parse(doc, text):
     38             parts = self.fn(parts) if self.fn is not None else parts
     39             yield Sentence(**parts)

F:\snorkel\snorkel\parser\corenlp.py in parse(self, document, text, conn)
    227         except socket.error as e:
    228             sys.stderr.write("Socket error")
--> 229             raise ValueError("Socket Error")
    230 
    231         # check for parsing error messages

ValueError: Socket Error

**Comment by ajratner** [comment]
@jason-fries any ideas here?

**Comment by jason-fries** [comment]
Hi @haixiaoyan7,

Some quick questions:
1) How are you loading Chinese model components in CoreNLP
2) Are you running multi-threaded? If so, what errors do you get using a single thread?

I've noticed socket errors before, sometimes when CoreNLP fails to shutdown properly after running multiple times.

**Comment by haixiaoyan7** [comment]
@jason-fries  Thank you for  your answer and this great tool. 
1. I downloaded the  CoreNLP  chinese models jar from the official website and change the Related configuration content in corenlp.py。
2. This is the cmd command in corenlp.py

-  'java -Xmx4g -cp "F:/snorkel\\parser/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer  -serverProperties StanfordCoreNLP-chinese.properties --port 12345 --timeout 600000 --threads 1 '

The thread = 1,so it seems not multithread. And I don't know how to shutdown the CoreNLP properly

**Comment by paroma** [comment]
closing this for now - feel free to reopen if it's still a problem!
