### ISSUE TITLE
When cloning/downloading snorkel, treedlib folder is empty

### ISSUE THREAD

**Issue by camisap** [HazyResearch/snorkel#859]
Just an FYI, an error pops up when running the tutorial notebooks because upon downloading or cloning the Snorkel repo, treedlib folder is empty. 

Fix: I downloaded the files from the "treedlib @ 8cb30e0" folder and deposited them into the empty "treedlib" folder that I had cloned with the rest of the repo. 
The tutorials run without a problem after that.

**Comment by ajratner** [comment]
Hi @camisap ,

If you run the tutorial notebooks / Snorkel via the `run.sh` script this should be taken care of automatically. Specifically, the command for this (in run.sh) is:
```
git submodule update --init --recursive
```

Hope this helps!
