### ISSUE TITLE
Travis error with Tensorflow

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/snorkel#862]
We're currently seeing build errors in Travis. This appears to be similar to what's reported in tensorflow here:

https://github.com/tensorflow/tensorflow/issues/16488

Could you look into it?

The error is:

```
2018-01-30 03:01:52.647301: F tensorflow/python/lib/core/bfloat16.cc:664] Check failed: PyBfloat16_Type.tp_base != nullptr 
```
[example failing build](https://travis-ci.org/HazyResearch/snorkel/jobs/327949938)

**Comment by ajratner** [comment]
@lukehsiao sorry I've never seen that error before. It's also weird that it's occurring in `python test/learning/test_gen_learning.py` which doesn't use Tensorflow (though I suppose may, through some chain of imports, load it?).  Either way sorry I can't help here :/

**Comment by ajratner** [comment]
Okay well now this is happening on master so I'll look into it tomorrow... @lukehsiao

**Comment by stephenbach** [comment]
Yeah, it's happening for `test/learning/test_supervised.py` and `test/learning/test_categorical.py` as well. Looks like it's happening on the initial import of snorkel.learning which imports tensorflow.

**Comment by stephenbach** [comment]
From tensorflow/tensorflow#16488

> I had the same problem using TensorFlow 1.5.0 on Pycharm with Anaconda. I solved it by updating numpy on both Pycharm and Anaconda to 1.14.0 (I thought they share the same numpy package but somehow no). This post indicates that wrong pandas version may also be a trigger.

**Comment by lukehsiao** [comment]
This appears to have resolved itself. Going to close this issue.
