### ISSUE TITLE
Using Postgres or other DB as source of documents

### ISSUE THREAD

**Issue by vlordier** [HazyResearch/snorkel#863]
Does it make sense to implement a postgresql (or other db) source for documents in this file ? Has anyone tried it or would it not be a good idea ? http://snorkel.readthedocs.io/en/master/_modules/snorkel/parser/doc_preprocessors.html

**Comment by ajratner** [comment]
@vlordier do you mean a `DocPreprocessor` subclass for ingesting input data stored in postgres? I think that would be a great addition- if you end up building this and submitting a PR, we'd love to review it :D!
