### ISSUE TITLE
Generality of method and framework for application to time series data

### ISSUE THREAD

**Issue by SemanticBeeng** [HazyResearch/snorkel#864]
Do `snorkel` and `data programming` apply to data other than text? 
Anybody using them for `time series` data?

What would it take to adapt to other kinds of data?

What would be the steps to apply to `time series` use cases? 

Is it just a matter of creating `labeling functions` specific for such data or are there things in implementation of `snorkel` that make it specific for text data?

Thanks

**Comment by vjtrost88** [comment]
It seems this is currently unsupported - see here: https://github.com/HazyResearch/snorkel/issues/446

**Comment by paroma** [comment]
This is a great question! If you create labeling functions specific for time series data, you can use the Snorkel GenerativeModel to learn assign probabilistic training labels. Would love to hear how it works for you, closing this for now!
