### ISSUE TITLE
Using FeatureAnnotator with float features scores

### ISSUE THREAD

**Issue by robertyates** [HazyResearch/snorkel#867]
At the moment FeatureAnnotator seems to coerce floats into integers somewhere inside of it.  I am trying to use tf-idf scores as feature scores and the additional precision is getting lost.  Is there a flag that I should be setting or is this not supported?

**Comment by ajratner** [comment]
@robertyates good call and thanks for bringing this up!  Yes, the underlying database representation is `float`-type, but it looks like the data was getting uniformly coerced to `int` by the `load_matrix` function.  Check out the PR I just submitted and see if it fixes it?

**Comment by robertyates** [comment]
works great, thanks
