### ISSUE TITLE
Working of generative model

### ISSUE THREAD

**Issue by srikar2605** [HazyResearch/snorkel#871]
Can anyone help me to understand how the relative accuracies of the labelling functions are being calculated? @ajratner @jason-fries

**Comment by ajratner** [comment]
Hi @srikar2605 - we use a generative model to learn these accuracies without any training data. Intuitively, we are looking at the matrix of their agreements and disagreements on unlabeled data, and learning the accuracies which make it most likely. See the data programming paper (https://arxiv.org/abs/1605.07723) and the data programming blog post (http://hazyresearch.github.io/snorkel/blog/weak_supervision.html) as well as other material on [snorkel.stanford.edu](snorkel.stanford.edu).  Hope this helps!

**Comment by srikar2605** [comment]
Hello Alex,
Thanks for the reply, I have another doubt. The candidates that we extract
from the documents, are they unique?

**Comment by stephenbach** [comment]
Yes, duplicates will be removed, so there will only be candidate referring to e.g., a particular tuple of spans of text.
