### ISSUE TITLE
Extracting candidates

### ISSUE THREAD

**Issue by srikar2605** [HazyResearch/snorkel#874]
My purpose is to extract one entity "issue"(faced by customer) How to extract the candidates? What matchers should i use?
 @ajratner  @jason-fries

**Comment by jason-fries** [comment]
Hi @srikar2605,
If you have a dictionary of potential `Issue` entities, you can use the `DictionaryMatch` to generate candidates. If you have a set of regular expressions for matching entities, you can use some variation on the `RegexMatch` matcher.
