### ISSUE TITLE
DDL.open_mindtagger

### ISSUE THREAD

**Issue by mrodriguezh** [HazyResearch/snorkel#875]
Hi:
When running DDL.open_mindtagger(...) in the notebook, there is a message "Making sure MindTagger is installed. Hang on!" but nothing happens. Is it normal that this installation to take so long?

**Comment by stephenbach** [comment]
Hi,

This sounds like a very old version of Snorkel. Can you confirm you're running the latest release 0.6.2 (https://github.com/HazyResearch/snorkel/releases) or the master branch?

**Comment by mrodriguezh** [comment]
Hi:
Yes, I was using a very old version. Now I work with the latest release. ;-)

**Comment by stephenbach** [comment]
Great!
