### ISSUE TITLE
OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'PRAGMA table_info("context")']

### ISSUE THREAD

**Issue by zkawan** [HazyResearch/snorkel#879]
Hi all,

I am trying to run Intro_Tutorial_2 and getting error w
Erorr:

---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1181                         parameters,
-> 1182                         context)
   1183         except BaseException as e:

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    469     def do_execute(self, cursor, statement, parameters, context=None):
--> 470         cursor.execute(statement, parameters)
    471 

OperationalError: database is locked

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
<ipython-input-1-7af0d4a4d0d6> in <module>()
      9 
     10 import numpy as np
---> 11 from snorkel import SnorkelSession
     12 session = SnorkelSession()

/home/zawan/PycharmProjects/snorkel-master/snorkel/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from .models import SnorkelSession
      4 
      5 __version__ = '0.6.2'

/home/zawan/PycharmProjects/snorkel-master/snorkel/models/__init__.py in <module>()
     40 # This call must be performed after all classes that extend SnorkelBase are
     41 # declared to ensure the storage schema is initialized
---> 42 SnorkelBase.metadata.create_all(snorkel_engine)

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/sql/schema.py in create_all(self, bind, tables, checkfirst)
   3858                           self,
   3859                           checkfirst=checkfirst,
-> 3860                           tables=tables)
   3861 
   3862     def drop_all(self, bind=None, tables=None, checkfirst=True):

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _run_visitor(self, visitorcallable, element, connection, **kwargs)
   1918                      connection=None, **kwargs):
   1919         with self._optional_conn_ctx_manager(connection) as conn:
-> 1920             conn._run_visitor(visitorcallable, element, **kwargs)
   1921 
   1922     class _trans_ctx(object):

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _run_visitor(self, visitorcallable, element, **kwargs)
   1527     def _run_visitor(self, visitorcallable, element, **kwargs):
   1528         visitorcallable(self.dialect, self,
-> 1529                         **kwargs).traverse_single(element)
   1530 
   1531 

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py in traverse_single(self, obj, **kw)
    119             meth = getattr(v, "visit_%s" % obj.__visit_name__, None)
    120             if meth:
--> 121                 return meth(obj, **kw)
    122 
    123     def iterate(self, obj):

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py in visit_metadata(self, metadata)
    710 
    711         collection = sort_tables_and_constraints(
--> 712             [t for t in tables if self._can_create_table(t)])
    713 
    714         seq_coll = [s for s in metadata._sequences.values()

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py in <listcomp>(.0)
    710 
    711         collection = sort_tables_and_constraints(
--> 712             [t for t in tables if self._can_create_table(t)])
    713 
    714         seq_coll = [s for s in metadata._sequences.values()

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py in _can_create_table(self, table)
    685         return not self.checkfirst or \
    686             not self.dialect.has_table(self.connection,
--> 687                                        table.name, schema=effective_schema)
    688 
    689     def _can_create_sequence(self, sequence):

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/base.py in has_table(self, connection, table_name, schema)
   1181     def has_table(self, connection, table_name, schema=None):
   1182         info = self._get_table_pragma(
-> 1183             connection, "table_info", table_name, schema=schema)
   1184         return bool(info)
   1185 

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/base.py in _get_table_pragma(self, connection, pragma, table_name, schema)
   1567         qtable = quote(table_name)
   1568         statement = "%s%s(%s)" % (statement, pragma, qtable)
-> 1569         cursor = connection.execute(statement)
   1570         if not cursor._soft_closed:
   1571             # work around SQLite issue whereby cursor.description

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/base.py in execute(self, object, *multiparams, **params)
    937         """
    938         if isinstance(object, util.string_types[0]):
--> 939             return self._execute_text(object, multiparams, params)
    940         try:
    941             meth = object._execute_on_connection

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_text(self, statement, multiparams, params)
   1095             statement,
   1096             parameters,
-> 1097             statement, parameters
   1098         )
   1099         if self._has_events or self.engine._has_events:

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1187                 parameters,
   1188                 cursor,
-> 1189                 context)
   1190 
   1191         if self._has_events or self.engine._has_events:

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1391                 util.raise_from_cause(
   1392                     sqlalchemy_exception,
-> 1393                     exc_info
   1394                 )
   1395             else:

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/util/compat.py in raise_from_cause(exception, exc_info)
    201     exc_type, exc_value, exc_tb = exc_info
    202     cause = exc_value if exc_value is not exception else None
--> 203     reraise(type(exception), exception, tb=exc_tb, cause=cause)
    204 
    205 if py3k:

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    184             value.__cause__ = cause
    185         if value.__traceback__ is not tb:
--> 186             raise value.with_traceback(tb)
    187         raise value
    188 

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1180                         statement,
   1181                         parameters,
-> 1182                         context)
   1183         except BaseException as e:
   1184             self._handle_dbapi_exception(

/home/zawan/new/lib/python3.6/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    468 
    469     def do_execute(self, cursor, statement, parameters, context=None):
--> 470         cursor.execute(statement, parameters)
    471 
    472     def do_execute_no_params(self, cursor, statement, context=None):

OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'PRAGMA table_info("context")']

**Comment by stephenbach** [comment]
Hi,

I suspect that this and #878 are related. It's possible for cells executed across different notebooks to interfere with each other if they are interleaved, perhaps by running them simultaneously. Since SQLite doesn't handle concurrent writes, I suspect it was locked.

Please delete `snorkel.db` and rerun the tutorial notebooks sequentially. If this fixes the problem, it was just a concurrent access issue. (You can also handle concurrent access situations by using a Postgres backend.
