### ISSUE TITLE
Labelling functions

### ISSUE THREAD

**Issue by srikar2605** [HazyResearch/snorkel#880]
Is it possible that labelling functions gives 1,2,3,4,5 as output instead of only 1,-1&0 ?For ex, If in a category 'A' there are 4 sub categories(x,y,z,w) can we label all the sub categories using labelling functions?
@ajratner  @jason-fries

**Comment by jason-fries** [comment]
Hi @srikar2605,

Yes, you can use labeling functions with categorical variables.  See our tutorial at: [Categorical Variables in Snorkel](https://github.com/HazyResearch/snorkel/blob/master/tutorials/advanced/Categorical_Classes.ipynb)
