### ISSUE TITLE
Question: How to match tagged entities separated by a comma

### ISSUE THREAD

**Issue by kopperud** [HazyResearch/snorkel#885]
Hello,

I use CoreNLP and have tagged entities such as "Hokkaido, Japan", either as "CITY", "COUNTRY" or "LOCATION" depending. How can I construct a matcher function such that I can match the entire span of "Hokkaido, Japan"?

Currently I have this matcher

```python
class LocationMatcher(RegexMatchEach):
    """
    Matches Spans that are locations, cities or countries, as identified by CoreNLP.
    """
    def __init__(self, *children, **kwargs):
        kwargs['attrib'] = 'ner_tags'
        kwargs['rgx'] = 'LOCATION|LOC|CITY|COUNTRY'
        super(LocationMatcher, self).__init__(*children, **kwargs)
```

Thanks
Bjørn

**Comment by stephenbach** [comment]
Hi,

Great question. You'll need to write a custom matcher that looks at both the ner tags and whether there are any comma (or other acceptable) tokens in between. You can use `LambdaFunctionMatcher(func=f)` where `f` is a function that operates on a candidate (same API as labeling functions). Then you can inspect both the ner_tags and words of the sentence that contains it.
