### ISSUE TITLE
How to digest pdf files

### ISSUE THREAD

**Issue by chhenning** [HazyResearch/snorkel#886]
I have a lot of pdf's (1000+) which are share the same domain (healthcare information) but are structured differently. They all contain tables which contain the meat of the information. Can I use snorkle to extract out these tables and create a model from them using snorkle?

**Comment by ajratner** [comment]
Hi @chhenning there's a cool project in our lab, built on top of Snorkel, called [Fonduer](https://hazyresearch.github.io/snorkel/blog/fonduer.html), that's exactly for this!!  Right now it's a branch in Snorkel, but will likely be getting pushed to it's own repo soon- either way you should check it out! @SenWu @lukehsiao @bhancock8

**Comment by chhenning** [comment]
@ajratner Thanks A LOT!
