### ISSUE TITLE
Printing candidates

### ISSUE THREAD

**Issue by srikar2605** [HazyResearch/snorkel#887]
When we are printing the candidates, ( Spouse(Span("b'Steve'", sentence=68759, chars=[0,4], words=[0,0]), Span("b'Barbara Thomas'", sentence=68759, chars=[10,23], words=[2,3]))) Can we get document ID along with the sentence number and all?
@ajratner  @stephenbach @jason-fries

**Comment by stephenbach** [comment]
Hi,
Candidates allow you to traverse the entire context tree! So if you have a candidate `c` then you can access the document id with `c.get_parent().document.id`

(`c.get_parent()` returns the enclosing sentence.)
