### ISSUE TITLE
Removing comments in html Parser

### ISSUE THREAD

**Issue by DarkDataAnalytics** [HazyResearch/snorkel#888]
Dear all,

I have noticed the HTMLDocPreprocessor class could not remove comments in the html files I used with Snorkel.
Looking at other examples I found it works nicely if the BeautifulSoup call is changed as followed :

def parse_file(self, fp, file_name) :
...
            txt = list(filter(self._cleaner, html.findAll(text=lambda text: not isinstance(text, Comment))))
...

Cheers.

**Comment by ajratner** [comment]
Thanks for this!  We'd love to accept it as a PR if you're willing!  Closing for now in mean time
