### ISSUE TITLE
Fonduer - paleo tutorial data missing

### ISSUE THREAD

**Issue by iross** [HazyResearch/snorkel#889]
Good morning--
I wanted to check out the Fonduer paleo measurement tutorial, to see a. how it works and b. determine whether there's work we can do within GeoDeepDive to get our corpus into a Fonduer-compatible state. It looks like the data files are no longer available, though. 
https://github.com/HazyResearch/snorkel/blob/fonduer/snorkel/contrib/fonduer/tutorials/paleo/download_data.sh#L2
Points to http://i.stanford.edu/hazy/share/paleo_tutorial_data.tar.gz, which throws a 404 error.

Is there any chance those documents are still available somewhere? Thanks!

**Comment by stephenbach** [comment]
Hi,
I suspect these are being migrated to the new Fonduer repo, with public release scheduled in the next week or two. Is that right, @SenWu ?

**Comment by lukehsiao** [comment]
Hi @iross,

As Stephen mentioned, we'll be making a new Fonduer repo soon. In the meantime, I've fixed the URLs so that you can get at that data.
