### ISSUE TITLE
Q/A- Using snorkel in my python script

### ISSUE THREAD

**Issue by zkawan** [HazyResearch/snorkel#892]
Hi there, 

Is it possible to use snorkel to label some data within my python script outside jupyter notebook? 
I have tried doing that even the import statement throws error.

ModuleNotFoundError: No module named 'snorkel'

**Comment by stephenbach** [comment]
Hi,

Definitely! This is often how we use Snorkel in our lab. The issue is likely just putting Snorkel on your Python path so that import statements know where to look. Here's a tutorial I found on doing so:

http://www.bdnyc.org/2012/09/editing-pythonpath-to-import-modules/
