### ISSUE TITLE
Discriminative model

### ISSUE THREAD

**Issue by srikar2605** [HazyResearch/snorkel#895]
Not able to understand what happens after marginal probabilities are generated.
How does the discriminative model work?

@ajratner @stephenbach 

Thankyou

**Comment by stephenbach** [comment]
Hi!

Our blog posts such as [this one](https://hazyresearch.github.io/snorkel/blog/weak_supervision.html) and the [Snorkel paper](https://arxiv.org/abs/1711.10160) provide details.
