### ISSUE TITLE
Entity extraction with Snorkel

### ISSUE THREAD

**Issue by raznargimeno** [HazyResearch/snorkel#896]
Hi,

I'm trying to implement an example of entity extraction with Snorkel. So far, I have not found any example of entity extraction without relations. Is there a complete example for this case?

Anyway, I have followed analogous steps to the examples implemented in _snorkel/tutorials/intro_ (relation examples). However, I have several doubts, in particular, about the definition of the class, the creation of the gold_labels and the training of the discriminative model:

1) I have implemented the following Candidate:

	`Person = candidate_subclass ('Person', ['person1'])`
Is the correct form for this case?

2) About the gold_labels (.tsv file):

    a) The structure followed for this case is \<document name\>::span:\<login\>:\<end of session\>\<tab\>\<label\>
 Is it correct?

	b) For mapping BRAT Annotations to Snorkel Candidates (previous format), I have not found a function similar to _map_annotations_ implemented in the _BratAnnotator_ class for this case (extraction of an entity without relationships). Is there an analogous function for this case?

3) Training of the discriminative model:

    In the script _snorkel/tutorials/intro/Intro_Tutorial_3.ipynb_ to train the discriminative model you apply 
     the following code:

```
     lstm = reRNN (seed = 1701, n_threads = None)
     lstm.train (train_cands, train_marginals, X_dev = dev_cands, Y_dev = L_gold_dev, ** train_kwargs)
```
   However, reRNN is for relations. Is there any implementation analogous to extract entities without 
    relations?

Thanks,
Rocío

**Comment by jason-fries** [comment]
Hi @raznargimeno,
There are currently no standalone tutorials for doing entity extraction with Snorkel. 
1) This is correct.
2) a) The gold label format is rather ad hoc and depends on use case.
    b) This is no equivalent function for importing entity-only annotations in BRAT. This is actually an easy change if you wanted to modify the `BRATAnnotator` code to support this.
3) There is a `TagRNN` implementation you can try as well. 

Hope this helps.

**Comment by raznargimeno** [comment]
Thank you very much for your help @jason-fries ! I will continue working on that direction.

**Comment by vlordier** [comment]
@raznargimeno @jason-fries could either of you put together a few words about how to go about NER with Snorkel to make up for the lack of standalone tutorial for doing entity extraction with Snorkel ?
Would be extremely useful :)

**Comment by ajratner** [comment]
Hi @vlordier I believe @jason-fries has a publication in the works!  Closing this for now, feel free to re-open
