### ISSUE TITLE
ImportError: No module named future.utils

### ISSUE THREAD

**Issue by khabiri** [HazyResearch/snorkel#897]
I followed all the steps successfully using  https://github.com/HazyResearch/snorkel#installation--dependencies
Now I run the ./run.sh and a notebook shows up. Going to tutorials>intro>Intro_Tutorial_1
Running the "from snorkel.parser import TSVDocPreprocessor" line, gives me the following error:
ImportError: No module named future.utils

I use macOS High Sierra. When I run "import future" it gives me this error. I can easily import future when using the command line. But in notebook it gives me this error.

Maybe it would help you to understand the problem if I give you the following extra information.
I originally received the error related to "builtins not found" and I solved it by replacing all the "from builtin  import *" with "from \__builtin\__  import *".

**Comment by ajratner** [comment]
What change did you make to the imports?  Doesn't look like there's a difference in what you wrote above? Also what version of Python are you running in?

**Comment by khabiri** [comment]
just fixed my comment. see above please

**Comment by khabiri** [comment]
It might help you to know that when I do ./run.sh, here is what I get:
"Snorkel home directory: /Users/elham/snorkel
Using PYTHONPATH=/Users/elham/Documents/spark-1.3.0-bin-hadoop2.4/python/:/Users/elham/Documents/spark-1.3.0-bin-hadoop2.4/python/::/Users/elham/snorkel:/Users/elham/snorkel/treedlib:/Users/elham/Documents/spark-1.3.0-bin-hadoop2.4/python
Environment variables set!"

I think the libraries are not visible from the notebook. When I do "import future" in command line python it finds it easily. The notebook gives me the error of "No module named future". You might want to fix something in setting the python library variables.

**Comment by khabiri** [comment]
You need to fix your documentation. If the python3 is used, none of the above problems are occurring. When I use python2 it tells me "builtins not found". Apparently for python2 it was used as underscore builtin underscore.

**Comment by paroma** [comment]
Thank you for catching this! The current version of Snorkel is meant for Python 3 as you noted
