### ISSUE TITLE
Extracting unigram, bigram, and trigram Candidate together.

### ISSUE THREAD

**Issue by KHvic** [HazyResearch/snorkel#898]
Hi, I am trying to extract every pair of unigram and bigram candidate. Is there any way to do this?

Given the text: "snorkel is a amazing tool"
I want the following set of candidate: {"snorkel", "is", "a", "amazing", "tool", "snorkel is", "is a", "a amazing", "amazing tool"}

I have tried the following, but does not work as intended:
: # RegexMatchSpan(rgx="[^\s]+") - to get unigram
: # NgramMatcher() - to get bigram

ngrams         = Ngrams(n_max=2)
matcher = Union( RegexMatchSpan(rgx="[^\s]+") ,NgramMatcher())

This does not extract the results from both the matcher

**Comment by ajratner** [comment]
Hi @KHvic love the example!  Using `Ngrams(n_max=2, longest_match_only=False)` should work, let me know?

**Comment by KHvic** [comment]
@ajratner Thanks for the help!
I think you are referring to 'longest_match_only' as a parameter for the matcher.

I have tried:
matcher = Union( NgramMatcher(longest_match_only = False), RegexMatchSpan(rgx="[^\s]+") )

Unfortunately, it still does not yield the intended result.
