### ISSUE TITLE
UnknownBackend   on  Intro_Tutorial_2.py 

### ISSUE THREAD

**Issue by loveJasmine** [HazyResearch/snorkel#903]
(venv) mldl@mldlUB1604:~/ub16_prj/gh-HazyResearch/snorkel/tutorials/intro$ sudo PYTHONPATH=~/ub16_prj/gh-HazyResearch/snorkel ipython Intro_Tutorial_2.py 
---------------------------------------------------------------------------
UnknownBackend                            Traceback (most recent call last)
/home/mldl/ub16_prj/gh-HazyResearch/snorkel/tutorials/intro/Intro_Tutorial_2.py in <module>()
     22 get_ipython().magic(u'load_ext autoreload')
     23 get_ipython().magic(u'autoreload 2')
---> 24 get_ipython().magic(u'matplotlib inline')
     25 import os
     26 

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-104> in matplotlib(self, line)

/usr/local/lib/python2.7/dist-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/usr/local/lib/python2.7/dist-packages/IPython/core/magics/pylab.pyc in matplotlib(self, line)
     98             print("Available matplotlib backends: %s" % backends_list)
     99         else:
--> 100             gui, backend = self.shell.enable_matplotlib(args.gui)
    101             self._show_matplotlib_backend(args.gui, backend)
    102 

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in enable_matplotlib(self, gui)
   2952         # Now we must activate the gui pylab wants to use, and fix %run to take
   2953         # plot updates into account
-> 2954         self.enable_gui(gui)
   2955         self.magics_manager.registry['ExecutionMagics'].default_runner = \
   2956             pt.mpl_runner(self.safe_execfile)

/usr/local/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.pyc in enable_gui(self, gui)
    505         if gui:
    506             self.active_eventloop, self._inputhook =\
--> 507                 get_inputhook_name_and_func(gui)
    508         else:
    509             self.active_eventloop = self._inputhook = None

/usr/local/lib/python2.7/dist-packages/IPython/terminal/pt_inputhooks/__init__.pyc in get_inputhook_name_and_func(gui)
     36 
     37     if gui not in backends:
---> 38         raise UnknownBackend(gui)
     39 
     40     if gui in aliases:

UnknownBackend: No event loop integration for u'inline'. Supported event loops are: qt, qt4, qt5, gtk, gtk2, gtk3, tk, wx, pyglet, glut, osx
(venv) mldl@mldlUB1604:~/ub16_prj/gh-HazyResearch/snorkel/tutorials/intro$

**Comment by ajratner** [comment]
Not enough information in this issue; closing this for now.
