### ISSUE TITLE
Performance and active learning

### ISSUE THREAD

**Issue by bjelkenhed** [HazyResearch/snorkel#905]
Hi, thank you for a really amazing project. We are using it for understanding the Swedish labor market and it is working really really well. 

Here is a couple of questions. One of the benefits of auto labeling with thumbrules is that it scales with the amount of data that is avaliable, not with the amount of labeled data. When we try to use Snorkel with 100 000 training examples or more it starts to take really long time to do the labeling. This is due to the use of SQLAlchemy and ORM where fetching the object graph will translate to joins from Span, Candidate, Sentence and up to Document tables in the database. 

How many training examples do you normally use? Do you configure Postgres in any particular way to be able to handle more data? 

Have you tried using Snorkel in combination with active learning (uncertainty sampling for example)? Would that method be complementary to using Snorkels method with autolabling? 

Best regards, Magnus

**Comment by stephenbach** [comment]
Hi! Thank you so much for using Snorkel! Thanks for your patience with our reply.

These are great questions!

We've successfully used Snorkel for 200k+ data points (see the [Snorkel paper](https://arxiv.org/abs/1711.10160) for details on the data) and anecdotally, users have gone higher. Most of the scaling issues we've encountered are usually in the data pre-processing code, not the actual statistical modeling that Snorkel does. Multithreading these operations, like in the [parallel processing tutorial](https://github.com/HazyResearch/snorkel/blob/master/tutorials/advanced/Parallel_Processing.ipynb), can help a lot.

We haven't tried combining active learning with Snorkel, but it should be complementary. Usually our philosophy is to save all hand labeled data for development and test sets.
