### ISSUE TITLE
How can I deal with chinese in Snorkel?

### ISSUE THREAD

**Issue by lcy081099** [HazyResearch/snorkel#906]
hi all:
      I have read the Intro_Tutorial_1-2-3,now I want extract relation from Chinese corpus ,the Intro_Tutorial_1 use spacy analysis corpus(tokensize,NER...) and save in database ,can i use other tools to deal with  tokensize,NER in Chinese corpus and save in database?

**Comment by haixiaoyan7** [comment]
just use stanfordCoreNLP

**Comment by francescoyang** [comment]
@haixiaoyan7  关于中文支持想请教一下？ 我的邮箱是muyixiaozhou@163.com，方便联系吗？

**Comment by haixiaoyan7** [comment]
@francescoyang 我也只是在学习阶段……
