### ISSUE TITLE
Named Entity Recognition with Categorical Classes

### ISSUE THREAD

**Issue by KHvic** [HazyResearch/snorkel#912]
Few questions and issue that I have faced using Snorkel for Named Entity Recognition:

1.
Currently, we have something like:
> NE = candidate_subclass('NE', ['ne'], values = [False, 'NAME', 'ORG' , 'DATE'])

(Here we have False because we do not want certain candidate to have any value as they are unimportant)

In our gold label, we only have the values of {1,2,3} to correspond to {NAME, ORG, DATE}
We trained a TagRNN model, but it only predicts {1, 2, and 3} for our candidates, we want it to produce a 0 to for unimportant candidates as well. How do we resolve this issue?

2.
In our case of -
> candidate_subclass('NE', ['ne'], values = [False, 'NAME', 'ORG' , 'DATE'])

Would like to clarify the confusion regarding returning a '0' and 'None' for Label Function:
Are they the same? 
If we are returning the literal values (i.e 0,1,2,3), this corresponds to  [False, 'NAME', 'ORG' , 'DATE']?

3.
Currently, we have extracted candidates using POS tags. However, they are huge in size. 
We have an idea of obtaining an additional probability feature for each candidate to filter them based on a constant threshold. Is there a way to do so for the candidate extractor?

Any help is much appreciated, thanks!

**Comment by haixiaoyan7** [comment]
HELLO, can you tell me how to manual label the categorical candidates.thank you.

**Comment by KHvic** [comment]
Hi, I simply wrote a script to transform my labeled data to create a labeled file with the format:

NE	ent_type
0::span:388:389	-1
0::span:406:407	-1
1::span:209:211	-1
1::span:761:763	2
5::span:429:434	1

document_id::span:startPos:EndPos caterogical_class

then use the script from introductory tutorial to load them into the database
