### ISSUE TITLE
Candidate.split == 0

### ISSUE THREAD

**Issue by vivienzou1** [HazyResearch/snorkel#916]
when I am loading `cands = session.query(Candidate).filter(Candidate.split == 0).all()`, it returns am empty list as `print (cands)`. I got `session.query(Candidate)` correct, but for `Candidate.split == 0` it return "Candidate.split = ?".....
Any idea?
Thanks.

**Comment by stephenbach** [comment]
Hi,

I'm not able to recreate this issue. When I have candidates loaded in the database, I am able to query for them using that command. Can you confirm that there are candidates in the database or provide more information?

```
I got session.query(Candidate) correct, but for Candidate.split == 0 it return "Candidate.split = ?".....
```
I'm sorry, I don't follow this. What is the code that produces this output? It sounds like the query executes without error but does not return any results?

Thanks!

**Comment by ajratner** [comment]
Closing this for now- feel free to re-open!
