### ISSUE TITLE
Training ML classifier(s) and using its input in snorkel

### ISSUE THREAD

**Issue by littlewine** [HazyResearch/snorkel#922]
Hi there.

I am using Snorkel for relationship extraction, but apart from the use case of defining regex and/or distant supervision, I would like to incorporate signals from ML models such as SVMs, Naive Bayes etc (created for instance in scikit-learn). Is there a recommended way to do that?

The most obvious (but probably not best) option to me atm is training them externally in sklearn, running the prediction in the unlabelled set and passing their results as a dictionary mapping such as the one bellow:
```
{ 
   'doc_id1': {'sent0': score,  'sent1': score,  'sent2': score } ,
   'doc_id2': {'sent0': score,  'sent1': score,  'sent2': score } ,
                   }
```
where score either a binary indicator or confidence score, and later pass them onto labelling functions as signals (like the distant supervision tutorial). However this does not seem very convenient.

I can also see there is an abstract class `Classifier`, but I am not sure if that's its purpose and is a bit unclear to me how to use it.

Any suggestions in regards that?

**Comment by stephenbach** [comment]
Hi! Thanks for using Snorkel!

The Classifier class is a parent class for classifiers that we want to train using Snorkel. So, it is not designed for use as a labeling function (although you could use a Snorkel-trained classifier as a labeling function for another classifier!)

Perhaps you can train a classifier and then encapsulate it in a labeling function that executes it on a candidate? It shouldn't be necessary to precompute the predictions.

**Comment by littlewine** [comment]
Hello Stephen. Many thanks for your answer.
I see, I just noticed that Classifier is a superclass of the discriminative models, so it is written mainly for that purpose. 

Your solution makes sense, however I believe it would be more time-consuming than simply performing the prediction separately and passing the predictions as a dictionary of "signals" (and maybe faster too, compared to loading the model each time for each labelling example). Also, in that case, you would have to re-write within snorkel (inside the LF) the feature extraction code in order to convert your sentence/candidate to the same representation the ML model was trained on (which will end up quite tricky when many different sets of features are used - at least in the prototyping phase). 

May I ask if any of you has tried using ML classifiers as LF and what the results were? I am planning to do so for relationship classification and I would like to investigate their effect in this task (in combination maybe with some patterns/regex). I think that thanks to your work on the dependency selector and the high coverage those ML models would have on the unlabelled set, some interesting results might arise.

**Comment by stephenbach** [comment]
That's a great point about data representation.

I haven't throughly investigated training classifiers to use as LFs, but [this paper](https://arxiv.org/abs/1709.02477) from some labmates uses pretrained deep nets for related tasks. It also addresses the issue of dependencies induced by shared components. I agree, it's very interesting! Let us know what you find!

**Comment by dmracek** [comment]
I'm looking to do something similar to what @littlewine is doing. @stephenbach is there a reproducible example, notebook, or tutorial that shows how to encapsulate something along the lines of scikit learn's .predict() in a labeling function that executes it on a candidate?
