### ISSUE TITLE
Problem with mapping gold annotations (from BRAT) to candidates 

### ISSUE THREAD

**Issue by littlewine** [HazyResearch/snorkel#927]
Hi,
I have some (already annotated) standoff files containing both entities and relationships and I am trying to import them into snorkel with no success. I am following [workshop tutorial 7](https://github.com/HazyResearch/snorkel/blob/master/tutorials/workshop/Workshop_7_Advanced_BRAT_Annotator.ipynb), but when I running `brat.import_gold_labels(session, "development", dev_cands)`, I get the following warnings:

```
Warning: 23425605 Span annotations do not match BRAT:[MeHg]!=SNORKEL:[] [949:953]
Warning: 23425605 Span annotations do not match BRAT:[dopamine]!=SNORKEL:[] [221:229]
Warning: 23425605 Span annotations do not match BRAT:[MeHg]!=SNORKEL:[] [1034:1038]
Warning: 23425605 Span annotations do not match BRAT:[calcium]!=SNORKEL:[] [1025:1032]
Warning: 23425605 Span annotations do not match BRAT:[methylmercury]!=SNORKEL:[synthesis, in] [57:70]
Warning: 23425605 Span annotations do not match BRAT:[catecholamine]!=SNORKEL:[demonstrate t] [20:33]
Warning: 23425605 Span annotations do not match BRAT:[tyrosine hydroxylase]!=SNORKEL:[] [1178:1198]
Warning: 23425605 Span annotations do not match BRAT:[dopamine]!=SNORKEL:[ar DA, a] [89:97]
Mapped 0/3558 ( 0%) of BRAT labels to candidates
```

As you can see, most of the SNORKEL mentions are empty, apart from those having offsets which are not that big. After having a look at my data, I figured out that while BRAT offsets are based on the beginning of the document, the snorkel span annotations (when not empty) start from the beginning of the last sentence of each document.

From the preprocessed dump used in tutorial 7 (brat-spouse.zip), I can see that each sentence was split in a new line and this might be the cause of the problem, as I copied `tools.conf` from the tutorial files, which has the following configuration:

```
# Possible values for splitter:
# - regex  : regular expression-based sentence splitting
# - newline: split by newline characters in source text (only)
Sentences	splitter:newline
```

However, I am unsure how to fix that problem, as there is a good chance that I will either ruin the offsets or might not be able to split the sentences again in a consistent way. Initially, for the candidate extraction phase (when creating snorkel db), I used the Stanford corpus parser with the pre-tagged candidate extractor (using a unary_tags dictionary and a mesh dict) for the entity tags.

Is there a way to ensure that the sentences are split again in the same way, or another way to import the gold labels into snorkel?
Thanks in advance!

**Comment by gpandey19** [comment]
we are facing the same issue , dis we find any approach to resolve this.

Thanks

**Comment by ajratner** [comment]
@jason-fries any ideas here?

**Comment by jason-fries** [comment]
@littlewine You are correct that BRAT uses absolute document offsets. If you did any preprocessing of your documents before bringing them into BRAT (e.g., tokenization, stripping whitespace) this can cause alignment issues when importing into Snorkel. Given an unmodified document annotated in BRAT, the same document parsed by CoreNLP should have the same absolute document offsets.
