### ISSUE TITLE
Loading Non-Documents into Session Database

### ISSUE THREAD

**Issue by bjcmit** [HazyResearch/snorkel#934]
I have a CSV of rows containing numeric sensor readings at a specific timestamp. I have processed this CSV into sequences containing multiple rows. A small number of sequences have been labeled as containing an event of interest. I would like to load the unlabeled and labeled sequence into a Snorkel session. It is my understanding that the session database is organized by Candidate, Document, and Sentence. How would you suggest loading my data into the Snorkel session? Thanks in advance.

**Comment by bartgras** [comment]
Did you succeed with this task? I'm curious if/how it worked.
As for your problem, intuitively, if your "event of interest" is applied to single sensor reading then this would be your equivalent of Sentence. In that case you should just ignore Document.
But if "event of interest" is applied to series of sensor readings then, with my current understanding how snorkel works, I don't think it's possible.

**Comment by paroma** [comment]
As @bartgras suggested, you could map a sentence to a single sensor reading and assign labels accordingly. You can also set up your own Session database or use a different way of accessing your data, such as with pandas. In this case, you can still write labeling functions over your data to generate the label matrix `L` and input it to the generative model to get probabilistic labels.

closing this for now, but tagging it as a Q&A, feel free to re-open!
