### ISSUE TITLE
Trouble with import BRAT annotations

### ISSUE THREAD

**Issue by thejeswi** [HazyResearch/snorkel#939]
Hello,
I am following the tutorial Advanced/Brat_annotations.
Running the following line:
`doc = session.query(Document).filter(Document.name==doc_name).one()`
Bring the error
 `NoResultFound: No row was found for one()`
Running `session.query(Document).all()` gives an empty string.

I see that the annotations have not been added to the database. How can I do this?

**Comment by jason-fries** [comment]
Hi @thejeswi
I'd double check that your Spouse tutorial database is initialized. Your error indicates you are working with an empty database instance. Make certain your run the full spouse tutorial and have that copy of `snorkel.db` in the same directory as the advanced tutorial.

**Comment by jason-fries** [comment]
Closing this issue. If you still have problems @thejeswi please reopen.
