### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by HarrietLyBui** [HazyResearch/snorkel#940]
When I try to import: `from snorkel.learning import GenerativeModel`

I got an error saying Illegal instruction (core dumped)
I am working on Ubuntu 16.0

**Comment by stephenbach** [comment]
Hi,

I haven't seen this issue before, and cannot recreate it. It seems unusual since the Python interpreter itself is crashing. We'll need more information to be able to help. Is there a stack trace you can produce from the dumped core?

**Comment by HarrietLyBui** [comment]
Hi,

I tried to import snorkel and run the program using command line "python filename.py" only instead of running it with jupyter notebook. This was when the error happened. Everything runs well if I run the program through jupyter notebook.

**Comment by ajratner** [comment]
Closing this issue for now as not enough information for us to debug- happy to reopen though!
