### ISSUE TITLE
Relation extraction on pretagged candidates

### ISSUE THREAD

**Issue by amineabdaoui** [HazyResearch/snorkel#947]
Hi,

I want to use snorkel to extract 5 types of relationships between pretagged entities. I already have a trained NER model that detects the desired entities pretty well. I just need snorkel to extract relations between preannoted candidates.

Is it possible to use my own pretagged entities as snorkel candidates? I have found a class named `PretaggedCandidateExtractor` but I'm not sure that it suits me.
Do you have any documentation or examples?

Thank you very much !

**Comment by amineabdaoui** [comment]
@stephenbach @ajratner 
Any help please :-)

Thank you !

**Comment by ajratner** [comment]
Hi @amineabdaoui , the `PreTaggedCandidateExtractor` is indeed the class we currently have for this setting. You can see it used in the CDR tutorial we have.

Another option (which might end up being ultimately cleaner, depending on your NER tagger) is to create a new `Parser` subclass for it(for example, see the [`Spacy`](https://github.com/HazyResearch/snorkel/blob/f788d0ba088de1fc59da7564f1f04b8eb369a89d/snorkel/parser/spacy_parser.py#L23) subclass as an example)

Hope this helps!

**Comment by amineabdaoui** [comment]
Thank you very much @ajratner 
Indeed, your answer is pretty helpful :-)

Right now, I'm trying to load labeled categorical relations as a gold standard to evaluate my models. However, it seems that the [Categorical_Classes Tutorial](https://github.com/HazyResearch/snorkel/blob/master/tutorials/advanced/Categorical_Classes.ipynb) do not use any specific `load_external_labels` method. Is this means that we can load categorial labels in the same way as we did this on binary labels ?

**Comment by ajratner** [comment]
Yep!
