### ISSUE TITLE
generative model: gen_model.learned_lf_stats()

### ISSUE THREAD

**Issue by sdeb-chegg** [HazyResearch/snorkel#949]
when this function is run it outputs accuracy, precision, recall and coverage. What is the evaluation set for calculating accuracy, precision and recall? 
Is it the gold set
or is it all data that has been tagged in the snorkel eco system.

Thanks,
--Sangha.

**Comment by ajratner** [comment]
Hi Sangha!  This is the learned parameters of the model- so it's not the metrics evaluated on any set, but rather the parameters as estimated by the generative model

Thanks,
Alex

**Comment by sdeb-chegg** [comment]
Can you point me to a paper/article that explains these parameters.

**Comment by ajratner** [comment]
You can check out the Snorkel VLDB paper as highlighted on
snorkel.stanford.edu!
