### ISSUE TITLE
Are there any tutorials or examples for using snorkel with numerical data?

### ISSUE THREAD

**Issue by Anirudh-Muthukumar** [HazyResearch/snorkel#950]
I have gone through many of the your tutorials and examples but I am not able to find any assistance on how to use snorkel for unstructured numerical data. Similar issue was raised by @gallamine #446  in 2016 and it is closed.

Thank you.

**Comment by ajratner** [comment]
Hi @Anirudh-Muthukumar great question!  Depends what you mean by unstructured numerical data?  But if you mean e.g. extracting numbers from text, then you can use a `Matcher` like the [`NumberMatcher`](https://github.com/HazyResearch/snorkel/blob/f788d0ba088de1fc59da7564f1f04b8eb369a89d/snorkel/matchers.py#L306), or a more general one using the `RegexMatcher`, to form `Candidates` that include numbers- then you can use the rest of the pipeline same as in the other tutorials.  Hope this helps!

**Comment by Anirudh-Muthukumar** [comment]
Hi @ajratner thanks for replying! To be precise, I have a csv file with lots of numerical values on which I wish to use snorkel to label them. I am also finding it difficult to strike the analogy that lies between script for textual data (which is well explained in the tutorial) and how to go about creating scripts for numerical data. 
I have the necessary numbers in my CSV file (for which I wish to create labels based on certain weak supervisions). It'd be very helpful if you could share some tutorial or example. Thanks!

**Comment by ajratner** [comment]
Hi @Anirudh-Muthukumar we don't currently have any examples directly for this- see the issue you linked (#446 ) for some thoughts on why.  Either way, you could check out the doc preprocessors in https://github.com/HazyResearch/snorkel/tree/master/snorkel/parser.  And if you do build something here, we'd love if you share it!

**Comment by Anirudh-Muthukumar** [comment]
Hey @ajratner thanks for the update.

**Comment by Anirudh-Muthukumar** [comment]
Hey @ajratner I have converted my data which was originally in CSV file into a TSV file and now I am able to retrieve it in Document->Sentence form using TSVDocPreprocessor.

TSV file format : 
<Document Name>\t<Number>

which is of the shape 26323 x 2.

 I am defining a candidate subclass to extract the numbers and I am using NumberMatcher class to retrieve the numbers as shown.

Good = candidate_subclass('Measurement', ['rtt'])

ngrams         = Ngrams(n_max=1)
number_matcher = NumberMatcher()
cand_extractor = CandidateExtractor(Good, ngrams, [number_matcher])

And when I apply the cand_extractor to extract the candidates I am not getting desired output.

for i, sents in enumerate([train_sents, dev_sents, test_sents]):
    cand_extractor.apply(sents, split=i)
    print("Number of candidates:", session.query(Good).filter(Good.split == i).count())

Output:
Clearing existing...
Running UDF...
[========================================] 100%

('Number of candidates:', 2)
Clearing existing...
Running UDF...
[========================================] 100%

('Number of candidates:', 0)
Clearing existing...
Running UDF...
[========================================] 100%

('Number of candidates:', 0)
CPU times: user 2.48 s, sys: 160 ms, total: 2.64 s
Wall time: 2.73 s


Can you help me with it?

**Comment by ajratner** [comment]
Not sure without seeing the actual results, but the NumberMatcher is
relying on the ‘number’ tag from the spacy or Corenlp parser. These parsers
are meant for full sentences, so might not be working if your “document” is
just a single number (correct?)?

In this case you could make a much simpler matcher that just takes the
whole document- for example you could use the Ngram matcher, since each of
your docs is just a unigram that is the number?

**Comment by Anirudh-Muthukumar** [comment]
@ajratner thanks for the input! I have used RegexMatcher() from snorkel.matcher to extract the numbers.

**Comment by ajratner** [comment]
Great!
