### ISSUE TITLE
Is it possible to run snorkel with a linear classifier as the discriminative model?

### ISSUE THREAD

**Issue by aindrilabasak** [HazyResearch/snorkel#951]
In both the tutorial examples, after the generative model, neural networks are used as noise-aware discriminative models. Is it possible to use a linear classifier (e.g., logistic regression) as a discriminative model? In that case, what would be the right way to interpret the confidence scores (i.e., the train marginals) generated by the generative model?

**Comment by ajratner** [comment]
@aindrilabasak Check out https://github.com/HazyResearch/snorkel/blob/master/snorkel/learning/disc_models/logistic_regression.py, and interpretation of the probabilistic training labels is exactly the same!

**Comment by aindrilabasak** [comment]
@ajratner Thank you for the reply. I understand that the generative model produces a noise-aware training label set for the discriminative model. However, if I want to train any binary classifier (that is not present in the snorkel library, e.g, SVM or Random forests) how can I convert these confidence scores to training labels for the classifier?
For example: I understand that when the confidence score for a datapoint is 0.9, it means that the generative model is 90% confident about the label for this data point. But, how can I know what is the actual label (e.g., is it 1 or -1 ?) that the generative model is confident about?

**Comment by aindrilabasak** [comment]
I am trying to run the intro example with LogisticRegression. As the LogisticRegression that is part of snorkel library, accepts its input training candidates only as csr_AnnotationMatrix, just wanted to know how can I convert the train_cands list to a csr_AnnotationMatrix?

**Comment by aindrilabasak** [comment]
@ajratner, thank you for the answer. I could run my code with Logistic Regression. So, if I want to run my code with any other classifier such as SVM (i.e., not present in the current snorkel library), what approach should I take? 
As far as I can understand, the Logistic Regression in the code is not just imported as a package from the sklearn repository, but the algorithm was implemented as a subclass of TFNoiseAwareModel. So, if I want to run any other linear classifier, do I need to implement the algorithm as a subclass of the noise-aware model? Or can I just import the algorithm as a package and run it with the train_candidates and trin_marginals as input?

**Comment by ajratner** [comment]
Both are correct- you can either (a) subclass TFNoiseAwareModel, or create
an alternative class like this one for non-tensorflow classifiers (one for
PyTorch is coming soon!), or (b) just feed in the candidates and
probabilistic training labels (train_marginals) if the training code you’re
using supports probabilistic training labels. Note that w (b) you also need
to get the candidate into a basic format that works with your classifier
(see the models we implemented for an example)

If you do make a new class in (a) feel free to share w a PR :)!

**Comment by gpandey19** [comment]
@aindrilabasak @ajratner 
How can we  train the Logistic Regression model using the candidates and the train marginals.

It will be helpful,if you can verify the below approach

from snorkel.learning.disc_models.logistic_regression import *
disc_model = LogisticRegression()
disc_model.train(train_cands, train_marginals, X_dev=dev_cands, Y_dev=L_gold_dev, **train_kwargs)


I'm getting these two errors: 
'list' object has no attribute 'shape
TypeError: list indices must be integers, not tuple

**Comment by gpandey19** [comment]
@ajratner 
w.r.t (see the models we implemented for an example)
Please specify the model where the candidates have been modified as the algorithm used

**Comment by ajratner** [comment]
Hi @gpandey19 to use logistic regression, you need to precompute a set of features; for an example, you can see [this test](https://github.com/HazyResearch/snorkel/blob/master/test/learning/pytorch/test_logistic_regression.py) (for the PyTorch version).  Hope this helps!
