### ISSUE TITLE
Bug in brat.py

### ISSUE THREAD

**Issue by tuxmam** [HazyResearch/snorkel#952]
Hello, 

At line 561 from contrib/brat/brat.py
` anno_filelist = set([os.path.basename(fn).strip(".ann") for fn in glob.glob(input_dir + "/*.ann")])`
I think the method strip is unappropriated here.

According to the [documentation](https://www.tutorialspoint.com/python/string_strip.htm) span remove chars from the beginning and the end of the string.

So the string "news01.ann" would be transform in "ews01" instead of "news01".
It prevents the file to be found.

I think a fix would be to use `os.path.basename(fn)[:-4]`.

**Comment by jason-fries** [comment]
Hi @tuxmam 
Good catch! We'll file this as a bug.
