### ISSUE TITLE
Parse docs and append more sentences into current SnorkelSession from new tsv files

### ISSUE THREAD

**Issue by HarrietLyBui** [HazyResearch/snorkel#955]
```
    session = SnorkelSession()
    doc_preprocessor = TSVDocPreprocessor(path_to_tsv)
    corpus_parser = CorpusParser(parser=Spacy())
    corpus_parser.apply(doc_preprocessor)
```
I am trying to parse a *.tsv file with snorkel. To my understanding, the corpus_parser will parse the docs in doc_preprcessor and store the sentences in SnorkelSession(). My *.tsv file's size is 412M and I had a 16G memory AWS instance. During the process of processing the tsv file and parsing the documents, my machine ran out of memory. 

I was recommended to process a smaller multiples tsv files instead of one big one in order to free up memory. However I do not know how to append sentences that are parsed from different *tsv file to one SnorkelSession(). Should I initialize multiple SnorkelSession() instead?

Thank you.

**Comment by paroma** [comment]
you can try creating multiple `TSVDocPreprocessor` objects for the multiple files and combine them in the candidate generation stage

tagging as Q&A and closing this for now, but feel free to reopen if it's still a problem!
