### ISSUE TITLE
Saving annotations to Database

### ISSUE THREAD

**Issue by Anirudh-Muthukumar** [HazyResearch/snorkel#956]
I have labelled quite a large number of samples through SentenceNgramViewer. How do I save it to the database so that I don't have to label them manually each time I run the script? 

Thanks!

**Comment by ajratner** [comment]
The labels should save to the database automatically- are you not seeing
this happen?

**Comment by Anirudh-Muthukumar** [comment]
Yes it is @ajratner. Thanks!!

**Comment by HarrietLyBui** [comment]
May I ask if there is a file the labels are saved to?
