### ISSUE TITLE
can snorkel be used for non-text data?

### ISSUE THREAD

**Issue by eloriundo** [HazyResearch/snorkel#957]
I would like to to test snorkel for some applications with simple tabular data: columns of numeric/categorical features, with rules defined over those features (`if column A>100 and column D == "red" --> label = -1`). Is it possible to use snorkel in such problems? if so, how to define the correct contexts and candidates?

(from the paper and the readme, snorkel and data programing doesn't seem to be text specific, but I cannot find anything with the API that refers to non-text datasets)

**Comment by stephenbach** [comment]
Thanks for checking out Snorkel! You're right, the methods behind Snorkel are not specific to text data! We've focused on text data in a lot of the preprocessing code just to help people with text data get started even more easily.

There are a couple of options for using Snorkel with other types of data. One is to extend the candidate and context classes with new subclasses for other data types. Another is to create your labeling functions outside of Snorkel and feed your own vote matrix to the generative model.

See #938 for examples of using Snorkel with image data and #803 for more discussion.
