### ISSUE TITLE
about installing

### ISSUE THREAD

**Issue by ne1114** [HazyResearch/snorkel#958]
I am new to this Anaconda environment .. I'm not sure how it is ran ..
anyways in the installation part I donwloaded conda and created py2Env with python 2.7 / installed numba 
but I am stuck with installing requirement.txt 

If I type the commands it gives me error No such file or directory so I thought i should first download the requirement.txt file but I am not sure where to download it ..

**Comment by HarrietLyBui** [comment]
Have you git clone the snorkel repository? After that you can go into the snorkel folder where the requirement.txt is and install the dependencies with:

`pip install --requirement python-package-requirement.txt`

**Comment by ne1114** [comment]
Thank you so much for replying ! ^^
I didn't clone nor download the snorkel repository. Could you tell me where I should unzip the snorkel repositroy ??

**Comment by ne1114** [comment]
Actually I solved the problem Thank you !! I am also new to this GitHub ..so...  it seems that I made a stupid question

**Comment by ajratner** [comment]
Hopefully the new 0.7 release (coming in next few days prob?) will clear some of this up btw!

**Comment by stephenbach** [comment]
Version 0.7 is now available on master. Please try out the new installation instructions and let us know how it goes. Thanks!
