### ISSUE TITLE
Snorkel structured predictions?

### ISSUE THREAD

**Issue by cbockman** [HazyResearch/snorkel#961]
Just checking in on https://github.com/HazyResearch/snorkel/issues/838: 

> We have plans to extend Snorkel to the structured prediction setting---where e.g. you would model each sentence as a sequence of words/characters vs. just as a bag of candidate mentions--though; stay tuned!

Any update here?  Best I can tell, it hasn't made its way into the repo or any sort of paper, but please let me know if I'm missing anything!

**Comment by ajratner** [comment]
Unfortunately no code on master yet, although:
(1) we did post some initial work on adapting to sequence models [here](https://arxiv.org/pdf/1704.06360), and more might be around the corner here :) @jason-fries ?
(2) We have some stuff on multi-task structure (see [this workshop paper](https://ajratner.github.io/assets/papers/deem-metal-prototype.pdf)) coming soon too!

**Comment by ajratner** [comment]
Can check out the [Snorkel MeTaL repo](https://github.com/HazyResearch/metal) for some work here, FYI.  Closing for now, but feel free to re-open!
