### ISSUE TITLE
"Support for labeled data in generative model" -- where?

### ISSUE THREAD

**Issue by cbockman** [HazyResearch/snorkel#962]
Hi, I see that 0.6 is listed as supporting "labeled data in generative model".  

What does this mean precisely, and where is a good example of this in practice?  Does this mean that the model can build both using labeling functions and via some gold labels?  Or is it perhaps a reference to https://github.com/HazyResearch/snorkel/blob/1bb4ffb681cf7f97fd5c4bd03c3f86cebb48c0d3/tutorials/advanced/Hyperparameter_Search.ipynb?  

Thank you!

**Comment by cbockman** [comment]
Thanks!

Is there any guidance on how adding these is expected to improve performance of the system?  Or perhaps this is still an area of active research...  (I am familiar with a lot of the, e.g., semi-supervised, literature and realize this is a non-trivial and tough-to-generalize question...any sort of direction is helpful, however).

**Comment by ajratner** [comment]
There is still indeed plenty to explore in terms of this tradeoff space!  In general though (practically) we've found that a small amount of labeled data is best used as the dev set for LF development and/or hyperparameter tuning of end model

**Comment by sangha123** [comment]
If we want to use param_label what is the format for it? Is it a array/list of length(candidates) with labels {+1,-1,0}?

**Comment by ajratner** [comment]
Should be:
```
Binary: Values in {-1, 0, 1} [Default]
Categorical: Values in {0, 1, ..., K}
```
