### ISSUE TITLE
Input CoreNLP object must have 'dep_parents' attribute which is a list

### ISSUE THREAD

**Issue by afuyo** [HazyResearch/snorkel#964]
Hi, 
when running Workshop_6_Advanced_Grid_Search, under feature extraction I run into this error. What is the problem here? 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-785de7a1b904> in <module>()
      4 
      5 if F_train.size == 0:
----> 6     get_ipython().magic(u'time F_train = featurizer.apply(split=0, parallelism=1)')
      7 if F_dev.size == 0:
      8     get_ipython().magic(u'time F_dev  = featurizer.apply_existing(split=1, parallelism=1)')

/home/ubuntu/anaconda3/envs/py2Env/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2158         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2159         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2160         return self.run_line_magic(magic_name, magic_arg_s)
   2161 
   2162     #-------------------------------------------------------------------------

/home/ubuntu/anaconda3/envs/py2Env/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2079                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2080             with self.builtin_trap:
-> 2081                 result = fn(*args,**kwargs)
   2082             return result
   2083 

<decorator-gen-60> in time(self, line, cell, local_ns)

/home/ubuntu/anaconda3/envs/py2Env/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/home/ubuntu/anaconda3/envs/py2Env/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1191         else:
   1192             st = clock2()
-> 1193             exec(code, glob, local_ns)
   1194             end = clock2()
   1195             out = None

<timed exec> in <module>()

/home/ubuntu/playground/snorkel/snorkel/annotations.pyc in apply(self, split, key_group, replace_key_set, cids_query, **kwargs)
    186         super(Annotator, self).apply(cids, split=split, key_group=key_group,
    187             replace_key_set=replace_key_set, cids_query=cids_query,
--> 188             count=cids_count, **kwargs)
    189 
    190         # Load the matrix

/home/ubuntu/playground/snorkel/snorkel/udf.pyc in apply(self, xs, clear, parallelism, progress_bar, count, **kwargs)
     46         print("Running UDF...")
     47         if parallelism is None or parallelism < 2:
---> 48             self.apply_st(xs, progress_bar, clear=clear, count=count, **kwargs)
     49         else:
     50             self.apply_mt(xs, parallelism, clear=clear, **kwargs)

/home/ubuntu/playground/snorkel/snorkel/udf.pyc in apply_st(self, xs, progress_bar, count, **kwargs)
     69 
     70             # Apply UDF and add results to the session
---> 71             for y in udf.apply(x, **kwargs):
     72 
     73                 # Uf UDF has a reduce step, this will take care of the insert; else add to session

/home/ubuntu/playground/snorkel/snorkel/annotations.pyc in apply(self, cid, **kwargs)
    252         cid = cid[0]
    253         c    = self.session.query(Candidate).filter(Candidate.id == cid).one()
--> 254         for key_name, value in self.anno_generator(c):
    255 
    256             # Note: Make sure no duplicates emitted here!

/home/ubuntu/playground/snorkel/snorkel/features/relative_features.pyc in get_binary_span_feats(sidxs, sentence, stopwords)
     56     """Get binary (relation) span features from TreeDLib"""
     57     get_tdl_feats = compile_relation_feature_generator()
---> 58     xmltree = corenlp_to_xmltree(get_as_dict(sentence))
     59     s1_idxs, s2_idxs = sidxs
     60     if len(s1_idxs) > 0 and len(s2_idxs) > 0:

/home/ubuntu/playground/snorkel/tree_structs.pyc in corenlp_to_xmltree(s, prune_root)
     73   # Use the dep_parents array as a guide: ensure it is present and a list of ints
     74   if not('dep_parents' in s and type(s['dep_parents']) == list):
---> 75     raise ValueError("Input CoreNLP object must have a 'dep_parents' attribute which is a list")
     76   try:
     77     dep_parents = map(int, s['dep_parents'])

ValueError: Input CoreNLP object must have a 'dep_parents' attribute which is a list

**Comment by ajratner** [comment]
@jason-fries ?

**Comment by Anirudh-Muthukumar** [comment]
Why can't we use LabelAnnotator() in place of FeatureAnnotator()? 

Does FeatureAnnotator() alone generate a scipy.sparse.csr_matrix or it is possible to generate one with LabelAnnotator()?

**Comment by jason-fries** [comment]
Hi @Anirudh-Muthukumar 
The workshop materials are slightly out-of-date with the most recent Snorkel release. We're in the process of forward porting all of this material this week, so many of these issues will be resolved shortly. Thanks for being patient!

**Comment by jason-fries** [comment]
Fixed by latest workshop commit.
