### ISSUE TITLE
ValueError : No negative labels for SparseLogisticRegression

### ISSUE THREAD

**Issue by Anirudh-Muthukumar** [HazyResearch/snorkel#966]
When I am using SparseLogisticRegression for training the model as instructed in Workshop 6, I am getting a ValueError as shown:

<img width="1002" alt="screen shot 2018-06-26 at 12 22 05 pm" src="https://user-images.githubusercontent.com/18349470/41934446-94bc7d7e-793b-11e8-9ded-097e043c6291.png">
And my train_marginals is also displayed in it. 

I have manually annotated the dev_set using SentenceNgramViewer, still I am getting such an error.

What should I do to fix this issue?

**Comment by ajratner** [comment]
@Anirudh-Muthukumar This warning is notifying you that you have no negative training labels from the generative model (and thus the discriminative model wouldn't learn anything useful)- I'd check to make sure you're writing enough LFs that vote positively!

**Comment by Anirudh-Muthukumar** [comment]
I am dealing with numerical data, and I just have one labelling function in place. Is that not enough?

**Comment by ajratner** [comment]
If your one labeling function only outputs labels of one class, then this is not currently enough for Snorkel.  This is often referred in the literature as the "Positive-unlabeled (PU) learning" setting- it's actually a straightforward change to handle this here, but one we don't currently have implemented.

Closing for now, feel free to re-open!
