### ISSUE TITLE
Multi args candidate class

### ISSUE THREAD

**Issue by pelegb** [HazyResearch/snorkel#971]
Hi,
Thanks for this very interesting system.
I would like to add an optional marriage date to the spouse relations tutorial example. I thought of creating the following candidate class:
`Spouse = candidate_subclass('Spouse', ['person1', 'person2', 'marriage_date'])`
where the marriage_date can have a special "empty" value.
I thought of extending the Ngrams class so that it would return an "empty" ngram, i.e.:
`class MyNgrams(Ngrams):

    def apply(self, context):
        for res in super(MyNgrams, self).apply(context):
            yield res
        yield TemporarySpan(char_start=0, char_end=0, sentence=context)

cand_extractor = CandidateExtractor(Spouse, [ngrams, ngrams, my_ngrams], [person_matcher, person_matcher, date_matcher])`

I'm not sure how to continue regarding the labeling functions as I would like to separate them into ones that refer only to the people in the relation and others that refer to the date.
Am I in the correct direction?

Any help will be greatly appreciated.
Thanks

**Comment by ajratner** [comment]
Hi @pelegb ,

This seems like a great start!  The initial setup of the trinary candidate seems sensible, including the new empty value.  Could also define an explicit none value- either way, if you come up with a good solution, definitely submit a PR :)!

As for the last bit you mention--LFs that only refer to the people versus the dates: the way Snorkel currently works, the `Candidate` (which now consists of people and a date) is one object, so all labeling functions label the whole thing. As for what parts of it they look at (eg the people vs the date) to generate the labels- that's up to you!

Anyway, let us know how this goes!

**Comment by ajratner** [comment]
Closing for now, feel free to re-open!
