### ISSUE TITLE
Training on GPU?

### ISSUE THREAD

**Issue by littlewine** [HazyResearch/snorkel#974]
Hi there,

I am wondering whether it is possible to train the relation extraction LSTMs in GPU. 
I am also not sure how well they do parallelize and what performance improvements I can expect, but I think it might be worth to give it a shot.
Regarding that, I have two questions:

1) I tried to launch snorkel with tensorflow-gpu backend some time ago in v0.6, but I got an error which was possibly due to an older CUDA/cuDNN version I am using. Is there some specific version requirement?

2) In the **tensorflow** models, I can see that there is a "deterministic" parameter in the NoiseAwareModel, which seems to have to do something with the GPU training. (I am not sure what it does and what the consequences of using it are - if you could please elaborate a bit more on that).
```
    :param deterministic [EXPERIMENTAL / in development!] If True, attempts to
            make the model deterministic on GPU by replacing all reduce_ and 
            other non-deterministic operations; has no effect (other than 
            potential slight slowdown) for CPU (at least for single-threaded?).
```
I have also tried many threads in CPU training, but it doesn't seem to have any difference (actually there is a small slowdown).

I can see that v.0.7.0 beta includes also **pyTorch** models, with some indications that they can be trained on the GPU. Can you confirm that this works well / is tested? 
I have already written my code for v.0.6.2, so I am not sure how long it would take to migrate to the next version of snorkel.

Thanks a lot!

**Comment by jdunnmon** [comment]
@stephenbach @ajratner confirmed that (at least for me) GPU training doesn't currently work.  I have a working pytorch LSTM that subclasses the original `TFNoiseAwareModel`, will work on recasting this to fit the new pytorch API in v0.7.0.

**Comment by stephenbach** [comment]
@jdunnmon Can you document what doesn't work?

**Comment by sujitpal** [comment]
I wasn't sure if the patch above was usable or not, so I cloned the snorkel.learning.pytorch into a sibling package snorkel.learning.pytorch_gpu and used the .to(device) approach to mark portions of the computation to be on GPU if available. Compared with running on a CPU (AWS t3.xlarge), I observe an approximately 5x speedup on GPU (AWS p2.xlarge). I haven't done the nn.dataparallel change so this code is single GPU only. 

Code and installation/calling instructions are here, in case others find it useful -- https://github.com/sujitpal/snorkel-pytorch-lstm-gpu

**Comment by bhancock8** [comment]
Thanks for the contribution @sujitpal! Closing this for now.
