### ISSUE TITLE
learned coverage stat doesn't match my intuition

### ISSUE THREAD

**Issue by eloriundo** [HazyResearch/snorkel#975]
Hi, 
(following as a example cell 21 in the intro tutorial, ```In [21]: gen_model.learned_lf_stats()``` since I face a similar situation in my dataset) 
- Should I understand that accuracy and coverage correspond to alpha and beta in equation 1 of the NIPS paper?
- If so, why are coverages so high compared to the coverage of the labeling function, and so similar across LFs? my intuition is that beta should be close to the coverage of the labeling functions, and should be quite easy to fit (since the maximum likelihood estimate only depends on the proportion of labeled samples, doesn't need golden labels or anything else). I would guess that if the GM doesn't have enough samples or epochs or is too regularized, then the values will deviate only slightly around mean value, but that's also not what I see (the final values are around a value higher than any of the original values).

Maybe I just need to play more with the hyper parameters of the GM, but until now they are all around a value which is far to high for any of the LFs (same for the intro tutorial, only one LF has coverage of 0.6, while all learned coverages gravitate around 0.66). Or am I misunderstanding the meaning of coverage on the learned_stats?

**Comment by eloriundo** [comment]
A clearer example on this. In [this notebook](https://github.com/eloriundo/snorkel/blob/master/synthetic_tabular/synthetic_tabular.ipynb) I generated synthetic labels with known coverage and accuracy, and tried to recover those parameters using snorkel generative model. For accuracy it does a decent job (mostly fails for LFs with very low coverage). But for recovering coverage, it mostly ends up with all LFs having a similar coverage around 0.66, no relation with the original one. This shouldn't affect the rest of the workflow (since AFAIK you only need the accuracies to calculate the marginals), but still. Is it me misunderstanding the parameter? or maybe I need to use different settings on the generative model training?

**Comment by ajratner** [comment]
@eloriundo sorry for the delayed response on this, and thanks for the detailed issue!  This looks like a bug- computing the coverage can be done empirically (counting!) and is thus trivial, and so I think there's some small issue here.  Ultimately this parameter is not used during prediction in the basic generative model configuration... so it's probably not getting updated for this `gen_model.learned_lf_stats()` print out... will try to look into soon.

As for accuracies- that it would have lower quality on LFs with lower coverage roughly makes sense- you can think of the number of overlaps with other LFs as the number of samples the model as to learn from, so lower coverage = fewer overlaps = fewer samples to estimate the accuracy from
