### ISSUE TITLE
How to dump database in snorkel into a csv

### ISSUE THREAD

**Issue by HarrietLyBui** [HazyResearch/snorkel#977]
After parsing documents into sentences with Spacy CorpusParser, I would like to save the sentences and their metadata into a *.csv file to be able to load into the database later instead of having to parse the documents multiple times. How can I do this?

To my understanding, the database is saved to snorkel.db. How do I read in the database with SnorkelSession if I have to restart with a complete new jupyter notebook system?

**Comment by sillystring13** [comment]
Snorkel defaults to writing out your session data to a SQLite database file "snorkel.db" in the working directory.  There's a reference to it here in https://github.com/HazyResearch/snorkel/blob/e7b7a5538bda4a53537cd08325a682b10b10ac83/tutorials/workshop/Workshop_5_Advanced_Preprocessing.ipynb#L32

You can use an os environment variable to tell Snorkel where to look for the database 
https://github.com/HazyResearch/snorkel/blob/33db6f764210623071d00960956fc3bb68f3fc8e/snorkel/models/meta.py#L12-L14

I tested this out and it seems to work:
```
from snorkel import SnorkelSession
from snorkel.models.meta import snorkel_engine
from snorkel.parser.doc_preprocessors import DocPreprocessor
from snorkel.models.context import Document
import os

os.environ['SNORKELDB'] = 'sqlite:////snorkel.db'
session = SnorkelSession()
```

A quick check showed that the session contained the same number of documents and sentences as were processed in my first notebook.
```
from snorkel.models import Document, Sentence
print("Documents: ", session.query(Document).count())
print("Sentences: ", session.query(Sentence).count())
```
