### ISSUE TITLE
given labeling matrix + ground truth, helper function to compute accuracies + coverage 

### ISSUE THREAD

**Issue by vincentschen** [HazyResearch/snorkel#978]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/5819303/42409208-c8a2d964-818b-11e8-84a1-6c842f2cb5a1.png">

So that these steps don't need to be done by hand, especially when comparing to the generative model stats, which can be generated via `gen_model.learned_lf_stats()`

**Comment by paroma** [comment]
`L_train.lf_stats(session)` can generate a table of statistics about the label matrix (function [here](https://github.com/HazyResearch/snorkel/blob/b047dfb032560584752cb5952a82b90943529209/snorkel/annotations.py#L118)) with example in [intro tutorial, cell 16](https://github.com/HazyResearch/snorkel/blob/master/tutorials/intro/Intro_Tutorial_2.ipynb)
