### ISSUE TITLE
Connection in postgresql in v0.7?

### ISSUE THREAD

**Issue by littlewine** [HazyResearch/snorkel#979]
How can I connect to postgresql in v0.7?
The code I have been using in 0.6.2 is no longer working:

```
import os
os.environ['SNORKELDB'] = 'postgres:///snorkel07'
from snorkel import SnorkelSession
session = SnorkelSession()
```

Gives me the following error:
```
OperationalError: (psycopg2.OperationalError) could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
 (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by stephenbach** [comment]
Hmm... I'm a little stumped. The only code that should be executed is in
snorkel/__init__.py
snorkel/models/__init__.py
snorkel/models/meta.py
and the only changes in those in 0.7 were about absolute vs. relative imports.

I'm not in a position to test Postgres at my day job right now, but will test ASAP. In the meantime, can you confirm in case you haven't that you can connect to the DB outside of Snorkel? Can anyone else confirm working or not working?

**Comment by jason-fries** [comment]
In our workshop demo we use Postgres. Just confirmed it works with 0.7 using the following call
```
import os
os.environ['SNORKELDB'] = "postgresql:///spouse"
from snorkel import SnorkelSession
session = SnorkelSession()
```
definitely double check if the database is running as @stephenbach suggested.

**Comment by stephenbach** [comment]
Closing this issue. Please reopen if you're still experiencing issues.
