### ISSUE TITLE
Fast iteration over Query results

### ISSUE THREAD

**Issue by debnil** [HazyResearch/snorkel#981]
This is more of a SQLAlchemy question, but wondering if anyone in the Snorkel community has figured out a better solution. All SQLAlchemy tutorials simply iterate over a query result like so:
```
results = session.Query(Document).all()
for row in results:
   foo(row)
```
Is there a way to parallelize an operation over `results`? Trying traditional multiprocessing in Python throws a `DetachedInstanceError` due to attempting lazy-loading, but trying a `joinedload` or `subqueryload` takes enormous amounts of time due to our document size. 

Any pointers would be appreciated, and let me know if you need any clarifications.

**Comment by debnil** [comment]
Update: our fix is to query for Document IDs, and then multiprocess a function which creates a new Snorkel session and queries for each ID (to get statements and sentences). While substantially faster, this does require N+1 queries and N+1 sessions, where N is the number of document IDs. Ideally, we'd like to use SQLAlchemy's scoped_session or a similar native concurrency solution for a single Snorkel session. Does anyone have any experience or intuition doing this?

cc @stephenbach

**Comment by stephenbach** [comment]
You might have already seen `https://github.com/HazyResearch/snorkel/blob/master/snorkel/udf.py`, but that's the best way we've found to do multiprocessing and it sounds like exactly what you're doing.

I'm not familiar with scoped_session, but aren't multiple Python threads in the same process limited by the GIL? Why would it be faster than multiple processes interacting with a Postgres server?

**Comment by debnil** [comment]
Sounds good to us. One per worker is definitely a simplification of our approach. The GIL limit is true -- I don't think it's faster, just what SQLAlchemy built in to support. Closing this, thanks!
