### ISSUE TITLE
How to input data in snorkel database into brat annotation

### ISSUE THREAD

**Issue by HarrietLyBui** [HazyResearch/snorkel#983]
I was able to install brat independently with docker. However, I am not sure how to integrate brat with snorkel as I cannot open brat with the port snorkel generates.

**Comment by jason-fries** [comment]
The current implementation assumes BRAT is installed in a specific location so that Snorkel can write files to the correct directory. You could try sharing a volume in the Docker instance so there is a writeable path to the BRAT install directory. Then you just change `self.brat_root` in `brat.py` to match this path.

**Comment by HarrietLyBui** [comment]
May I ask for more specific guide on how to share a volume in the Docker instance with snorkel? Thank you!

**Comment by HarrietLyBui** [comment]
where am I supposed to find the brat.py file?

**Comment by jason-fries** [comment]
All BRAT files are found at:
`https://github.com/HazyResearch/snorkel/tree/master/snorkel/contrib/brat`

**Comment by HarrietLyBui** [comment]
I tried to install the lastest version of snorkel, and tried to run the install.sh script in the ~/snorkel/tree/master/snorkel/contrib/brat folder. I got the following error:

> cat: /home/ec2-user/snorkel/snorkel/contrib/brat/config_template.py: No such file or directory
cp: cannot stat ‘/home/ec2-user/snorkel/snorkel/contrib/brat/example-data/corpora’: No such file or directory
cp: cannot stat ‘/home/ec2-user/snorkel/snorkel/contrib/brat/example-data/tutorials’: No such file or directory
WARNING: failed to determine Apache group.

May I ask how to fix this error?

**Comment by jason-fries** [comment]
This looks like it's a AWS-related issue. I'd confirm that Snorkel/BRAT is installed in the appropriate places :)
