### ISSUE TITLE
[Tutorial][Crowdsourcing] 'Session' object has no attribute 'shape'

### ISSUE THREAD

**Issue by redcinelli** [HazyResearch/snorkel#984]
Hey there, I have just started using snorkel,
And i am currently trying to go through the tutorial, I am having an issue I can seem to resolve.

Cell 11, give me an error

<img width="936" alt="screen shot 2018-07-17 at 18 23 24" src="https://user-images.githubusercontent.com/4200886/42831405-885ca82e-89ee-11e8-9d59-72f8c80c76c0.png">

I have been through the install process with Conda.
My Jupyter kernel is the one created during the process.

I am not sure what to do.

If it can help here is my config:
- Mac OS 10.13.5
- Conda 4.5.4
- pyspark 2.3.0
- python 3.6.5

I guess that's about it.

**Comment by tmerrittsmith** [comment]
I think this might be an error in the code, I found the same issue.
Try this:

```
correct, incorrect = gen_model.error_analysis(session, L_train, train_cand_labels)
print("Number incorrect:{}".format(len(incorrect)))
```

**Comment by bhancock8** [comment]
Thanks for the update @tmerrittsmith . Yes, this notebook fell out of sync with other changes in the code. It is updated now in 0b74b7.
