### ISSUE TITLE
[Question] Fake news dataset example / guidelines

### ISSUE THREAD

**Issue by foobatman** [HazyResearch/snorkel#986]
Hello team, 

Really appreciate this great project! I would like to know what kind of techniques / label functions I should be looking at to potentially generate a fake news dataset using Snorkel. Any relevent reserach papers / pointers to articles would be really helpful. If anyone in community has already tried doing this and would like to shed some light upon the overall approach that would be very helpful.

**Comment by ajratner** [comment]
Hey @foobatman great topic!  By 'generate' I assume you mean use Snorkel to label it?  If so this sounds really cool- definitely sounds like a good area to apply Snorkel, although I don't have a ton of intuition for this particular setting off the top of my head!  But do let us know what you find (and if anyone else has resources would be cool to see!)

**Comment by ajratner** [comment]
You could check out some of @thodrek 's work [here](http://pages.cs.wisc.edu/~thodrek/) where he uses similar techniques as in Snorkel to do data cleaning, which could be relevant here!  And then I know there is a lot of work going on in the NLP community around this topic- would be great to see if any connection to Snorkel / weak supervision- keep us updated!

**Comment by henryre** [comment]
We're adding a document classification tutorial to v0.9, which should demonstrate how to use new the new API to label things like news articles. It would be super interesting to wrap existing tools e.g. http://www.fakenewschallenge.org/ in Snorkel. Closing for now, but feel free to reopen if you have any additional questions.
