### ISSUE TITLE
Construct own unlabaled dataset for labeling 

### ISSUE THREAD

**Issue by rmfajri** [HazyResearch/snorkel#992]
First of all, thank you for this great repo. 
How do i label my unlabeled text dataset with snorkel. I already followed the tutorial, it works fine. in first intro there is articles.tsv file, with daeb4cc3-95d9-4eb6-806f-ee6a0c28c07d as entry. I believe this could be the document ID, how do I create one. Furthermore, there is gold label with similar entry such as 36c3703b-bd5b-4888-be46-2f45bcb37f8e, I believe that this is a person name, with the starting character and end, How do i parse this.

https://github.com/HazyResearch/snorkel/issues/890 the same question with this close issue.
Thank you for your help

**Comment by paroma** [comment]
The entries can be interpreted as described [here](https://github.com/HazyResearch/snorkel/issues/890#issuecomment-373151786)

marking as Q&A and closing for now, feel free to reopen if needed!
