### ISSUE TITLE
Proper LF format

### ISSUE THREAD

**Issue by Coupdesinge** [HazyResearch/snorkel#994]
Hello,
For cardinality  > 2,  does it make a difference if LFs return more than two values?  For example, given classes A, B, C, D, would it be advisable for a _single_ LF to return 

A if .... 
else B if ...
else D if ...
else None

or should a single LF adjudicate on the presence or absence of only one class, i.e. A if... else None. 

Thank you:)

**Comment by stephenbach** [comment]
Hi Kate,

This is a great question with no one answer. We usually make this decision based on how related the heuristic(s) are.

In the first example, if the conditions are mutually exclusive, or they're all relevant to subsequent decisions (e.g., that the conditions for A and B are both false increases the probability that it's D), then making it one LF probably makes sense.

If you have LFs for different classes that are mostly independent (i.e., their mistakes are weakly correlated), then making them different LFs makes more sense.

Hope this is helpful. Please reopen the issue if you have any follow up questions, and we'd love to hear which approach works better for you.
