### ISSUE TITLE
Add explanation on what an UDF is

### ISSUE THREAD

**Issue by MaxG87** [HazyResearch/snorkel#995]
When taking a deep dive into Snorkels code, I repeatedly stumbled over UDF. It seems to be a very central concept. Unfortunately, I was not able to find any documentation on this. It would be great if there could be at least some documentation on the UDF class family.

Thank you very much.

**Comment by jrdeans** [comment]
UDF in many cases (and I believe it be the same case here) stands for User Defined Functions that allow you to apply custom python functions to the results of SQL searches. [Call python machine learning model from UDF or SP](https://dba.stackexchange.com/questions/160620/call-python-machine-learning-model-from-udf-or-sp) (See #2 in the answer)

I'm not certain as to the full extent of the UDF classes in Snorkel and what exactly they are doing, but my assumption is that they are just using UDFs with sqlalchemy to interact with the databases.

**Comment by ajratner** [comment]
Hey @MaxG87 thanks for pointing this out, and sorry for the delayed response; and @jrdeans thanks for jumping in!

"User defined function (UDF)" does indeed have a database meaning as explained by @jrdeans above, but in the repo we are mainly using it just in the colloquial sense- a synonym for labeling function basically!
