### ISSUE TITLE
Adding features to the discriminative model

### ISSUE THREAD

**Issue by barakl** [HazyResearch/snorkel#996]
Hi,

I'm trying to expand the Spouse tutorial in order to learn more about the snorkel system.

I managed to achieve pretty good performance with snorkel using relatively simple labeling functions and a labeled data set I have build, however I fear that the LSTM will not be able to generalize as well as I want it to since the LSTM model only has the word embeddings as its input layer (as far as I can tell by viewing the code, please let me know if any other features are used in the input layer)

Is there an option to add additional features to the LSTM like the word's pos tag (as a number) or the word's NER (as a number)

Thanks,
   Barak.

**Comment by paroma** [comment]
Since we focus more on the generative model, our goal was to provide default end models that work with common classification tasks. These models can definitely be improved and we would be glad to accept a PR that adds this functionality! Closing this for now (feel free to reopen)
