### ISSUE TITLE
Improve Signature of RNNBase train functions

### ISSUE THREAD

**Issue by MaxG87** [HazyResearch/snorkel#998]
The RNNBase.train function accepts an X_dev and some **kwargs and passes them on to TorchNoiseAwareModel.train. However, in TorchNoiseAware.train, it seems as if one either has to set both X_dev and Y_dev ore none. When only X_dev is provided, Y_dev gets its default value 'None' which will lead to a runtime crash in TorchNoiseAwareModel.score.

To make users more aware of this, the RNNBase.train function signature should either mention both or none of X_dev and Y_dev.

**Comment by ajratner** [comment]
Hey @MaxG87 that suggestion makes sense!  Happy to accept this modification as a PR if you want to contribute!

**Comment by vincentschen** [comment]
We're preparing for a large refactor in v0.9 which should change these signatures entirely. Closing for now, but feel free to open another issue if you have additional feedback!
