### ISSUE TITLE
Test TorchNoiseAwareModel.(train|score|...) arguments for sanity

### ISSUE THREAD

**Issue by MaxG87** [HazyResearch/snorkel#999]
This is related to #998. When X_dev is valid, it is implicitly assumed that Y_dev is too.

There could be checks to make sure to catch mismatches early. Otherwise the error might manifest itself as something obscure as broadcasting errors or 'unsupported types for *', as it happened to me.

**Comment by ajratner** [comment]
@MaxG87 thanks for this idea!  Happy to accept PRs, otherwise we'll try to cover this in our next pass / in #998 .  Closing for now, but feel free to reopen
